#!/usr/bin/env python3
"""Apply Brazilian Portuguese translations for days 41-60."""
import json

def get_translations():
    return {
        41: {
            "introduction": "Hoje vamos explorar uma mudança de mentalidade que pode destravar tudo na sua jornada de bem-estar. A mentalidade do \"copo vazio\" é sobre abordar esse processo com abertura, curiosidade e disposição para aprender — mesmo que sinta que \"já tentou de tudo\". Quando você esvazia seu copo de velhas suposições e decepções passadas, cria espaço para algo novo e bonito criar raízes.",
            "mainContent": "Muitas de nós chegam à jornada de bem-estar carregando um copo pesado — cheio até a borda de fracassos de dietas passadas, crenças rígidas sobre o que funciona e o que não funciona, e um ceticismo profundo nascido da decepção. \"Já tentei de tudo\", você pode dizer, ou \"Sei o que deveria fazer, só não consigo manter\". Esses sentimentos são completamente válidos, mas também podem se tornar barreiras que impedem você de ver novas possibilidades.\nA mentalidade do copo vazio, inspirada no conceito Zen de \"mente de iniciante\", te convida a deixar de lado essas histórias pesadas — pelo menos por agora. Não é sobre fingir que suas experiências passadas não aconteceram. É sobre escolher não deixá-las ditar o que é possível para você hoje. O que não funcionou cinco anos atrás pode funcionar lindamente agora, porque *você* é diferente agora. Seu corpo, suas circunstâncias, sua compreensão — tudo evoluiu.\nUm dos aspectos mais libertadores dessa mentalidade é soltar o pensamento tudo-ou-nada. Dietas passadas podem ter te ensinado que você está \"no caminho\" ou \"fora do caminho\", \"bem\" ou \"mal\". Esse pensamento rígido cria uma pressão enorme e inevitavelmente leva ao ciclo de perfeição, deslize, culpa e desistência. A abordagem do copo vazio diz: não existe um trem do qual cair. Existe apenas hoje e a próxima pequena escolha que você pode fazer.\nPratique curiosidade em vez de julgamento, especialmente quando os resultados parecem lentos ou diferentes do esperado. Em vez de \"Isso não está funcionando\", tente \"O que isso está me ensinando?\". Em vez de \"Falhei de novo\", tente \"O que posso ajustar?\". Essa mudança sutil transforma contratempos de evidências de fracasso em dados valiosos para sua jornada.\nIsso também é sobre reconhecer que o controle de peso não é puramente físico — é profundamente mental e emocional. Sua relação com a comida, seu diálogo interno, seus padrões de estresse, suas crenças sobre o que você merece — tudo isso tem um papel. Quando você aborda sua jornada com um copo vazio, cria espaço para abordar todas essas dimensões, não apenas a comida no seu prato.\nQuando o copo está vazio, há espaço para crescimento, para surpresa, para descobrir abordagens que você nunca considerou. Essa mentalidade reduz a resistência, diminui o estresse e permite que a consistência se forme naturalmente — tornando o bem-estar sustentável muito mais alcançável.",
            "keyTakeaways": [
                "Um copo vazio significa soltar suposições passadas para que novos hábitos possam crescer",
                "O pensamento tudo-ou-nada de dietas passadas cria pressão e autossabotagem",
                "Pratique curiosidade (\"O que posso aprender?\") em vez de julgamento (\"Eu falhei\")",
                "O controle de peso é mental e emocional, não apenas físico",
                "Abertura e disposição para aprender criam as condições para mudanças duradouras"
            ],
            "actionStep": "Escreva uma crença sobre si mesma ou seu corpo que tem carregado de uma experiência passada (por exemplo, \"Nunca consigo manter nada\" ou \"Meu metabolismo é quebrado\"). Depois, conscientemente escolha deixá-la de lado — apenas por esta semana — e aborde sua jornada como se estivesse começando do zero.",
            "journalPrimary": "Que suposições ou crenças de experiências passadas podem estar enchendo seu copo agora? Como seria deixá-las de lado e abordar sua jornada de bem-estar com olhos frescos?"
        },
        42: {
            "introduction": "Hoje vamos iluminar com gentileza e compaixão algo que toca tantas de nós — a alimentação emocional. Se você já se pegou buscando comida quando não estava fisicamente com fome, você não está sozinha, e não há absolutamente nenhuma vergonha nisso. Consciência é o primeiro passo para a liberdade, e hoje é sobre compreender, não julgar.",
            "mainContent": "A alimentação emocional acontece quando usamos comida para administrar sentimentos em vez de satisfazer fome física. É incrivelmente comum porque a comida proporciona conforto neuroquímico genuíno — ela dispara dopamina e serotonina, os mesmos químicos de bem-estar que amor e risada produzem. Seu corpo não está quebrado por buscar comida quando está triste, estressada, solitária ou até entediada. Ele está fazendo o que aprendeu a fazer.\nUma das ferramentas mais poderosas para entender seus padrões de alimentação emocional é um diário de comida-humor. Não precisa ser elaborado — simplesmente anote o que comeu, quando comeu e como estava se sentindo no momento. Estava estressada com o trabalho? Solitária após um dia longo? Ansiosa com algo que está por vir? Comemorando uma boa notícia? Ao longo de uma ou duas semanas, padrões vão surgir que podem te surpreender. Talvez você sempre busque chocolate às 15h quando a fadiga da tarde bate. Talvez os fins de semana tragam beliscos sem pensar quando você está sem estímulo.\nUma vez que identificou seus padrões, pode começar a desenvolver estratégias de enfrentamento sem comida para cada gatilho emocional. É aqui que a verdadeira transformação acontece. Se estresse é seu gatilho, talvez respiração profunda, uma caminhada curta ou ligar para uma amiga possam servir o mesmo propósito reconfortante. Se tédio impulsiona sua alimentação, talvez um hobby, um quebra-cabeça ou uma mudança de cenário preencheria esse vazio. Se solidão é a raiz, conexão — mesmo enviar uma mensagem para alguém que você se importa — pode ser o alimento que você realmente precisa.\nÉ importante enfatizar que o objetivo não é nunca mais comer por razões emocionais — esse é um padrão irreal que te prepara para o fracasso. O objetivo é consciência e escolha. Às vezes você pode escolher ter aquela tigela reconfortante de sopa em um dia difícil, e está perfeitamente bem. A diferença é que é uma escolha consciente em vez de uma reação automática, e você tem outras ferramentas no seu kit também.\nSeja incrivelmente gentil consigo mesma nesse processo. Padrões de alimentação emocional frequentemente se desenvolveram na infância e foram reforçados ao longo de décadas. Desfazê-los leva tempo, compaixão e paciência. Cada momento de consciência — mesmo quando você ainda escolhe comer — é progresso.",
            "keyTakeaways": [
                "A alimentação emocional é uma resposta comum e compreensível — não uma falha de caráter",
                "Um diário de comida-humor revela padrões entre emoções e alimentação",
                "Desenvolver estratégias sem comida para gatilhos específicos é transformador",
                "O objetivo é escolha consciente, não perfeição",
                "Autocompaixão é essencial ao explorar esses padrões"
            ],
            "actionStep": "Comece um diário simples de comida-humor hoje. Para cada refeição ou lanche, anote o que comeu, o horário e seu estado emocional. Faça isso pelos próximos três dias e veja que padrões surgem.",
            "journalPrimary": "Pense em uma vez recente que comeu sem estar fisicamente com fome. O que estava sentindo? Que necessidade tentava suprir com comida, e o que mais poderia ter satisfeito essa necessidade?"
        },
        43: {
            "introduction": "Hoje vamos explorar o jejum intermitente — um assunto que tem recebido muita atenção, e com razão. Mas aqui está o que quero que saiba desde o início: o jejum intermitente é uma *ferramenta*, não uma regra. Funciona maravilhosamente para algumas pessoas e não é adequado para outras, e está tudo bem. Vamos explorar juntas para que você possa decidir se pode apoiar sua jornada.",
            "mainContent": "O jejum intermitente não é sobre *o que* você come — é sobre *quando* você come. Em vez de beliscar constantemente ao longo do dia, envolve comer dentro de uma janela de tempo definida e dar ao seu corpo um descanso da digestão nas horas restantes. Esse período de descanso permite que os níveis de insulina caiam, o que pode mudar seu corpo do modo de armazenamento de gordura para o modo de queima de gordura. É um processo natural que nossos ancestrais experimentavam regularmente.\nA abordagem mais popular é o método 16:8, onde você jejua por 16 horas e come dentro de uma janela de 8 horas. Para muitas pessoas, isso simplesmente significa pular o café da manhã e comer das 12h às 20h. Se parecer ambicioso demais, o método 14:10 é um ponto de partida mais gentil — talvez comendo das 10h às 20h. No outro extremo, o método 18:6 comprime a alimentação em uma janela de 6 horas para quem achar confortável.\nTambém existem abordagens semanais. O método 5:2 envolve comer normalmente cinco dias por semana e reduzir significativamente as calorias em dois dias não consecutivos. O jejum em dias alternados alterna entre alimentação normal e dias de muito baixa caloria. E o OMAD (Uma Refeição por Dia) concentra toda a ingestão em uma única refeição, embora essa seja uma abordagem mais avançada que não é adequada para todos.\nA coisa mais importante a entender é que o jejum intermitente deve ser sustentável, não punitivo. Se você está aguentando firme durante a janela de jejum, contando cada minuto até poder comer, ou comendo compulsivamente quando a janela abre, essa ferramenta não está te servindo — e não há vergonha em deixá-la de lado. A abordagem certa é aquela que apoia equilíbrio hormonal, paz mental e nutrição consistente.\nQuando o jejum intermitente funciona bem, as pessoas frequentemente relatam pensamento mais claro, energia mais estável, menos desejos e uma relação mais simples com a comida. Remove a tomada de decisão constante sobre refeições e lanches e pode ajudar a resetar seus sinais de fome ao longo do tempo. Mas funciona melhor quando combinado com refeições equilibradas e ricas em nutrientes durante a janela alimentar — jejum não é passe livre para comer qualquer coisa.\nSe está interessada em experimentar, comece gentilmente. Talvez simplesmente estenda seu jejum noturno natural por uma ou duas horas e veja como seu corpo responde. Ouça com atenção — seu corpo vai te dizer o que precisa.",
            "keyTakeaways": [
                "O jejum intermitente é sobre quando você come, não o que come",
                "O método 16:8 é o mais popular; opções mais gentis como 14:10 existem",
                "O jejum permite que a insulina caia, apoiando a queima natural de gordura",
                "Deve ser sustentável e apoiador, nunca punitivo",
                "Comece gentilmente e ouça a resposta do seu corpo"
            ],
            "actionStep": "Se o jejum intermitente te interessa, tente um experimento gentil: estenda seu jejum noturno por apenas uma hora esta noite e amanhã de manhã. Se normalmente toma café às 7h, espere até as 8h. Observe como se sente — energizada ou esgotada? Calma ou ansiosa?",
            "journalPrimary": "Qual é seu padrão alimentar atual ao longo do dia? Como se sente sobre a ideia de dar ao seu corpo um intervalo mais longo da digestão? Parece libertador ou restritivo para você?"
        },
        44: {
            "introduction": "Lanchar tem uma má reputação, mas aqui está a verdade: lanchar de forma inteligente pode ser sua arma secreta para manter a energia, prevenir fome extrema e fazer melhores escolhas nas refeições principais. Hoje vamos aprender como fazer os lanches trabalharem *a seu favor* em vez de contra. É tudo sobre intenção e preparação!",
            "mainContent": "A diferença entre lanchar de forma que apoia seus objetivos e lanchar de forma que os prejudica muitas vezes se resume a uma coisa: planejamento. Quando você tem uma estratégia de lanches bem pensada, é muito menos provável se encontrar mergulhada em um pacote de batata chips às 15h. Não é sobre força de vontade — é sobre preparação encontrando a fome no momento certo.\nOs lanches mais eficazes combinam proteína com fibra. Essa combinação funciona lindamente porque a proteína te mantém satisfeita enquanto a fibra retarda a digestão, criando uma liberação suave e sustentada de energia. Uma maçã com pasta de amendoim é um exemplo perfeito — a fibra da maçã e a proteína e gordura saudável da pasta de amendoim trabalham juntas para manter a fome à distância por horas. Outras opções maravilhosas incluem vegetais com homus, um punhado de castanhas com uma fruta, ou iogurte grego com frutas vermelhas.\nConsciência de porções é importante com lanches. O objetivo é fazer a ponte entre as refeições, não ter um segundo almoço. Manter os lanches na faixa de 100-200 calorias é uma diretriz útil. Uma dica prática: porcione seus lanches em porções individuais em vez de comer direto da embalagem. Quando come de um saco ou recipiente grande, é incrivelmente fácil perder a noção de quanto consumiu — não porque falta disciplina, mas porque sua atenção está em outro lugar.\nPlanejar seus lanches no início da semana — assim como planejaria suas refeições — remove a tomada de decisão diária que pode levar a escolhas menos favoráveis. Quando você abre a geladeira e vê um recipiente de vegetais lavados e cortados ao lado de homus, ou um saco de mix de castanhas pré-porcionado na bolsa do trabalho, a escolha saudável se torna a escolha fácil. Torne nutrir seu corpo o mais conveniente possível.\nO timing também importa. Se você chega faminta ao jantar, um lanche bem calculado à tarde pode prevenir o tipo de fome extrema que leva a comer demais à noite. Pense no lanche estratégico como uma forma gentil de manter seu açúcar no sangue estável e seu humor equilibrado ao longo do dia.",
            "keyTakeaways": [
                "Planejar lanches com antecedência previne escolhas impulsivas e menos favoráveis",
                "A combinação proteína mais fibra cria satisfação duradoura",
                "Mantenha lanches na faixa de 100-200 calorias para fazer ponte entre refeições",
                "Pré-porcione lanches em vez de comer da embalagem",
                "O timing estratégico previne fome extrema e excessos noturnos"
            ],
            "actionStep": "Prepare três lanches saudáveis agora para os próximos dias. Algumas ideias fáceis: lave e corte vegetais para mergulhar em homus, porcione saquinhos de castanhas, ou fatie uma maçã para acompanhar sachês individuais de pasta de amendoim. Coloque-os onde você verá primeiro quando a fome bater.",
            "journalPrimary": "Quando você tende a lanchar durante o dia? Costuma ser por fome física, ou outra coisa como tédio, hábito ou estresse? Como ter lanches planejados poderia mudar sua experiência da tarde?"
        },
        45: {
            "introduction": "Prepare-se para se apaixonar pelo seu armário de temperos! Hoje vamos explorar como especiarias e ervas simples podem cumprir dupla função — adicionando sabor incrível às suas refeições enquanto realmente apoiam o bem-estar do seu corpo. Essas pequenas potências são usadas há séculos na medicina tradicional, e a ciência moderna está confirmando o que nossos ancestrais já sabiam.",
            "mainContent": "Especiarias e ervas são verdadeiramente um presente da natureza para qualquer pessoa em jornada de bem-estar. Adicionam sabor e complexidade enormes às refeições sem contribuir calorias significativas, tornando-se a ferramenta definitiva para criar comida que você realmente ama comer. Mas além do sabor, muitas especiarias comuns têm propriedades genuínas de apoio metabólico e à saúde que podem complementar seus esforços.\nA pimenta caiena contém capsaicina, o composto que cria seu ardor. A capsaicina aumenta a termogênese — a produção de calor do corpo — que temporariamente aumenta a queima de calorias. Mesmo uma pequena pitada adicionada às suas refeições pode fazer diferença. Além do metabolismo, a caiena também pode ajudar a reduzir levemente o apetite. Se não está acostumada a comida picante, comece com apenas uma pitadinha e vá aumentando.\nA canela é uma especiaria quente e reconfortante com propriedades notáveis de regulação do açúcar no sangue. Pesquisas sugerem que a canela pode melhorar a sensibilidade à insulina, ajudando seu corpo a processar a glicose mais eficientemente. Uma pitada na aveia matinal, no café ou misturada no iogurte é uma forma deliciosa de incorporá-la diariamente. Satisfaz aquele desejo por algo doce sem açúcar adicionado.\nO gengibre é uma potência digestiva que tem sido usado há milhares de anos para acalmar estômagos e apoiar a digestão saudável. Pode ajudar a reduzir inchaço, aliviar náuseas e até tem propriedades anti-inflamatórias. Gengibre fresco ralado em refogados, chá de gengibre ou até um molho de salada à base de gengibre são formas maravilhosas de aproveitar essa raiz versátil.\nA cúrcuma, com sua linda cor dourada, contém curcumina — um dos compostos anti-inflamatórios mais potentes da natureza. A inflamação crônica está ligada ao ganho de peso e dificuldade em perdê-lo, então incorporar cúrcuma na sua cozinha pode apoiar a capacidade do seu corpo de liberar excesso de peso. Uma dica: sempre combine cúrcuma com uma pitada de pimenta-do-reino, que aumenta a absorção da curcumina em até 2.000%.\nA beleza das ervas e especiarias é que convidam criatividade e aventura para sua cozinha. Experimente livremente — tente alecrim em vegetais assados, manjericão nas saladas, cominho nas sopas, ou páprica defumada nas proteínas. Cada nova combinação é um passo para tornar a alimentação saudável algo que você genuinamente espera com ansiedade.",
            "keyTakeaways": [
                "A pimenta caiena aumenta a termogênese e pode ajudar a reduzir o apetite",
                "A canela ajuda a regular o açúcar no sangue e satisfaz desejos por doces naturalmente",
                "O gengibre apoia a digestão e reduz inflamação e inchaço",
                "A curcumina da cúrcuma é um poderoso anti-inflamatório (combine com pimenta-do-reino!)",
                "Ervas e especiarias tornam a alimentação saudável deliciosa, criativa e sem calorias"
            ],
            "actionStep": "Escolha uma especiaria da lição de hoje que não usa regularmente. Adicione-a a uma refeição hoje — canela no café da manhã, gengibre no chá da tarde, caiena no jantar, ou cúrcuma numa sopa ou refogado. Observe como realça tanto o sabor quanto como você se sente.",
            "journalPrimary": "Que especiarias e ervas estão atualmente na sua cozinha? Há alguma que está curiosa para experimentar? Como explorar novos sabores poderia tornar suas refeições mais empolgantes e satisfatórias?"
        },
        46: {
            "introduction": "Hoje vamos abordar um tema sensível mas importante com compaixão e honestidade. Se você já sentiu que certos alimentos têm poder sobre você — como se simplesmente não conseguisse parar depois de começar — não é imaginação, e certamente não é fraqueza. Há ciência real por trás do porquê alguns alimentos são tão difíceis de resistir, e entender isso é o primeiro passo para retomar seu poder.",
            "mainContent": "A dependência alimentar é um conceito que ganhou suporte científico significativo nos últimos anos. Estudos de imagem cerebral mostraram que alimentos altamente processados — particularmente aqueles que combinam açúcar, gordura e sal — ativam os mesmos centros de recompensa no cérebro que outras substâncias viciantes. Esses alimentos disparam uma onda de dopamina, o neurotransmissor associado ao prazer e recompensa, criando um impulso poderoso de buscá-los repetidamente.\nIsso não é acidente. Muitos alimentos processados são literalmente projetados por cientistas de alimentos para atingir o que a indústria chama de \"ponto de êxtase\" — a combinação perfeita de doçura, salinidade e textura que te faz querer mais. São projetados para anular seus sinais naturais de saciedade. Quando sente que \"não consegue parar\" de comer certas batatas chips, biscoitos ou balas, não é uma falha pessoal — é o alimento fazendo exatamente o que foi projetado para fazer.\nO primeiro passo em direção à liberdade é reconhecer seus alimentos-gatilho pessoais. São os alimentos específicos que você acha praticamente impossível comer com moderação. A lista de cada pessoa é diferente. Para algumas, é sorvete; para outras, são chips salgados ou pão fresquinho. Sem julgamento aqui — apenas consciência. Uma vez que identifica seus gatilhos, pode fazer uma escolha consciente sobre sua exposição a eles.\nLimitar a exposição não significa que nunca mais pode ter esses alimentos. Significa ser estratégica — talvez não mantê-los em casa onde te chamam da despensa, ou escolher apreciá-los em porções individuais fora de casa em vez de comprar o tamanho família. É sobre se preparar para o sucesso em vez de depender apenas da força de vontade, porque força de vontade é um recurso limitado.\nReduzir gradualmente seu consumo de alimentos altamente processados permite que suas papilas gustativas e química cerebral se recalibrem. Com o tempo, os desejos diminuem. Alimentos integrais começam a ter um sabor mais satisfatório, e a atração intensa dos processados suaviza. Esse processo leva paciência — às vezes várias semanas — mas a liberdade do outro lado vale absolutamente a pena.",
            "keyTakeaways": [
                "Alimentos altamente processados são projetados para disparar respostas cerebrais viciantes",
                "Isso é uma resposta neuroquímica, não uma falha de caráter ou falta de força de vontade",
                "Identificar seus alimentos-gatilho pessoais é o primeiro passo para a liberdade",
                "Limite a exposição estrategicamente em vez de depender apenas da força de vontade",
                "Papilas gustativas e desejos se recalibram com o tempo ao reduzir alimentos processados"
            ],
            "actionStep": "Faça uma lista de 3-5 alimentos que você acha mais difícil comer com moderação — seus alimentos-gatilho pessoais. Para cada um, pense numa estratégia para reduzir sua exposição esta semana (não manter em casa, comprar porções individuais, etc.).",
            "journalPrimary": "Quais alimentos parecem mais difíceis de controlar? Quando começou sua relação com esses alimentos, e como entender a ciência da dependência alimentar muda como você se sente sobre si mesma?"
        },
        47: {
            "introduction": "Seu intestino é o lar de trilhões de organismos minúsculos que desempenham um papel surpreendentemente grande na sua saúde geral e jornada de bem-estar. Hoje vamos explorar o mundo maravilhoso dos probióticos — as bactérias benéficas que apoiam digestão, imunidade e até controle de peso. Cuidar do seu intestino é verdadeiramente um ato de amor ao corpo inteiro.",
            "mainContent": "Seu microbioma intestinal — a comunidade de bactérias vivendo no seu sistema digestivo — é como um jardim. Quando o jardim é saudável e diverso, tudo prospera: sua digestão funciona suavemente, seu sistema imunológico fica forte, seu humor permanece equilibrado e seu corpo gerencia o peso mais eficazmente. Probióticos são as \"bactérias boas\" que ajudam a manter esse jardim florescendo.\nPesquisas têm cada vez mais ligado a saúde intestinal ao controle de peso. Estudos descobriram que pessoas com peso saudável tendem a ter bactérias intestinais mais diversas do que aquelas que lutam com o peso. Certas cepas de bactérias benéficas parecem influenciar quão eficientemente extraímos calorias dos alimentos, quanto de gordura armazenamos e até quão famintas ou satisfeitas nos sentimos. Embora ainda estejamos aprendendo os detalhes, uma coisa é clara: apoiar sua saúde intestinal apoia sua jornada de bem-estar.\nAlimentos fermentados são a forma mais deliciosa e natural de introduzir probióticos no seu sistema. Iogurte (procure \"culturas vivas ativas\" no rótulo) é talvez a opção mais acessível. Kefir, uma bebida de leite fermentado ácida, contém cepas de bactérias benéficas ainda mais diversas. Chucrute, kimchi e kombucha são outras opções maravilhosas que trazem diferentes cepas bacterianas e sabores ao seu prato. Comece com porções pequenas se esses alimentos são novos para você — seu intestino precisa de tempo para se ajustar.\nMas probióticos são apenas metade da equação. Essas bactérias boas precisam de comida para prosperar, e é aí que os prebióticos entram. Alimentos prebióticos contêm tipos de fibra que alimentam suas bactérias intestinais benéficas, ajudando-as a se multiplicar e florescer. Cebolas, alho, bananas, aspargos e aveia são todos excelentes fontes prebióticas. Pense assim: probióticos plantam as sementes, e prebióticos fornecem o fertilizante.\nSe sua dieta é limitada em alimentos fermentados, um suplemento probiótico de qualidade pode ser uma adição útil. Procure suplementos com múltiplas cepas e pelo menos 10 bilhões de UFC (unidades formadoras de colônia). Armazene conforme indicado — alguns precisam de refrigeração. No entanto, suplementos funcionam melhor junto a uma dieta variada e rica em fibras, não como substituto.",
            "keyTakeaways": [
                "Um microbioma intestinal diverso apoia digestão, imunidade, humor e controle de peso",
                "Alimentos fermentados como iogurte, kefir, chucrute e kimchi são fontes naturais de probióticos",
                "Alimentos prebióticos (cebola, alho, banana, aveia) alimentam e apoiam bactérias benéficas",
                "Comece com porções pequenas de alimentos fermentados e aumente gradualmente",
                "Suplementos de qualidade podem ajudar mas funcionam melhor junto a uma dieta variada e rica em fibras"
            ],
            "actionStep": "Adicione um alimento rico em probióticos ao seu dia hoje — uma porção de iogurte com culturas vivas, uma garfada de chucrute com sua refeição, ou um copo pequeno de kombucha. Observe como sua digestão se sente nos próximos dias.",
            "journalPrimary": "Como você descreveria sua saúde digestiva? Já experimentou alimentos fermentados, e se sim, quais curtiu? Como priorizar a saúde intestinal pode parecer um ato de autocuidado?"
        },
        48: {
            "introduction": "A comida está entrelaçada no tecido da nossa vida social — celebrações, encontros, jantares com amigos, feriados em família. E isso é lindo! Hoje vamos aprender como navegar essas situações sociais com graça e confiança, para que você possa curtir a companhia, saborear a comida e se manter alinhada com seus objetivos de bem-estar — sem se sentir privada ou constrangida.",
            "mainContent": "Um dos maiores desafios que as pessoas enfrentam na jornada de bem-estar não é cozinhar em casa — é o que acontece quando saem pela porta. A alimentação social vem com suas próprias pressões: porções grandes, comidas ricas, amigos bem-intencionados que insistem que você \"coma só mais um pouquinho\", e o desejo de se encaixar em vez de se destacar. Mas com algumas estratégias simples, você pode navegar essas situações lindamente.\nA primeira estratégia é maravilhosamente simples: coma um lanche saudável antes de ir. Chegar a uma festa ou restaurante genuinamente faminta é receita para comer demais. Um lanche pequeno e equilibrado — vegetais com homus, um punhado de castanhas, ou uma fruta com pasta de amendoim — tira a borda da fome para que possa fazer escolhas de um lugar de calma em vez de desespero.\nAo jantar em restaurantes, procure opções grelhadas, no vapor, assadas ou ao forno no cardápio. Esses métodos de cozimento tendem a ser mais leves que pratos fritos ou salteados. Não hesite em pedir modificações — a maioria dos restaurantes fica feliz em atender pedidos como molho à parte, vegetais no lugar de batata frita, ou proteína grelhada em vez de empanada. Você não está sendo difícil; está honrando seu corpo.\nEm encontros e bufês, pratique a arte da observação. Antes de colocar qualquer coisa no prato, caminhe ao longo de toda a mesa e decida o que realmente quer. Escolha as coisas que parecem mais apetitosas e nutritivas, e pule os itens que estão ali \"só por estar\". Encha pelo menos metade do prato com vegetais e saladas, depois adicione porções moderadas de proteínas e outros alimentos que genuinamente deseja.\nTalvez o mais importante: solte a pressão de limpar o prato. Você não tem obrigação de terminar tudo que foi servido, seja num restaurante ou na casa de alguém querido. Está tudo bem deixar comida. Sobras podem ser levadas para casa e apreciadas depois, e seu corpo nunca é uma lata de lixo. Aprender a parar quando está confortavelmente satisfeita — independente do que ficou no prato — é uma das habilidades mais libertadoras que vai desenvolver.",
            "keyTakeaways": [
                "Coma um lanche pequeno e equilibrado antes de eventos sociais para não chegar faminta",
                "Escolha opções grelhadas, no vapor ou assadas e peça modificações",
                "Observe o bufê primeiro, depois escolha com atenção em vez de empilhar tudo",
                "Você nunca tem obrigação de limpar o prato",
                "Foque nas pessoas e na conexão, não apenas na comida"
            ],
            "actionStep": "Pense na sua próxima situação de alimentação social. Planeje uma estratégia específica que vai usar — ter um lanche antes, pesquisar o cardápio online com antecedência, ou decidir encher metade do prato com vegetais. Ter um plano remove a ansiedade.",
            "journalPrimary": "Como se sente comendo diferente das pessoas ao seu redor em situações sociais? O que te ajudaria a se sentir mais confiante e confortável fazendo escolhas que se alinham com seus objetivos?"
        },
        49: {
            "introduction": "Seja seu café da manhã, um chá da tarde ou um impulso pré-treino, a cafeína é uma das substâncias mais consumidas no mundo. Hoje vamos explorar como a cafeína pode realmente apoiar sua jornada de bem-estar quando usada com sabedoria — e como evitar as armadilhas que podem trabalhar contra seus objetivos.",
            "mainContent": "A cafeína é um estimulante natural que, quando usada com atenção, pode genuinamente apoiar seus objetivos de bem-estar. Pesquisas mostram consistentemente que a cafeína proporciona um impulso temporário ao metabolismo — estudos sugerem que pode aumentar a taxa metabólica em 3-11%, com efeitos maiores em indivíduos magros. Embora esse impulso seja modesto, é um efeito real e mensurável que se acumula com o tempo, especialmente quando combinado com outros hábitos saudáveis.\nUm dos benefícios mais bem documentados da cafeína é sua capacidade de melhorar o desempenho físico. Estimula o sistema nervoso, sinaliza às células de gordura para quebrarem gordura corporal e pode melhorar o desempenho no exercício em média 11-12%. Isso significa que seu café da manhã antes de uma caminhada ou treino não é apenas conforto — está genuinamente ajudando você a tirar mais do seu movimento.\nPorém, como você consome cafeína importa enormemente. Um café preto ou chá puro tem virtualmente zero calorias e entrega benefício puro. Mas quando adiciona açúcar, creme, xaropes aromatizados ou cobertura chantilly, sua bebida saudável pode rapidamente se tornar uma sobremesa em copo. Algumas bebidas populares de cafeteria contêm 400-500 calorias — mais que muitas refeições. Se aprecia bebidas de café, tente gradualmente reduzir os adoçantes e escolher opções de leite com menos calorias. Pode se surpreender com quão rápido se adapta e até prefere menos doçura.\nO timing é igualmente importante. A cafeína tem meia-vida de cerca de 5-6 horas, o que significa que metade da cafeína do seu café da tarde ainda está circulando no seu sistema na hora de dormir. Como sono de qualidade é tão crucial para o controle de peso (lembre do Dia 33!), limitar o consumo de cafeína após as 14h é uma prática sábia. Isso protege seu sono sem exigir que desista do seu amado ritual matinal.\nModeração é a chave. A maioria das organizações de saúde sugere que até 400 mg de cafeína por dia — aproximadamente 3-4 xícaras de café coado — é seguro para a maioria dos adultos. Ouça seu corpo: se a cafeína te deixa nervosa, ansiosa ou perturba seu sono mesmo dentro desses limites, reduza para um nível que pareça apoiador em vez de estressante.",
            "keyTakeaways": [
                "A cafeína temporariamente aumenta o metabolismo em 3-11% e melhora o desempenho físico",
                "Como prepara seu café importa — evite açúcares, xaropes e creme adicionados",
                "Limite a cafeína após as 14h para proteger a qualidade crucial do sono",
                "Até 400 mg por dia (3-4 xícaras) é geralmente seguro para maioria dos adultos",
                "Ouça seu corpo e encontre a quantidade que apoia em vez de estressar"
            ],
            "actionStep": "Se bebe bebidas com cafeína, avalie o que está adicionando. Desafie-se a reduzir uma coisa esta semana — metade do açúcar, um leite mais leve, ou pular o xarope aromatizado. Observe se se adapta mais rápido do que esperava.",
            "journalPrimary": "Que papel a cafeína desempenha na sua rotina diária? Parece uma ferramenta de apoio ou algo de que depende? Como ajustar seus hábitos de cafeína poderia apoiar tanto sua energia quanto seu sono?"
        },
        50: {
            "introduction": "Você já ouviu que precisa comer tudo no prato? Muitas de nós fomos criadas com essa mensagem, e embora venha de um lugar amoroso, pode estar silenciosamente trabalhando contra a sabedoria natural do seu corpo. Hoje vamos gentilmente desempacotar esse hábito tão enraizado e aprender a confiar nos sinais de saciedade do seu corpo.",
            "mainContent": "\"Limpe seu prato\" é uma das mensagens mais universais da infância. Talvez tenha ouvido \"Há crianças passando fome que adorariam essa comida\" ou \"Não pode sair da mesa até o prato estar vazio\". Essas mensagens eram bem-intencionadas — geralmente enraizadas em não querer desperdiçar comida ou garantir que crianças recebessem nutrição adequada. Mas como adultas, essa programação pode silenciosamente anular os sinais naturais do corpo, nos ensinando a comer baseado no que está no prato em vez do que está no estômago.\nAqui está uma verdade que vale a pena sentar com ela: terminar tudo no prato é um comportamento aprendido, não uma necessidade biológica. Seu corpo tem seu próprio sistema sofisticado para dizer quando já comeu o suficiente. Quando consistentemente anula esse sistema comendo além da saciedade, gradualmente perde o contato com ele. A boa notícia é que essa conexão pode ser reconstruída — só leva prática e paciência.\nComece dando permissão a si mesma para parar de comer quando estiver confortavelmente satisfeita, mesmo que reste comida no prato. Pode ser desconfortável no início, especialmente se deixar comida dispara culpa ou memórias de ser mandada comer tudo. Lembre-se gentilmente: sobras não são desperdício. Na verdade, comer demais — consumir mais do que seu corpo precisa — também não é respeitoso com seu corpo. Você pode guardar sobras para o almoço de amanhã ou um lanche futuro.\nDesacelerar durante as refeições é um aliado poderoso aqui. Leva aproximadamente 20 minutos para o cérebro receber sinais de saciedade do estômago. Quando come rápido, frequentemente consome muito mais do que precisa antes desses sinais chegarem. Coloque o garfo na mesa entre mordidas, mastigue bem, tome goles de água e converse se estiver comendo com outros. Essas pequenas pausas criam espaço para a sabedoria do seu corpo ser ouvida.\nOutra abordagem útil é se servir de porções menores inicialmente, sabendo que sempre pode repetir se realmente ainda estiver com fome. Isso remove a pressão do prato grande te encarando e oferece pontos naturais de decisão ao longo da refeição. Quando se serve menos e depois checa com seu corpo antes de decidir se quer mais, está construindo um hábito bonito de alimentação consciente e responsiva.",
            "keyTakeaways": [
                "Terminar tudo no prato é um hábito aprendido, não uma necessidade biológica",
                "Comer demais não é mais respeitoso que ter sobras",
                "Desacelere — sinais de saciedade levam cerca de 20 minutos para se registrar",
                "Comece com porções menores e repita apenas se realmente com fome",
                "Reconstruir sua conexão com sinais de saciedade leva prática e paciência"
            ],
            "actionStep": "Na sua próxima refeição, sirva-se um pouco menos do que normalmente faria. Coma devagar, e quando terminar o que está no prato, pause por cinco minutos antes de decidir se quer mais. Cheque com seu corpo: estou confortavelmente satisfeita, ou realmente ainda estou com fome?",
            "journalPrimary": "Que mensagens você recebeu sobre comida e limpar o prato quando era criança? Como essas mensagens podem estar aparecendo nos seus hábitos alimentares hoje? Como seria dar permissão a si mesma para parar quando satisfeita?"
        },
        51: {
            "introduction": "Você provavelmente já ouviu os termos \"proteína\", \"carboidratos\" e \"gorduras\", mas hoje vamos mergulhar mais fundo em como esses três macronutrientes trabalham juntos para abastecer seu corpo, apoiar seus objetivos e ajudá-la a se sentir no seu melhor. Pense nos macronutrientes como os três pilares que sustentam toda a sua base nutricional.",
            "mainContent": "Macronutrientes — ou \"macros\" — são as três categorias de nutrientes que seu corpo precisa em grandes quantidades para funcionar adequadamente. Cada um desempenha um papel único e essencial, e o equilíbrio entre eles pode influenciar significativamente sua energia, satisfação e progresso na jornada de bem-estar.\nA proteína é o material de construção do seu corpo. Mantém e repara seus músculos, apoia seu sistema imunológico e cria as enzimas e hormônios que mantêm tudo funcionando. Para controle de peso, a proteína é particularmente valiosa porque tem o maior fator de saciedade dos três macros — mantém você se sentindo satisfeita por mais tempo que carboidratos ou gorduras. Também tem o maior efeito térmico, significando que seu corpo queima mais calorias digerindo proteína do que digerindo a mesma quantidade de carboidratos ou gordura. Buscar que a proteína represente cerca de 25-30% das suas calorias diárias é uma meta favorável para a maioria das pessoas em jornada de bem-estar.\nOs carboidratos são a fonte preferida de energia do seu corpo, particularmente para o cérebro e durante atividade física. Ganharam uma reputação injusta nos últimos anos, mas a verdade é que seu corpo precisa de carboidratos — a chave é escolher os tipos certos. Carboidratos complexos como vegetais, grãos integrais, leguminosas e frutas vêm embalados com fibra, vitaminas e minerais. Fornecem energia sustentada sem picos dramáticos de açúcar no sangue. Uma faixa de 40-50% das calorias desses carboidratos de qualidade apoia tanto energia quanto bem-estar.\nGorduras saudáveis são essenciais para produção de hormônios, função cerebral, absorção de nutrientes (vitaminas A, D, E e K todas precisam de gordura para serem absorvidas) e saúde celular. Também contribuem para saciedade e fazem a comida ter um sabor delicioso. Abacate, azeite, castanhas, sementes e peixes gordurosos são fontes lindas. Buscar 25-30% das calorias dessas gorduras nutritivas apoia tanto seu corpo quanto seu prazer com a comida.\nEm vez de se obsesionar com porcentagens exatas, foque em incluir os três macronutrientes em cada refeição. Um prato com uma porção do tamanho da palma de proteína, uma porção generosa de vegetais (carboidratos complexos), uma porção modesta de grãos integrais ou vegetais amiláceos, e uma porção do tamanho do polegar de gordura saudável é uma refeição lindamente equilibrada que apoia energia, satisfação e objetivos de bem-estar.",
            "keyTakeaways": [
                "Proteína (25-30% das calorias) apoia músculos, saciedade e tem o maior efeito térmico",
                "Carboidratos complexos (40-50%) fornecem energia sustentada e nutrientes essenciais",
                "Gorduras saudáveis (25-30%) apoiam hormônios, função cerebral e absorção de nutrientes",
                "Inclua os três macronutrientes em cada refeição para equilíbrio e satisfação",
                "Foque em fontes de qualidade em vez de se obsesionar com números exatos"
            ],
            "actionStep": "Olhe para sua próxima refeição e identifique a proteína, carboidratos e gorduras no seu prato. Está faltando algum? Algum está dominando? Ajuste para criar um prato mais equilibrado e observe como se sente nas horas seguintes.",
            "journalPrimary": "Qual macronutriente você tende a comer mais, e qual tende a negligenciar? Como reequilibrar seu prato poderia mudar sua energia e satisfação ao longo do dia?"
        },
        52: {
            "introduction": "Com pouco tempo mas quer que seu movimento conte? Hoje vamos explorar o Treino Intervalado de Alta Intensidade — um estilo de exercício que pode entregar resultados impressionantes em surpreendentemente pouco tempo. Se você já sentiu que precisa de horas na academia para fazer diferença, essa lição vai mudar sua perspectiva da forma mais empolgante!",
            "mainContent": "O Treino Intervalado de Alta Intensidade, ou HIIT, é um estilo de exercício que alterna entre explosões curtas de esforço intenso e períodos breves de descanso ou movimento de menor intensidade. Uma sessão típica de HIIT pode envolver 30 segundos de esforço total seguidos de 30-60 segundos de recuperação, repetidos por 20-30 minutos no total. É eficiente, eficaz e — uma vez que pega o jeito — genuinamente empolgante.\nO que torna o HIIT especial é o que acontece *depois* do treino. Durante cardio tradicional em ritmo constante, você queima calorias enquanto exercita, mas a queima para em grande parte quando você para. O HIIT, por outro lado, cria o que se chama \"efeito afterburn\" (cientificamente conhecido como consumo excessivo de oxigênio pós-exercício, ou EPOC). Após uma sessão de HIIT, seu corpo continua queimando calorias em taxa elevada por horas — às vezes até 24-48 horas — enquanto se recupera e restaura ao estado basal. Isso significa que um treino HIIT de 20 minutos pode, no final, queimar tantas calorias quanto um treino tradicional muito mais longo.\nO HIIT também é notavelmente acessível. Não precisa de equipamento — exercícios com peso corporal como polichinelos, burpees, corrida no lugar com joelhos altos, alpinista e agachamentos funcionam perfeitamente. Pode fazer HIIT na sala de estar, no parque ou num quarto de hotel. E como as sessões são curtas, é muito mais fácil encaixar numa agenda ocupada que uma sessão de 60 minutos na academia.\nDito isso, HIIT é intenso por natureza, e é importante abordá-lo com respeito pelo seu corpo. Se está apenas começando sua prática de movimento, comece com intervalos de menor intensidade e períodos de descanso mais longos. Pode começar com 20 segundos de esforço e 40 segundos de descanso, aumentando gradualmente a intensidade conforme seu condicionamento melhora. Sempre aqueça por 5 minutos antes e desaqueça por 5 minutos depois. E por causa da intensidade, limite o HIIT a 2-3 sessões por semana, permitindo dias de recuperação entre elas.\nOuça seu corpo o tempo todo. A \"alta intensidade\" deve ser relativa ao *seu* nível de condicionamento — não ao de outra pessoa. Seu melhor esforço pessoal é sempre suficiente.",
            "keyTakeaways": [
                "O HIIT alterna esforço intenso com períodos de descanso para máxima eficiência",
                "O \"efeito afterburn\" continua queimando calorias por horas após o treino",
                "As sessões podem ter apenas 20 minutos e não exigem equipamento",
                "Comece com menor intensidade e períodos de descanso mais longos se for iniciante",
                "Limite o HIIT a 2-3 sessões por semana para permitir recuperação adequada"
            ],
            "actionStep": "Experimente um treino HIIT simples para iniciantes: 30 segundos de polichinelos, 30 segundos de descanso, repetido 8 vezes (apenas 8 minutos no total!). Se polichinelos forem intensos demais, substitua por marcha no lugar com joelhos altos. Observe como se sente durante e depois.",
            "journalPrimary": "Como se sente sobre exercícios de alta intensidade? A ideia de treinos mais curtos e intensos te atrai, ou parece intimidante? O que tornaria isso mais acessível?"
        },
        53: {
            "introduction": "Todas nós experimentamos desejos — aqueles desejos intensos, aparentemente urgentes, por alimentos específicos que podem parecer quase impossíveis de resistir. Hoje vamos te equipar com estratégias práticas e comprovadas para navegar os desejos com confiança e graça. Você é mais forte que qualquer desejo, e hoje vai ver exatamente por quê.",
            "mainContent": "Primeiro, vamos normalizar os desejos: são uma parte completamente natural de ser humana. Todo mundo os experimenta, e não te tornam fraca ou quebrada. Desejos são simplesmente seu corpo e cérebro enviando sinais — às vezes sobre necessidades físicas genuínas, e às vezes sobre padrões emocionais ou habituais. A chave é aprender a responder com atenção em vez de reagir automaticamente.\nUma das estratégias mais poderosas é o simples ato de esperar. A maioria dos desejos, mesmo os intensos, vai passar dentro de 15-20 minutos. Na próxima vez que um desejo bater, programe um timer e comprometa-se a esperar antes de agir. Durante esse tempo, faça uma caminhada, ligue para uma amiga, arrume um cômodo, ou faça qualquer atividade que mude seu foco. Frequentemente vai descobrir que, quando o timer apita, o desejo diminuiu significativamente ou desapareceu completamente.\nAqui vai um fato surpreendente: a sede é frequentemente confundida com fome e desejos. Os sinais de desidratação do seu corpo podem parecer notavelmente similares aos desejos por comida. Quando um desejo bater, beba um copo cheio de água primeiro e espere 10 minutos. Muitas pessoas descobrem que o que achavam ser um desejo por chips ou chocolate era na verdade seu corpo pedindo hidratação.\nDistração pode parecer simples demais para funcionar, mas é respaldada pela ciência. Desejos ocupam a mesma \"largura de banda\" mental que outras atividades envolventes. Quando redireciona sua atenção para algo que exige foco — uma conversa, um jogo, um projeto criativo, ou até uma caminhada rápida — você literalmente tira o desejo da sua memória de trabalho. O desejo perde poder quando dá ao cérebro algo mais para processar.\nFinalmente, ter uma alternativa pequena e saudável pronta pode ser salvação. Se deseja algo doce, alguns quadradinhos de chocolate amargo ou frutas vermelhas frescas podem satisfazer sem atrapalhar seus objetivos. Se sal é o que procura, um punhado de castanhas levemente salgadas ou pipoca estourada no ar pode acertar. O objetivo não é aguentar firme na privação — é encontrar alternativas satisfatórias que funcionem tanto para suas papilas quanto para seu corpo.",
            "keyTakeaways": [
                "A maioria dos desejos passa dentro de 15-20 minutos se esperar",
                "Beba água primeiro — a sede é frequentemente confundida com desejos",
                "Atividades envolventes redirecionam a atenção do cérebro para longe dos desejos",
                "Ter alternativas saudáveis prontas previne escolhas impulsivas",
                "Desejos são naturais e não refletem fraqueza ou fracasso"
            ],
            "actionStep": "Na próxima vez que um desejo bater hoje, experimente a abordagem esperar-e-beber-água: beba um copo cheio de água, programe um timer de 15 minutos e se envolva em uma atividade de distração. Depois que o timer tocar, avalie honestamente se ainda quer o alimento. Escreva sobre a experiência.",
            "journalPrimary": "Que alimentos você deseja com mais frequência, e quando esses desejos costumam bater? Há um padrão — um horário do dia, uma emoção, ou uma situação — que consistentemente os dispara?"
        },
        54: {
            "introduction": "Comer os mesmos alimentos dia após dia pode parecer seguro e simples, mas pode estar te segurando silenciosamente. Hoje vamos celebrar a beleza da variedade — não apenas para suas papilas, mas para a capacidade do seu corpo de obter todos os nutrientes que precisa. Expandir seu prato é uma aventura, e estou animada para te inspirar a explorar!",
            "mainContent": "Seu corpo precisa de dezenas de vitaminas, minerais e fitonutrientes diferentes para funcionar no seu melhor, e nenhum alimento único fornece todos. Comer uma ampla variedade de alimentos é a forma mais simples de garantir que está cobrindo todas as suas bases nutricionais. Pense como construir uma casa — você precisa de muitos materiais diferentes, não apenas tijolos.\nUma das formas mais fáceis e bonitas de aumentar a variedade é \"comer o arco-íris\". Frutas e vegetais de cores diferentes contêm compostos benéficos diferentes. Alimentos vermelhos como tomates e melancia são ricos em licopeno. Alimentos laranja como batata-doce e cenoura fornecem betacaroteno. Vegetais verdes são carregados de folato e vitamina K. Alimentos roxos e azuis como mirtilo e berinjela contêm poderosas antocianinas. Ao buscar tantas cores diferentes no prato cada dia quanto possível, está naturalmente diversificando sua ingestão de nutrientes.\nAlternar suas fontes de proteína ao longo da semana é outra estratégia importante. Se come frango todos os dias, vai obter os nutrientes que o frango fornece mas perder o que outras proteínas oferecem. Peixe fornece ácidos graxos ômega-3. Feijões e lentilhas oferecem fibras e minerais únicos. Ovos fornecem colina. Carne bovina é rica em ferro e B12. Ao alternar entre fontes diferentes, cria um perfil nutricional mais completo.\nAqui vai um desafio divertido: experimente um alimento saudável novo a cada semana. Visite a seção de hortifrutigranjeiros do mercado e pegue algo que nunca cozinhou — talvez jicama, bok choy, farro ou beterraba dourada. Procure uma receita simples online e experimente. Nem todo experimento se tornará favorito, mas pode descobrir alimentos que ama absolutamente e que nunca teria experimentado de outra forma.\nA variedade também previne o tédio do paladar, que é uma das principais razões pelas quais as pessoas abandonam a alimentação saudável e voltam para alimentos processados convenientes. Quando está empolgada com suas refeições, comer bem deixa de parecer uma obrigação e começa a parecer um prazer.",
            "keyTakeaways": [
                "Alimentos de cores diferentes fornecem nutrientes essenciais diferentes — coma o arco-íris",
                "Alternar fontes de proteína garante um perfil nutricional mais completo",
                "Experimentar um alimento novo por semana expande suas opções e previne tédio",
                "Variedade torna a alimentação saudável mais prazerosa e sustentável",
                "Nenhum alimento único fornece tudo que seu corpo precisa"
            ],
            "actionStep": "Olhe para o que está planejando comer hoje e identifique uma forma de adicionar variedade. Poderia trocar sua proteína usual por uma diferente? Adicionar um vegetal que não comeu esta semana? Experimentar uma fruta nova? Faça uma troca colorida hoje.",
            "journalPrimary": "Quão variada é sua dieta atual? Tende a comer os mesmos alimentos repetidamente? Qual é um alimento que está curiosa para experimentar, e o que te impediu de experimentar?"
        },
        55: {
            "introduction": "Ah, fins de semana — aqueles dias gloriosos de relaxamento e liberdade que também podem se tornar o lugar onde o progresso da semana silenciosamente se desfaz. Hoje vamos aprender a curtir seus fins de semana plenamente enquanto mantém sua jornada de bem-estar avançando. Porque você merece se divertir *e* se sentir bem na segunda de manhã!",
            "mainContent": "Aqui está um padrão que muitas pessoas reconhecem: você come bem e se mantém ativa de segunda a sexta, depois o fim de semana chega e de repente a estrutura se dissolve. Eventos sociais, brunch, delivery, dormir demais e perder o treino, e aquele pensamento sedutor: \"Começo de novo na segunda\". Ao longo de um mês, esse padrão pode apagar completamente o progresso da semana. Dois dias de alimentação desestruturada por semana representam quase 30% do seu tempo total de alimentação — isso é significativo.\nA boa notícia é que gerenciar os fins de semana não significa transformá-los em extensões da rotina de trabalho. Significa ser intencional em vez de reativa. Planejar com antecedência para eventos sociais é um ótimo primeiro passo. Se sabe que vai a um jantar no sábado à noite, planeje refeições mais leves mas equilibradas mais cedo no dia. Se o brunch de domingo é tradição, curta — mas talvez pule os drinks infinitos ou escolha ovos e vegetais em vez da torre tripla de panquecas.\nUma das mudanças de mentalidade mais saudáveis que pode fazer é sair dos \"dias de lixo\" para \"pequenos prazeres\". Um dia de lixo implica que sua alimentação saudável é uma forma de restrição da qual precisa escapar, e frequentemente leva a consumir milhares de calorias extras em um único dia. Em vez disso, permita-se pequenos prazeres ao longo do fim de semana — uma bola de sorvete, um copo de vinho, um pedaço de pão no jantar. Curta plenamente, sem culpa, e sem deixar virar uma liberação geral de comida o dia todo.\nManter sua rotina de movimento nos fins de semana é talvez o hábito mais impactante de todos. Não precisa parecer igual à rotina da semana — talvez seja uma trilha em família em vez da academia, um passeio de bicicleta em vez de um vídeo de treino, ou uma caminhada tranquila na feira. O ponto é manter seu corpo se movendo e manter o momentum da identidade saudável que está construindo.\nMais importante, elimine a frase \"Começo de novo na segunda\" do seu vocabulário. Essa frase te dá permissão para abandonar seus objetivos por dois dias inteiros e cria uma relação prejudicial de liga-desliga com sua jornada de bem-estar. Em vez disso, cada refeição é um novo começo. Teve um brunch pesado? Sua próxima refeição pode ser uma lindamente equilibrada. Sem necessidade de esperar até segunda.",
            "keyTakeaways": [
                "A alimentação do fim de semana representa quase 30% da semana — importa",
                "Planeje com antecedência para eventos sociais em vez de ir sem estratégia",
                "Escolha pequenos prazeres conscientes em vez de \"dias de lixo\" completos",
                "Continue se movendo nos fins de semana, mesmo que a atividade pareça diferente",
                "Cada refeição é um novo começo — nunca espere até segunda"
            ],
            "actionStep": "Olhe para seu próximo fim de semana. Identifique um evento social ou tempo livre que tipicamente leva a escolhas que se arrepende. Faça um plano específico de como vai navegar — o que vai comer antes, o que vai escolher, e como vai movimentar o corpo naquele dia.",
            "journalPrimary": "O que tipicamente acontece com seus padrões de alimentação e movimento nos fins de semana? Como seria curtir seus fins de semana plenamente enquanto ainda honra seus objetivos de bem-estar?"
        },
        56: {
            "introduction": "Dizem que é preciso uma vila, e sua jornada de bem-estar não é exceção. Hoje vamos explorar o poder incrível de ter alguém ao seu lado — um parceiro de responsabilidade que compartilha seus objetivos, celebra suas vitórias e te levanta quando as coisas ficam difíceis. Essa única relação pode fazer uma diferença notável no seu sucesso.",
            "mainContent": "Pesquisas mostram consistentemente que pessoas com parceiros de responsabilidade são significativamente mais propensas a alcançar seus objetivos. Um estudo descobriu que simplesmente contar a alguém sobre seu objetivo aumenta sua probabilidade de sucesso em 65%, e ter check-ins regulares com essa pessoa aumenta para 95%. Há algo poderoso em saber que alguém está torcendo por você e esperando que você apareça.\nUm parceiro de responsabilidade não precisa ser alguém na mesma jornada que você. Só precisa ser alguém em quem confia, que apoia seus objetivos e com quem pode ser honesta. Pode ser uma amiga, familiar, colega, ou até alguém que conhece online. O que importa é a qualidade da conexão e o compromisso de aparecer uma pela outra.\nCompartilhar seus objetivos e progresso regularmente é a base da responsabilidade. Isso pode parecer um check-in semanal por mensagem, um dia compartilhado de preparo de refeições, ou uma ligação fixa no domingo à noite para planejar a semana. Algumas pessoas compartilham diários alimentares ou contagem de passos. Outras simplesmente enviam um emoji de joinha quando completam seu movimento diário. Encontre um ritmo e formato que funcione para ambas.\nSe exercitar juntas, quando possível, leva a responsabilidade a outro nível. É muito mais difícil pular a caminhada matinal quando sabe que sua amiga já está lá fora esperando. Movimento conjunto não precisa ser intenso — caminhar juntas, seguir o mesmo treino online, ou até alongar durante uma videochamada, tudo conta. A experiência compartilhada torna o movimento mais prazeroso e consistente.\nCelebrar as vitórias uma da outra — não importa quão pequenas — é tão importante quanto fornecer apoio durante contratempos. Sua parceira bebeu água suficiente a semana toda? Celebre. Ela escolheu vegetais no restaurante? Reconheça. Essas celebrações reforçam comportamentos positivos e constroem o tipo de associação positiva com escolhas saudáveis que as fazem durar. E quando contratempos acontecem (porque vão), encorajamento gentil em vez de julgamento mantém ambas avançando.",
            "keyTakeaways": [
                "Ter um parceiro de responsabilidade aumenta o alcance de objetivos em até 95%",
                "Escolha alguém em quem confia, que apoia seus objetivos e com quem pode ser honesta",
                "Check-ins regulares — mesmo mensagens simples — mantêm a conexão e o compromisso",
                "Se exercitar juntas aumenta consistência e prazer",
                "Celebre vitórias e ofereça encorajamento gentil durante contratempos"
            ],
            "actionStep": "Pense em uma pessoa na sua vida que poderia ser uma boa parceira de responsabilidade. Entre em contato hoje — compartilhe no que está trabalhando e pergunte se estaria disposta a fazer check-ins semanais com você. Se ninguém vier à mente, procure comunidades online de bem-estar onde possa encontrar uma parceira.",
            "journalPrimary": "Quem na sua vida apoia seus objetivos de bem-estar? Que tipo de responsabilidade seria mais útil — check-ins diários, ligações semanais, treinos compartilhados? O que tem te impedido de pedir apoio?"
        },
        57: {
            "introduction": "Yoga pode não parecer a escolha mais óbvia para controle de peso, mas hoje vou te mostrar por que é uma das ferramentas mais poderosas do seu kit de bem-estar. Yoga é onde movimento suave encontra redução de estresse, onde força física encontra paz interior. É uma prática que nutre seu corpo e alma simultaneamente.",
            "mainContent": "Quando as pessoas pensam em controle de peso através do movimento, frequentemente imaginam cardio intenso ou pesos pesados. Yoga às vezes é descartado como \"só alongamento\". Mas essa prática linda oferece uma combinação única de benefícios que apoiam diretamente seus objetivos de bem-estar de formas que outras formas de movimento simplesmente não conseguem.\nPrimeiro, yoga constrói músculo magro e melhora a flexibilidade. Manter as poses requer força significativa — suportar o próprio peso corporal através de guerreiros, pranchas e poses de equilíbrio constrói e tonifica músculos por todo o corpo. E tecido muscular magro queima mais calorias em repouso que tecido adiposo, então construir músculo através do yoga na verdade aumenta sua taxa metabólica mesmo quando não está praticando.\nMas o verdadeiro superpoder do yoga para controle de peso pode ser seu impacto no estresse. Você aprendeu como o estresse crônico eleva o cortisol, que promove armazenamento de gordura e impulsiona alimentação emocional. Yoga é uma das práticas de redução de estresse mais eficazes disponíveis, consistentemente demonstrando reduzir os níveis de cortisol. A respiração, meditação e movimento consciente que são entrelaçados na prática de yoga ativam seu sistema nervoso parassimpático, mudando seu corpo de \"luta ou fuga\" para modo \"descansar e digerir\". Essa mudança hormonal cria as condições internas para seu corpo liberar excesso de peso naturalmente.\nYoga também cultiva algo chamado interocepção — a capacidade de sentir e compreender os sinais internos do corpo. Praticantes regulares se tornam mais sintonizadas com sinais de fome e saciedade, estados emocionais e necessidades físicas. Essa consciência corporal elevada naturalmente apoia alimentação consciente e melhores decisões de autocuidado ao longo do dia.\nSe queima calórica é importante para você, certos estilos de yoga entregam benefícios cardiovasculares significativos. Vinyasa (flow) yoga conecta respiração com movimento contínuo, mantendo a frequência cardíaca elevada. Power yoga é uma abordagem vigorosa baseada em fitness que pode queimar 300-500 calorias por hora. Hot yoga (praticado em salas aquecidas) adiciona um elemento de intensidade adicional. Mas mesmo estilos suaves como Hatha ou Yin yoga fornecem os benefícios de redução de estresse e consciência corporal que apoiam sua jornada.\nVocê não precisa de estúdio ou equipamento caro para começar. Um tapete simples e um dos muitos vídeos gratuitos de yoga disponíveis online são suficientes. Comece com aulas para iniciantes e se dê total permissão para modificar qualquer pose. Yoga é uma prática pessoal — não há competição e não há jeito errado de fazer.",
            "keyTakeaways": [
                "Yoga constrói músculo magro, aumentando sua taxa metabólica em repouso",
                "É uma das práticas mais eficazes para reduzir cortisol e estresse",
                "A prática regular melhora a consciência corporal e conexão com sinais de fome/saciedade",
                "Estilos vigorosos como Vinyasa e Power yoga podem queimar 300-500 calorias por hora",
                "Tudo que precisa é um tapete e acesso à internet para começar"
            ],
            "actionStep": "Encontre um vídeo gratuito de yoga para iniciantes online (10-20 minutos é perfeito) e experimente hoje. Foque em como a prática te faz sentir em vez de como parece. Observe qualquer mudança no seu nível de estresse, consciência corporal ou humor depois.",
            "journalPrimary": "Qual tem sido sua experiência com yoga, se alguma? O que te atrai na ideia de combinar movimento físico com redução de estresse e mindfulness? O que poderia te impedir de experimentar?"
        },
        58: {
            "introduction": "Já subiu na balança e viu um salto repentino de um ou dois quilos da noite para o dia? Antes de entrar em pânico, há uma chance muito boa de que o sódio seja o culpado. Hoje vamos desmistificar o sódio e a retenção de líquidos, para que entenda o que realmente está acontecendo no seu corpo e pare de deixar flutuações temporárias abalarem sua confiança.",
            "mainContent": "O sódio — comumente consumido como sal de cozinha — é um mineral essencial que seu corpo precisa para função nervosa, contração muscular e equilíbrio de fluidos. O problema não é o sódio em si; é que a maioria de nós consome muito mais do que nosso corpo precisa. O limite diário recomendado é menos de 2.300 mg, mas a pessoa média consome mais de 3.400 mg diariamente, muito disso de fontes que nem percebemos.\nQuando consome sódio em excesso, seu corpo responde retendo água extra para manter a concentração certa de sódio no sangue. Essa retenção de líquidos pode causar ganho de peso temporário de 1-2 quilos, inchaço, puffiness (especialmente nas mãos, pés e rosto) e uma sensação geral desconfortável e pesada. É importante entender que isso é peso de *água*, não ganho de gordura. É temporário e se resolve quando a ingestão de sódio normaliza.\nA maior fonte de excesso de sódio não é o saleiro na sua mesa — são alimentos processados e embalados. Sopas enlatadas, refeições congeladas, frios, queijos, condimentos, pão e comida de restaurante podem conter quantidades impressionantes de sódio. Uma única refeição de fast-food pode facilmente conter toda a sua cota diária. Ler rótulos nutricionais e estar consciente do teor de sódio nas suas escolhas alimentares é uma das coisas mais práticas que pode fazer.\nAlimentos ricos em potássio podem ajudar a contrabalançar os efeitos do sódio. O potássio trabalha junto com o sódio para manter o equilíbrio de fluidos, e comer mais potássio ajuda seu corpo a liberar excesso de sódio pela urina. Bananas, batatas, espinafre, abacate, feijão e iogurte são todos fontes excelentes. Pense no potássio como o parceiro equilibrador do sódio.\nContra-intuitivamente, beber *mais* água ajuda a reduzir a retenção de líquidos, não menos. Quando está bem hidratada, seu corpo se sente confiante liberando excesso de fluidos porque sabe que mais está vindo. Quando está desidratada, seu corpo retém água com mais força como mecanismo de proteção. Busque pelo menos 8 copos de água por dia, e ainda mais quando teve um dia com mais sódio.",
            "keyTakeaways": [
                "Excesso de sódio causa retenção temporária de líquidos — não ganho de gordura",
                "A maioria do excesso de sódio vem de alimentos processados, não do saleiro",
                "Busque menos de 2.300 mg de sódio por dia e leia rótulos com atenção",
                "Alimentos ricos em potássio ajudam a equilibrar o sódio e reduzir retenção de líquidos",
                "Beber mais água realmente ajuda seu corpo a liberar excesso de fluidos"
            ],
            "actionStep": "Verifique o teor de sódio de três alimentos embalados ou processados na sua cozinha. Pode se surpreender com quão rápido se acumula. Identifique um item alto em sódio que poderia trocar por uma alternativa mais baixa em sódio esta semana.",
            "journalPrimary": "Como reage quando a balança mostra um aumento repentino? Sabendo sobre retenção de líquidos e sódio, como poderia responder diferente da próxima vez? Como seria confiar mais no processo do que no número?"
        },
        59: {
            "introduction": "Sucos detox, chás desintoxicantes, jejuns de 3 dias que prometem \"eliminar toxinas\" — a indústria de detox é um negócio bilionário construído sobre medo e falsas promessas. Hoje vamos separar fato de ficção, empoderando você com a verdade sobre como seu corpo realmente se desintoxica, e mostrando como apoiar esse processo natural incrível.",
            "mainContent": "Vamos começar com a verdade maravilhosa: seu corpo já é uma potência de desintoxicação. Seu fígado, rins, pulmões, pele e sistema digestivo trabalham 24 horas por dia para filtrar, neutralizar e eliminar substâncias nocivas. Esses órgãos evoluíram ao longo de milhões de anos para fazer esse trabalho brilhantemente, e nenhum produto comercial pode fazê-lo melhor do que eles.\nA maioria dos programas comerciais de \"detox\" não tem respaldo científico para suas alegações. Sucos detox, chás desintoxicantes, suplementos de carvão ativado e protocolos de jejum extremo não \"limpam seu sistema\" de nenhuma forma significativa. Muitos deles simplesmente causam perda rápida de água e músculo, que aparece como perda de peso na balança mas não representa perda real de gordura. Quando você volta a comer normalmente, o peso volta — frequentemente com juros, porque perdeu tecido muscular metabolicamente ativo no processo.\nAlguns produtos detox podem realmente ser prejudiciais. Certos chás detox contêm senna, um laxante poderoso que pode causar desidratação, desequilíbrios de eletrólitos e dependência. Sucos detox extremos podem elevar o açúcar no sangue (todo aquele suco de fruta sem fibra), privar seu corpo de proteínas e gorduras essenciais, e deixá-la fraca, irritável e intensamente faminta. Ironicamente, podem estressar os mesmos órgãos que alegam ajudar.\nA forma verdadeiramente eficaz de apoiar a desintoxicação natural do seu corpo é simples e gratuita: mantenha-se bem hidratada (água é a melhor amiga do seu fígado), coma bastante fibra (que ajuda o sistema digestivo a remover resíduos eficientemente), durma com qualidade (seu cérebro realmente elimina resíduos metabólicos durante o sono profundo), movimente-se regularmente (apoiando circulação e drenagem linfática), e minimize a ingestão das coisas que sobrecarregam seus órgãos de desintoxicação — álcool em excesso, alimentos altamente processados e medicamentos desnecessários.\nEm vez de uma limpeza dramática e de curto prazo, foque em criar um estilo de vida que consistentemente apoie o sistema de desintoxicação embutido do seu corpo. Esse é o tipo de \"detox\" que realmente funciona — e não custa um centavo.",
            "keyTakeaways": [
                "Seu fígado, rins e outros órgãos já desintoxicam seu corpo naturalmente",
                "A maioria dos produtos detox comerciais não tem respaldo científico",
                "Limpezas extremas frequentemente causam perda de água e músculo, não de gordura",
                "Alguns produtos detox podem ser realmente prejudiciais",
                "Apoiar a desintoxicação natural é gratuito: hidratação, fibra, sono, movimento, alimentos integrais"
            ],
            "actionStep": "Em vez de um \"detox\", dê ao sistema de desintoxicação natural do seu corpo um apoio extra hoje: beba um copo ou dois extras de água, coma uma porção extra de vegetais ricos em fibra, e busque sono de qualidade esta noite. Essa é a verdadeira limpeza.",
            "journalPrimary": "Você já tentou uma dieta detox ou limpeza? Como foi sua experiência? Como se sente sabendo que seu corpo já é incrivelmente capaz de se limpar quando devidamente apoiado?"
        },
        60: {
            "introduction": "Hoje é dia de celebração, e estou tão orgulhosa de você! Chegamos ao Dia 60, o que significa que você está nessa jornada há dois meses inteiros. Hoje vamos dar um passo para trás da balança e reconhecer todas as formas lindas como você já mudou — porque progresso é muito maior que um número. Vamos honrar cada vitória, grande e pequena.",
            "mainContent": "A balança mede uma coisa: sua relação com a gravidade em um único ponto no tempo. Ela não mede sua saúde, seu valor, seu progresso ou a transformação incrível acontecendo dentro do seu corpo e mente. Se tem focado apenas no número, está perdendo um quadro muito maior e mais bonito.\nVitórias além da balança são as mudanças que a balança não consegue captar mas que genuinamente transformam sua qualidade de vida. Mais energia pode ser uma das primeiras coisas que percebeu — talvez esteja passando a tarde sem aquela necessidade desesperada de cafeína ou açúcar. Talvez esteja dormindo melhor, adormecendo mais facilmente e acordando mais descansada. Essas não são coisas pequenas — é seu corpo respondendo ao cuidado que tem dado a ele.\nComo suas roupas estão? Percebeu calças cabendo mais confortavelmente, uma blusa um pouco mais solta, ou uma roupa favorita que pode vestir com mais confiança? Mudanças de composição corporal — perder gordura enquanto potencialmente ganha músculo magro — podem estar acontecendo mesmo quando a balança não se move. Na verdade, essa é uma das melhores coisas que podem acontecer, porque significa que seu metabolismo está se tornando mais eficiente.\nSeu humor e bem-estar emocional também são marcadores poderosos de progresso. Talvez esteja lidando com o estresse com mais graça, se sentindo mais confiante em situações sociais, ou percebendo um diálogo interno mais positivo. Talvez esteja experimentando menos desejos, comendo com mais atenção, ou sentindo orgulho quando escolhe nutrição em vez de conveniência. Essas mudanças de mentalidade são a base de mudanças duradouras.\nE não ignore os marcadores de saúde. Se visitou seu profissional de saúde recentemente, pode ter visto melhorias na pressão arterial, níveis de açúcar no sangue, colesterol ou outras medidas. Essas são vitórias profundas e transformadoras que a balança do banheiro não sabe nada sobre.\nTire um momento agora para reconhecer o quanto já caminhou. Você apareceu. Você continuou. Você aprendeu, adaptou e cresceu. Isso merece ser celebrado — não com comida, mas com reconhecimento genuíno e sincero da pessoa incrível que está se tornando.",
            "keyTakeaways": [
                "A balança mede apenas sua relação com a gravidade — não sua saúde ou progresso",
                "Mais energia, sono melhor e humor melhorado são vitórias poderosas",
                "A composição corporal pode mudar significativamente mesmo quando a balança não se move",
                "Marcadores de saúde como pressão arterial e açúcar no sangue são mais significativos que peso",
                "Você merece celebrar cada mudança positiva, não importa quão pequena"
            ],
            "actionStep": "Escreva pelo menos cinco vitórias além da balança que experimentou desde o início dessa jornada. Coloque onde vai vê-las diariamente — no espelho, na geladeira, ou como nota no celular. Leia quando precisar de um lembrete de quanto já caminhou.",
            "journalPrimary": "Além do número na balança, como sua vida mudou nos últimos dois meses? Que melhorias em energia, humor, sono, confiança ou saúde você percebeu? De qual vitória tem mais orgulho?"
        },
    }

def apply_translations(data, translations):
    count = 0
    for lesson in data['lessons']:
        day = lesson['dayNumber']
        if day in translations:
            t = translations[day]
            lesson['content']['introduction'] = t['introduction']
            lesson['content']['mainContent'] = t['mainContent']
            lesson['content']['keyTakeaways'] = t['keyTakeaways']
            lesson['content']['actionStep'] = t['actionStep']
            lesson['journalPrompt']['primary'] = t['journalPrimary']
            count += 1
    return count

if __name__ == '__main__':
    filepath = 'src/i18n/locales/pt/lessons.json'
    with open(filepath, 'r') as f:
        data = json.load(f)
    translations = get_translations()
    count = apply_translations(data, translations)
    with open(filepath, 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Applied {count} translations (Days 41-60)")
