#!/usr/bin/env python3
"""Apply Brazilian Portuguese translations for days 61-80."""
import json

def get_translations():
    return {
        61: {
            "introduction": "Hoje vamos brincar de detetive, e o caso é importante: açúcares ocultos em alimentos que se vendem como saudáveis. Você pode se surpreender ao descobrir que alguns itens \"saudáveis\" na sua despensa contêm mais açúcar do que jamais imaginaria. Conhecimento é proteção, e hoje vamos te armar com os dois.",
            "mainContent": "Um dos obstáculos mais frustrantes na jornada de bem-estar é fazer tudo \"certo\" e ainda se sentir empacada. Muitas vezes, o culpado são açúcares ocultos escondidos em alimentos que você genuinamente acredita serem escolhas saudáveis. A indústria alimentícia é incrivelmente hábil em vender produtos como nutritivos enquanto silenciosamente os enche de açúcares adicionados.\nA granola é uma das maiores vilãs. Aquele pacote bonito com fotos de aveia, castanhas e frutas vermelhas na frente? Confira o rótulo — muitas granolas contêm 12-16 gramas de açúcar por porção, algumas tanto quanto uma barra de chocolate. Iogurtes com sabor são outra surpresa. Um único pote de iogurte com sabor de fruta pode conter 20-25 gramas de açúcar. Até barras de proteína, vendidas como combustível fitness, frequentemente contêm tanto açúcar quanto uma sobremesa. Molhos de salada, molhos de tomate e \"smoothies saudáveis\" completam os suspeitos de sempre.\nProdutos rotulados como \"light\" ou \"baixo teor de gordura\" merecem atenção especial. Quando fabricantes removem gordura dos alimentos, frequentemente compensam adicionando açúcar para manter sabor e textura. Então aquela opção \"light\" que escolheu pensando ser mais saudável pode conter significativamente mais açúcar que a versão regular. Da mesma forma, rótulos \"orgânico\" e \"natural\" dizem sobre como os ingredientes foram obtidos, não sobre o teor de açúcar. Açúcar de cana orgânico ainda é açúcar.\nCalorias líquidas de sucos e smoothies são particularmente problemáticas porque contornam a mastigação e fibra que normalmente retardam a absorção do açúcar. Um copo de suco de laranja pode conter tanto açúcar quanto um refrigerante, sem a fibra que retardaria o impacto no açúcar no sangue. Quando você bebe açúcar em vez de comê-lo em alimentos integrais, o pico de açúcar é mais rápido e a queda mais forte.\nA solução empoderadora é simples: escolha versões sem sabor dos alimentos e adicione seus próprios temperos. Compre iogurte natural e adicione frutas vermelhas frescas e um fio de mel. Escolha aveia sem sabor e cubra com canela, castanhas e frutas. Selecione pastas de amendoim sem sabor. Quando você controla a doçura, usa muito menos que os fabricantes — e suas papilas gustativas se adaptam lindamente.\nPreste atenção em como se sente depois de comer alimentos com açúcares ocultos. Você tem uma queda uma hora depois? Seus desejos se intensificam? Essa autoconhecimento constrói uma bússola natural que te guia para escolhas que realmente apoiam sua energia e bem-estar.",
            "keyTakeaways": [
                "Muitos alimentos \"saudáveis\" como granola, iogurte com sabor e barras de proteína contêm quantidades surpreendentes de açúcar",
                "Rótulos \"light\", \"orgânico\" e \"natural\" não significam baixo em açúcar",
                "Açúcares líquidos em sucos e smoothies elevam o açúcar no sangue rapidamente sem fibra para retardar a absorção",
                "Escolher versões sem sabor e adicionar seus próprios ingredientes coloca você no controle",
                "Observe como açúcares ocultos afetam sua energia e desejos para autoconhecimento valioso"
            ],
            "actionStep": "Verifique o teor de açúcar de três alimentos \"saudáveis\" na sua cozinha — granola, iogurte, barras de proteína, molhos de salada ou molhos. Compare com a versão sem sabor ou sem açúcar. Pode se surpreender o suficiente para fazer uma troca esta semana.",
            "journalPrimary": "Você tem consumido alimentos que achava saudáveis mas que podem conter açúcares ocultos? Como se sente ao perceber isso — frustrada, empoderada, ou ambos? Qual troca te motiva a fazer?"
        },
        62: {
            "introduction": "Já passou por uma padaria e de repente sentiu fome, mesmo tendo comido há apenas uma hora? Ou se pegou buscando a caixa de doces na mesa de uma colega toda vez que passava? Hoje vamos explorar a fascinante psicologia dos gatilhos alimentares — os estímulos ambientais que influenciam seu comportamento alimentar sem você nem perceber. Consciência muda tudo.",
            "mainContent": "Seu comportamento alimentar é influenciado muito mais pelo ambiente do que imagina. Pesquisas em psicologia comportamental mostraram que estímulos visuais, proximidade, conveniência e até o tamanho dos seus pratos podem impactar significativamente quanto você come. A notícia empolgante é que, uma vez que entende esses gatilhos, pode remodelar seu ambiente para trabalhar *a favor* dos seus objetivos.\nO gatilho alimentar mais poderoso é a visibilidade. Estudos mostraram que quando balas são colocadas em um pote transparente na mesa, as pessoas comem 71% mais do que quando as mesmas balas estão em um pote opaco. Longe dos olhos, longe do coração. Aplique isso em casa removendo comida pouco saudável visível das bancadas e espaço de trabalho. Guarde alimentos menos favoráveis em recipientes opacos em armários difíceis de alcançar, e coloque tigelas de frutas e vegetais onde vai vê-los primeiro.\nO tamanho dos pratos desempenha um papel sutil mas significativo. Pesquisas mostraram que as pessoas se servem 22% mais quando usam pratos e tigelas maiores. Usar pratos menores — 25 cm em vez de 30 cm — naturalmente reduz porções mantendo a satisfação psicológica de um \"prato cheio\". É uma troca simples que funciona sem esforço.\nComo organiza sua geladeira também importa. Guarde alimentos saudáveis na altura dos olhos — vegetais lavados, frutas frescas, iogurte e proteínas magras bem onde vai vê-los ao abrir a porta. Opções menos favoráveis devem ir em prateleiras mais baixas ou gavetas. Quando a escolha saudável é a primeira coisa que vê, se torna a mais fácil e natural.\nAté suas rotas diárias podem influenciar sua alimentação. Se passa por um estabelecimento de comida todos os dias e se pega parando \"só dessa vez\" (de novo), considere mudar sua rota. Não é sobre evitar toda tentação para sempre — é sobre ser estratégica enquanto constrói hábitos mais fortes.",
            "keyTakeaways": [
                "Comida visível é comida consumida significativamente mais — longe dos olhos, longe do coração",
                "Pratos menores naturalmente reduzem porções sem parecer restritivo",
                "Organize sua geladeira com opções saudáveis na altura dos olhos",
                "Seu ambiente físico molda suas escolhas alimentares mais que a força de vontade",
                "Redesenhar seu ambiente é mais eficaz que depender de disciplina"
            ],
            "actionStep": "Faça uma rápida \"auditoria do ambiente alimentar\" na sua cozinha e espaço de trabalho. Mova qualquer comida pouco saudável visível para fora da vista, coloque frutas ou vegetais em um lugar de destaque, e verifique que opções saudáveis estão na altura dos olhos na geladeira.",
            "journalPrimary": "Que estímulos alimentares ambientais você percebe no seu dia a dia? Existem lugares, recipientes ou arranjos que consistentemente te levam a escolhas menos favoráveis? Qual mudança poderia fazer no seu ambiente hoje?"
        },
        63: {
            "introduction": "Movimento não precisa ser intenso para ser incrivelmente eficaz. Hoje vamos celebrar o exercício de baixo impacto — formas gentis de movimento que apoiam seus objetivos de bem-estar sendo gentis com suas articulações. Seja iniciante, se recuperando de uma lesão, ou simplesmente preferindo uma abordagem mais suave, essas opções provam que cuidar do corpo pode ser muito, muito bom.",
            "mainContent": "Existe um mito no mundo fitness de que o exercício precisa doer ou deixar sem fôlego para \"contar\". Nada poderia estar mais longe da verdade. Exercício de baixo impacto — movimento onde pelo menos um pé fica no chão, ou onde suas articulações são amortecidas — oferece benefícios cardiovasculares genuínos, queima de calorias e construção de força sem o desgaste que atividades de alto impacto podem causar.\nNatação e hidroginástica são talvez os exercícios mais gentis para as articulações. A água suporta o peso do corpo, reduzindo o estresse nas articulações em até 90%, enquanto oferece resistência natural que constrói força. A flutuabilidade faz os movimentos parecerem mais fáceis enquanto seus músculos realmente trabalham duro. Nadar queima 400-700 calorias por hora dependendo da intensidade e estilo.\nCiclismo — ao ar livre ou em bicicleta ergométrica — oferece excelente treino cardiovascular com mínimo impacto articular. Como a bicicleta suporta seu peso, joelhos, quadris e tornozelos experimentam muito menos estresse do que durante a corrida. A bicicleta ergométrica permite exercitar independente do clima, e muitas pessoas gostam de combinar com assistir uma série ou ouvir um podcast.\nO elíptico imita o movimento da corrida sem o impacto. Seus pés nunca saem dos pedais, criando um movimento suave e deslizante que é gentil com as articulações enquanto eleva a frequência cardíaca e trabalha o corpo todo.\nExercícios na cadeira e treinos sentados merecem menção especial porque tornam o movimento acessível a praticamente todos. Marchas sentadas, elevações de braço, torções sentadas e extensões de perna oferecem benefícios genuínos. Tutoriais gratuitos estão amplamente disponíveis online.\nO mais importante é encontrar movimento que você goste e possa fazer consistentemente. O \"melhor\" exercício é aquele que você realmente vai fazer — dia após dia, semana após semana.",
            "keyTakeaways": [
                "Baixo impacto não significa baixa eficácia — esses exercícios genuinamente apoiam o controle de peso",
                "Natação reduz estresse articular em até 90% enquanto queima 400-700 calorias por hora",
                "Ciclismo e elíptico oferecem benefícios cardiovasculares sem impacto nas articulações",
                "Exercícios na cadeira tornam o movimento acessível a praticamente todos",
                "Consistência importa mais que intensidade — escolha movimento que você goste"
            ],
            "actionStep": "Experimente um exercício de baixo impacto hoje por pelo menos 15 minutos. Se tem acesso a uma piscina, vá nadar. Caso contrário, tente uma sessão gentil de bicicleta, uma caminhada, ou procure um vídeo gratuito de exercícios na cadeira online.",
            "journalPrimary": "Quais formas de movimento gentil mais te atraem? Tem evitado exercícios porque achava que tinha que ser intenso? Como abraçar opções de baixo impacto poderia mudar sua relação com o movimento?"
        },
        64: {
            "introduction": "O vinagre de maçã tem sido usado como remédio popular há séculos, e hoje vamos dar uma olhada honesta e equilibrada no que ele pode — e não pode — fazer pela sua jornada de bem-estar. Sem soluções mágicas aqui, apenas informações práticas sobre como esse simples item de despensa pode oferecer apoio genuíno quando usado com sabedoria.",
            "mainContent": "O vinagre de maçã (VM) ganhou enorme popularidade no mundo do bem-estar, com alegações que vão de milagre queimador de gordura a elixir para tudo. Vamos separar os benefícios baseados em evidências do exagero para que possa tomar decisões informadas.\nA evidência científica mais forte apoia a capacidade do VM de ajudar a reduzir picos de açúcar no sangue após as refeições. Vários estudos mostraram que consumir uma pequena quantidade de vinagre de maçã antes ou com uma refeição rica em carboidratos pode reduzir a resposta pós-refeição do açúcar no sangue em 20-30%. O ácido acético no vinagre parece retardar a digestão de amidos, permitindo que a glicose entre na corrente sanguínea mais gradualmente.\nTambém há evidências modestas de que o VM pode promover sensação de saciedade. Um estudo encontrou que participantes que consumiram vinagre com uma refeição comeram 200-275 calorias a menos no resto do dia. Esse efeito provavelmente se deve ao ácido acético retardar o esvaziamento estomacal.\nSe gostaria de experimentar, a abordagem recomendada é simples: dilua 1-2 colheres de sopa em um copo grande de água e beba 15-20 minutos antes das refeições. Nunca beba vinagre de maçã puro — a acidez pode danificar o esmalte dos dentes e irritar garganta e trato digestivo. Usar um canudo pode ajudar a proteger os dentes.\nPorém — e isso é importante — vinagre de maçã não é uma solução mágica. Não vai derreter gordura, \"desintoxicar\" seu corpo, ou substituir os fundamentos de alimentação equilibrada e movimento regular. Pense nele como uma ferramenta pequena e de apoio no seu kit de bem-estar maior, não como o kit em si.",
            "keyTakeaways": [
                "O VM pode reduzir picos de açúcar no sangue após as refeições em 20-30%",
                "Pode promover sensação de saciedade e reduzir modestamente a ingestão calórica",
                "Sempre dilua 1-2 colheres de sopa em água; nunca beba puro",
                "É uma ferramenta de apoio, não uma solução mágica — os fundamentos ainda importam mais",
                "Se não combina com você, pule — não está perdendo nada essencial"
            ],
            "actionStep": "Se está curiosa, experimente diluir uma colher de sopa de vinagre de maçã em um copo de água e beba 15 minutos antes da próxima refeição. Observe se percebe alguma diferença na saciedade ou como se sente depois de comer.",
            "journalPrimary": "Como se sente sobre remédios naturais e suplementos? É atraída por eles, cética, ou algo no meio? Qual é sua abordagem para incorporar novas ferramentas de bem-estar?"
        },
        65: {
            "introduction": "A cozinha chama mais alto depois que escurece, não é? Se comer à noite é algo com que você luta, saiba que está em boa companhia — é um dos desafios mais comuns na jornada de bem-estar. Hoje vamos explorar por que isso acontece e, mais importante, como gentilmente quebrar o padrão com compaixão e estratégias práticas.",
            "mainContent": "Comer à noite raramente é sobre fome física. No final do dia, a maioria das pessoas consumiu comida suficiente para atender às necessidades do corpo. Em vez disso, comer à noite é tipicamente impulsionado por uma combinação de hábito, tédio, descompressão do estresse e fadiga. Entender o que realmente te leva à cozinha depois do jantar é a chave para mudar o padrão.\nDepois de um dia longo, seus recursos mentais estão esgotados. A fadiga de decisão — a exaustão de fazer escolhas o dia todo — te deixa com menos força de vontade e mais vulnerável ao impulso. Some a isso o desejo de relaxar e se recompensar, e a comida se torna uma fonte rápida e fácil de conforto. Seu corpo não está com fome; sua alma está cansada.\nUma das estratégias mais eficazes é criar um ponto final claro para a alimentação cada dia. Algumas pessoas acham útil literalmente \"fechar a cozinha\" após o jantar — apagar a luz da cozinha, arrumar tudo e mentalmente declarar que a alimentação acabou por hoje. Isso cria um limite que, com o tempo, seu cérebro aceita e respeita.\nEscovar os dentes logo após o jantar é um truque surpreendentemente poderoso. Envia um sinal fisiológico e psicológico claro de que comer acabou. O sabor fresco e limpo na boca torna a comida menos atrativa, e o esforço de escovar novamente se comer funciona como um dissuasor gentil.\nAbordar a causa raiz é o que faz mudanças duradouras. Se tédio é seu gatilho, tenha uma atividade noturna pronta — um livro, artesanato, quebra-cabeça, caminhada ou ligação para uma amiga. Se estresse te leva à cozinha, experimente exercícios de respiração ou escrita. Se hábito é a questão, substituir o ritual de comida por um novo — uma xícara de chá, um banho quente, uma rotina de alongamento — pode satisfazer a necessidade de uma rotina noturna reconfortante.\nSe realmente precisa comer à noite, faça valer escolhendo opções ricas em proteína. Um ovo cozido, uma porção pequena de queijo cottage, ou algumas fatias de peru são muito mais favoráveis que os chips, biscoitos ou sorvete que os desejos noturnos normalmente pedem.",
            "keyTakeaways": [
                "Comer à noite é geralmente impulsionado por hábito, tédio, estresse ou fadiga — não fome",
                "Criar um limite claro de \"cozinha fechada\" ajuda seu cérebro a aceitar que comer acabou",
                "Escovar os dentes após o jantar envia um sinal poderoso de que a alimentação terminou",
                "Aborde a causa raiz: tédio precisa de atividade, estresse precisa de alívio, hábito precisa de substituição",
                "Se precisar comer, escolha opções ricas em proteína para menor impacto"
            ],
            "actionStep": "Esta noite, feche sua cozinha após o jantar — apague a luz, arrume tudo e escove os dentes. Se surgir vontade de beliscar, prepare uma xícara de chá e se envolva em uma atividade sem comida por 20 minutos. Veja se o desejo passa.",
            "journalPrimary": "Quando come à noite, o que geralmente motiva — fome genuína, tédio, estresse, hábito ou outra coisa? Que conforto sem comida poderia oferecer a si mesma nesses momentos?"
        },
        66: {
            "introduction": "Existe uma vitamina da qual muitas de nós somos silenciosamente deficientes, e ela tem um impacto maior na jornada de bem-estar do que imagina. Hoje vamos iluminar — literalmente — a vitamina D, a \"vitamina do sol\" que influencia metabolismo, humor, energia e muito mais. Vamos garantir que seu corpo está recebendo o que precisa.",
            "mainContent": "A vitamina D é única entre as vitaminas porque seu corpo pode produzi-la quando a pele é exposta à luz solar. Funciona mais como um hormônio do que uma vitamina tradicional, influenciando centenas de processos — desde saúde óssea e função imunológica até regulação do humor e, importantemente, metabolismo e controle de peso.\nPesquisas consistentemente ligaram a deficiência de vitamina D ao ganho de peso e dificuldade em perder peso. Estudos mostram que pessoas com níveis adequados de vitamina D tendem a perder peso mais facilmente e manter uma composição corporal mais saudável. A vitamina D parece afetar o comportamento das células de gordura, sensibilidade à insulina e regulação do apetite.\nInfelizmente, a deficiência de vitamina D é notavelmente comum. Dependendo de onde mora, época do ano, tom de pele e quanto tempo passa ao ar livre, pode não estar produzindo o suficiente pela exposição solar.\nA melhor fonte natural é luz solar direta — cerca de 15-30 minutos de sol do meio-dia nos braços e rosto, sem protetor solar, algumas vezes por semana. Fontes alimentares incluem peixes gordurosos como salmão e cavalinha, gemas de ovo, leite e cereais fortificados, e cogumelos expostos à luz UV. Pode ser difícil obter vitamina D suficiente apenas pela alimentação.\nDada a frequência da deficiência e seu impacto significativo, vale pedir ao seu profissional de saúde para verificar seus níveis de vitamina D com um exame de sangue simples. Se estiver deficiente, a suplementação é segura, acessível e eficaz.",
            "keyTakeaways": [
                "A deficiência de vitamina D está ligada ao ganho de peso e dificuldade em perdê-lo",
                "Afeta o comportamento das células de gordura, sensibilidade à insulina e regulação do apetite",
                "A melhor fonte é luz solar — 15-30 minutos algumas vezes por semana",
                "Fontes alimentares incluem peixes gordurosos, gemas de ovo e alimentos fortificados",
                "Peça ao profissional de saúde para testar seus níveis e suplemente se necessário"
            ],
            "actionStep": "Agende um exame de sangue de vitamina D com seu profissional de saúde se não fez recentemente. Enquanto isso, tente tomar 15-20 minutos de sol hoje — faça uma caminhada, sente-se ao ar livre no almoço, ou simplesmente fique em um lugar ensolarado.",
            "journalPrimary": "Quanto tempo passa ao ar livre na luz natural do sol? A deficiência de vitamina D poderia estar influenciando seus níveis de energia ou progresso de bem-estar? Qual é uma forma de ter mais luz natural na rotina diária?"
        },
        67: {
            "introduction": "Se o preparo de refeições é a filosofia, o cozimento em lote é a prática! Hoje vamos mergulhar no como cozinhar uma vez e comer bem a semana toda. Essa é uma daquelas habilidades que, uma vez dominada, vai economizar horas, reduzir seu estresse, e fazer a alimentação saudável parecer quase sem esforço.",
            "mainContent": "O cozimento em lote é a arte de preparar grandes quantidades de comida de uma vez, depois armazenar para refeições fáceis durante a semana. É o ato máximo de autocuidado — seu eu de domingo amando seu eu de quarta ao garantir que uma refeição saudável está pronta e esperando, não importa quão agitado o dia fique.\nA primeira chave para o cozimento em lote bem-sucedido é escolher receitas que armazenam e reaquecem bem. Sopas, ensopados, chili, bowls de grãos, vegetais assados, proteínas assadas e caçarolas são todos excelentes candidatos. Alimentos com texturas crocantes ou folhas delicadas não armazenam tão bem, então guarde esses para preparação fresca.\nPreparar ingredientes em quantidade é onde a economia de tempo real acontece. Lave e pique todos os vegetais de uma vez. Cozinhe um lote grande de grãos — arroz, quinoa ou farro. Prepare várias porções de proteína — frango assado, carne moída, tofu ou ovos cozidos. Armazene cada componente separadamente, e você tem blocos de construção modulares que podem criar refeições diferentes ao longo da semana.\nInvestir em recipientes de armazenamento de qualidade faz diferença genuína. Recipientes de vidro com tampas seguras são ideais — não absorvem odores, são seguros para micro-ondas e você pode ver exatamente o que tem dentro.\nAqui vai uma dica profissional: congele porções extras. Dobre ou triplique receitas e congele porções individuais em recipientes etiquetados. Naqueles dias inevitáveis quando a vida supera seus planos, seu freezer se torna seu serviço pessoal de entrega de refeições.",
            "keyTakeaways": [
                "Escolha receitas que armazenam e reaquecem bem: sopas, ensopados, bowls, proteínas assadas",
                "Prepare ingredientes em quantidade e armazene separadamente para versatilidade",
                "Recipientes de vidro de qualidade mantêm a comida fresca e facilitam pegar refeições",
                "Congelar porções extras cria um estoque de reserva para semanas corridas",
                "O cozimento em lote é o ato máximo de cuidar do seu eu futuro"
            ],
            "actionStep": "Planeje sua sessão de cozimento em lote para esta semana. Escolha duas receitas que armazenam bem, faça uma lista de compras e reserve 2-3 horas no calendário para cozinhar.",
            "journalPrimary": "O que te impede de cozinhar durante semanas corridas? Como seria abrir a geladeira e sempre encontrar uma refeição saudável pronta? Que receitas simples você gostaria de comer durante a semana?"
        },
        68: {
            "introduction": "No nosso mundo sempre conectado, telas estão em todo lugar — e podem estar afetando sua jornada de bem-estar de formas que não considerou. Hoje vamos explorar a conexão surpreendentemente forte entre tempo de tela e peso, encontrando formas práticas de criar um equilíbrio mais saudável. Não é sobre desistir da tecnologia — é sobre usá-la com mais intenção.",
            "mainContent": "A relação entre tempo de tela e ganho de peso é bem documentada mas frequentemente ignorada. Funciona através de vários mecanismos, cada um contribuindo silenciosamente para o desafio de manter um peso saudável.\nO impacto mais óbvio é o comportamento sedentário. Cada hora diante de uma tela é uma hora sem se mover. Estudos mostraram que adultos que assistem mais de quatro horas de TV por dia têm taxas significativamente mais altas de ganho de peso. Mas não é só televisão — trabalho no computador, rolagem no celular e uso de tablet todos contribuem para ficar sentada por longos períodos.\nTalvez ainda mais prejudicial é a ligação entre uso de tela e alimentação sem atenção. Quando come assistindo TV, rolando o celular ou trabalhando no computador, você se desconecta da experiência alimentar. Sua atenção está dividida, e você perde os sinais de saciedade do corpo. Pesquisas mostram que pessoas que comem diante de telas consomem significativamente mais — e relatam sentir menos satisfação.\nDefinir limites no tempo recreativo de tela não significa virar ermitã tecnológica. Significa ser intencional. Tente designar certos momentos como livres de tela — talvez a primeira hora após acordar, horário das refeições e a última hora antes de dormir. Preencha esses momentos com atividades que naturalmente envolvem mais movimento.\nFazer pausas de movimento a cada 30-60 minutos durante tempo de tela no trabalho é um antídoto poderoso. Programe um timer gentil e levante-se, alongue-se, caminhe para pegar água, ou faça um minuto de movimento. Considere mesas de trabalho em pé, esteiras para caminhar, ou até fazer elevações de panturrilha durante videochamadas.",
            "keyTakeaways": [
                "Tempo prolongado de tela promove comportamento sedentário e alimentação sem atenção",
                "Comer diante de telas leva a maior consumo e menos satisfação",
                "Designe momentos livres de tela: primeira hora do dia, refeições e antes de dormir",
                "Faça pausas de movimento a cada 30-60 minutos durante trabalho com tela",
                "Mesas de pé e esteiras transformam tempo passivo de tela em tempo ativo"
            ],
            "actionStep": "Escolha uma refeição hoje para comer completamente livre de tela — sem celular, sem TV, sem computador. Programe um timer para pausas de movimento a cada 45 minutos durante seu tempo de tela. Observe a diferença na experiência alimentar e níveis de energia.",
            "journalPrimary": "Quantas horas por dia passa diante de telas? Como isso se compara com quanto tempo passa se movendo? Qual é um hábito de tempo de tela que poderia ajustar para melhor apoiar seus objetivos de bem-estar?"
        },
        69: {
            "introduction": "Em um mundo de transformações nas redes sociais e fotos de antes e depois, é tão fácil olhar para a jornada de outra pessoa e sentir que a sua não se compara. Hoje vamos nos libertar da armadilha da comparação — aquela ladra sorrateira de alegria que drena sua motivação e te desconecta do progresso lindo que é unicamente seu.",
            "mainContent": "Comparação é uma das tendências humanas mais naturais, mas no contexto da jornada de bem-estar, pode ser uma das mais destrutivas. Quando compara seu Dia 69 com o Dia 300 de outra pessoa, ou seu progresso real com o destaque cuidadosamente curado das redes sociais de alguém, está comparando seus bastidores com o produto final dela — e isso nunca é uma comparação justa.\nAqui está uma verdade fundamental: o corpo, metabolismo, história e circunstâncias de cada pessoa são diferentes. Alguém que parece perder peso sem esforço pode ter um ponto de partida completamente diferente, genética diferente, níveis de estresse diferentes, histórico médico diferente ou redes de apoio diferentes. Você está vendo uma fração da história dela e comparando com a totalidade da sua. A comparação é inerentemente incompleta e portanto inerentemente injusta — para você.\nAs redes sociais tornam isso exponencialmente mais difícil. As fotos de transformação que vê foram selecionadas de dezenas ou centenas de tentativas. A iluminação, ângulos, poses, filtros e timing são todos otimizados para mostrar a diferença mais dramática. O que não vê são os dias inchados, os contratempos, as frustrações, as lágrimas e as lutas que fazem parte de toda jornada real.\nEm vez de olhar para fora, redirecione sua atenção para dentro. Foque em marcadores pessoais de sucesso que são inteiramente seus: Tem mais energia do que quando começou? Está dormindo melhor? Está fazendo escolhas alinhadas com seus valores? Se sente mais forte, mais confiante, mais no controle? Está aparecendo consistentemente, mesmo quando é difícil?\nQuando vê o sucesso de outra pessoa, pratique usá-lo como inspiração em vez de um padrão que precisa igualar. A jornada dela não invalida a sua — confirma que mudança é possível, e você já está no caminho.",
            "keyTakeaways": [
                "Comparação é inerentemente injusta — você vê os destaques dos outros, não a história completa",
                "O corpo, metabolismo e circunstâncias de cada pessoa são únicos",
                "Redes sociais mostram ficção curada, não a realidade do dia a dia",
                "Foque nos seus marcadores pessoais: energia, consistência, força, crescimento emocional",
                "Use o sucesso dos outros como inspiração, não como régua para seu próprio progresso"
            ],
            "actionStep": "Se segue contas nas redes sociais que consistentemente te fazem sentir \"atrasada\" ou inadequada, deixe de seguir ou silencie três delas hoje. Substitua por contas que inspiram, educam e celebram progresso realista. Observe como seu feed — e seu humor — mudam.",
            "journalPrimary": "Quando se compara com outros na jornada de bem-estar, como se sente? Que vitórias pessoais pode celebrar agora que não têm nada a ver com a história de outra pessoa?"
        },
        70: {
            "introduction": "Exploramos lanches saudáveis no Dia 44, e hoje vamos mais fundo. Lanchar de forma inteligente é verdadeiramente uma arte — quando feito com intenção, apoia energia estável, reduz desejos e faz todo o seu dia alimentar parecer mais calmo e equilibrado. Vamos refinar suas habilidades de lanche com algumas estratégias poderosas e ideias deliciosas.",
            "mainContent": "A diferença entre um lanche que apoia sua jornada e um que sabota não é apenas sobre o alimento em si — é sobre a intenção por trás. Lanchar inteligente significa usar comida estrategicamente para fazer ponte entre refeições, estabilizar açúcar no sangue e prevenir o tipo de fome extrema que leva a comer demais na próxima refeição. É nutrição com propósito, não beliscar sem pensar.\nAntes de pegar um lanche, faça uma breve pausa e cheque consigo mesma. Pergunte: \"Estou fisicamente com fome, ou isso é emocional?\" Fome física aumenta gradualmente, pode ser satisfeita por uma variedade de alimentos, e vem com sensações físicas como estômago roncando ou baixa energia. Fome emocional tende a aparecer de repente, deseja alimentos muito específicos (geralmente processados ou açucarados), e é impulsionada por sentimentos como tédio, estresse ou solidão.\nQuando determinar que fome física está presente, busque lanches que combinem pelo menos dois destes três elementos: proteína, fibra e gorduras saudáveis. Essa combinação cria satisfação duradoura e açúcar no sangue estável. Iogurte grego com frutas vermelhas dá proteína mais fibra. Fatias de maçã com pasta de amendoim fornecem fibra mais gordura saudável mais um toque de proteína. Ovos cozidos oferecem proteína pura. Homus com vegetais crus entrega fibra, gordura saudável e alguma proteína.\nIntenção de porção é importante — coma seu lanche de um prato ou tigela pequena, nunca direto da embalagem. Isso cria um limite visual claro e permite comer com atenção em vez de automaticamente.\nA estratégia mais profunda é aprender a lanchar com consciência em vez de hábito. Quando lanches são escolhidos para apoiar seu corpo — não para distrair de emoções ou preencher o tempo — se tornam ferramentas poderosas para consistência.",
            "keyTakeaways": [
                "Pause antes de lanchar para determinar se a fome é física ou emocional",
                "Combine proteína, fibra e/ou gorduras saudáveis para satisfação duradoura",
                "Coma lanches de um prato ou tigela, nunca direto da embalagem",
                "Lanchar estratégico previne fome extrema e excessos noturnos",
                "Lanchar intencional é ferramenta de consistência, não fonte de culpa"
            ],
            "actionStep": "Prepare dois lanches inteligentes para amanhã usando a fórmula proteína-fibra-gordura: talvez iogurte grego com frutas vermelhas e algumas castanhas, e palitos de vegetais com homus. Coloque na frente e no centro da geladeira.",
            "journalPrimary": "Pense nos seus padrões típicos de lanche. A maioria dos seus lanches são escolhidos intencionalmente ou pegos impulsivamente? O que mudaria se abordasse cada lanche com um momento de consciência?"
        },
        71: {
            "introduction": "Comer fora é um dos grandes prazeres da vida — os sabores, a atmosfera, a companhia. E aqui vai a notícia maravilhosa: você pode absolutamente curtir restaurantes enquanto se mantém alinhada com seus objetivos de bem-estar. Hoje vamos dominar a arte de comer fora com confiança, para nunca ter que escolher entre prazer social e autocuidado.",
            "mainContent": "Refeições de restaurante tendem a ter mais calorias, sódio e gordura que refeições caseiras, mas isso não significa que precisam atrapalhar seu progresso. Com algumas estratégias simples, pode navegar qualquer cardápio com confiança e sair satisfeita e orgulhosa das suas escolhas.\nUma das estratégias mais eficazes acontece antes de chegar: pesquise o cardápio online. A maioria dos restaurantes publica seus cardápios nos sites. Passe alguns minutos decidindo o que vai pedir antes de chegar. Isso elimina a pressão de tomar uma decisão quando está com fome, cercada por descrições tentadoras e aromas deliciosos.\nNa mesa, considere pedir primeiro. Pesquisas mostram que pessoas que pedem depois são mais influenciadas pelo que outros escolhem. Se a pessoa antes de você pede o hambúrguer duplo com batata frita, é mais provável que faça o mesmo — mesmo que originalmente planejasse pedir o peixe grelhado.\nNunca tenha vergonha de fazer pedidos especiais. Peça molhos e temperos à parte — esse simples movimento pode economizar centenas de calorias. Peça vegetais no vapor em vez de fritas. Pergunte como as coisas são preparadas e se há opções grelhadas ou assadas. Você não está sendo difícil — está sendo intencional com sua saúde.\nUma dica prática: leve metade da refeição para casa. Porções de restaurante em muitos lugares são dramaticamente maiores do que seu corpo realmente precisa. Peça uma embalagem para viagem quando sua comida chegar e embale metade imediatamente. Você terá duas refeições satisfatórias pelo preço de uma.",
            "keyTakeaways": [
                "Pesquise cardápios online e decida seu pedido antes de chegar",
                "Peça primeiro na mesa para evitar ser influenciada pelas escolhas dos outros",
                "Peça molhos e temperos à parte para controlar a ingestão calórica",
                "Faça pedidos de modificação livremente — restaurantes geralmente ficam felizes em atender",
                "Leve metade para casa: vai aproveitar duas refeições e evitar comer demais"
            ],
            "actionStep": "Na próxima vez que comer fora, pesquise o cardápio online com antecedência e escolha sua refeição antes de ir. No restaurante, peça uma modificação — molho à parte, vegetais extras, ou uma opção grelhada. Observe como é comer fora com um plano.",
            "journalPrimary": "Como costuma se sentir depois de comer em um restaurante — satisfeita e orgulhosa, ou desconfortavelmente cheia e arrependida? Qual estratégia da lição de hoje poderia mudar essa experiência?"
        },
        72: {
            "introduction": "Hoje vamos celebrar um dos nutrientes mais poderosos da natureza — os ácidos graxos ômega-3. Essas gorduras essenciais não apenas apoiam coração e cérebro; podem realmente ajudar seu corpo a gerenciar o peso mais eficazmente. Vamos explorar por que essas gorduras notáveis merecem um papel protagonista no seu plano de nutrição.",
            "mainContent": "Ácidos graxos ômega-3 são chamados \"essenciais\" porque seu corpo não pode produzi-los sozinho — você precisa obtê-los pela alimentação. Desempenham papéis críticos, desde função cerebral e saúde cardíaca até resposta imunológica e comunicação celular. E cada vez mais, pesquisas revelam sua importância para o controle de peso.\nUm dos benefícios mais significativos dos ômega-3 é seu poderoso efeito anti-inflamatório. Inflamação crônica de baixo grau é cada vez mais reconhecida como impulsionadora do ganho de peso, resistência à insulina e dificuldade em perder peso. Ao reduzir a inflamação, os ômega-3 ajudam a criar um ambiente interno mais favorável para o controle saudável do peso.\nAlgumas pesquisas sugerem que os ômega-3 podem ajudar a reduzir o apetite através de seus efeitos nos hormônios reguladores de fome, incluindo a leptina. Participantes em estudos que aumentaram sua ingestão de ômega-3 relataram sentir mais satisfação após as refeições e experimentaram menos desejos.\nAs melhores fontes alimentares de ômega-3 são peixes gordurosos: salmão, cavalinha, sardinha, arenque e anchova. Busque duas a três porções por semana. Fontes vegetais incluem nozes, sementes de chia, linhaça e sementes de cânhamo, embora o tipo de ômega-3 nas plantas (ALA) precise ser convertido nas formas ativas (EPA e DHA) encontradas no peixe, e essa conversão é ineficiente.\nSe sua ingestão de peixe gorduroso é baixa, um suplemento de óleo de peixe ou ômega-3 à base de algas de qualidade vale considerar. Procure suplementos que forneçam pelo menos 500 mg de EPA e DHA combinados por porção.",
            "keyTakeaways": [
                "Ômega-3 reduzem inflamação crônica, apoiando o controle saudável de peso",
                "Podem ajudar a reduzir o apetite e aumentar a satisfação após refeições",
                "Melhores fontes: peixes gordurosos como salmão, cavalinha e sardinha (2-3 porções semanais)",
                "Fontes vegetais incluem nozes, sementes de chia e linhaça",
                "Considere suplementação se a ingestão alimentar for baixa"
            ],
            "actionStep": "Planeje incluir um alimento rico em ômega-3 nas suas refeições esta semana. Adicione salmão ao plano de jantar, polvilhe sementes de chia ou nozes na aveia ou iogurte matinal, ou pegue um suplemento de ômega-3 de qualidade.",
            "journalPrimary": "Com que frequência come peixe gorduroso ou outros alimentos ricos em ômega-3? Qual é uma forma simples de aumentar sua ingestão de ômega-3 esta semana? Como reduzir a inflamação poderia te ajudar a se sentir melhor no geral?"
        },
        73: {
            "introduction": "Você não precisa de uma academia chique ou equipamento caro para ter um treino incrível. Hoje vamos provar que um espaço de exercício eficaz pode ser criado na sua própria casa com investimento mínimo. Sua sala, quarto ou garagem podem se tornar um santuário de bem-estar — vamos montar!",
            "mainContent": "Uma das barreiras mais comuns ao exercício consistente é a crença de que precisa de academia. O deslocamento toma tempo, a mensalidade custa dinheiro e o ambiente pode parecer intimidante. A bela verdade é que treinos altamente eficazes podem acontecer bem onde você mora, com equipamento que custa menos que um mês da maioria das academias.\nFaixas elásticas são talvez o melhor custo-benefício em equipamento fitness. Por menos de R$50, pode conseguir um conjunto com diferentes níveis de resistência que trabalham cada grupo muscular. São incrivelmente versáteis, ocupam praticamente nenhum espaço e viajam com você para qualquer lugar.\nUm par de halteres ajustáveis é um investimento que vale a pena se o orçamento permitir. Substituem uma prateleira inteira de pesos individuais e permitem aumentar progressivamente a resistência conforme fica mais forte.\nExercícios com peso corporal devem ser a base de qualquer rotina de treino em casa. Flexões, agachamentos, avanços, pranchas, alpinistas e burpees não exigem equipamento e podem ser modificados para qualquer nível. Usam seu próprio corpo como resistência, construindo força funcional que se traduz diretamente para a vida cotidiana.\nUm tapete de yoga fornece uma superfície confortável para exercícios no chão, alongamento e yoga. Uma corda de pular, um dos equipamentos cardiovasculares mais acessíveis, oferece treino cardiovascular intenso em espaço muito pequeno. E a internet está transbordando de vídeos de treino gratuitos.\nA chave é criar um espaço dedicado, mesmo que pequeno. Limpe um canto do cômodo, mantenha seu equipamento visível e acessível, e torne convidativo. Quando seu espaço de treino está pronto e esperando, a barreira para começar cai dramaticamente.",
            "keyTakeaways": [
                "Faixas elásticas oferecem versatilidade e valor incríveis por menos de R$50",
                "Exercícios com peso corporal não exigem equipamento e trabalham todos os grupos musculares",
                "Um tapete de yoga e corda de pular completam uma academia caseira acessível e completa",
                "Vídeos gratuitos de treino online fornecem rotinas guiadas ilimitadas",
                "Criar um espaço dedicado e acessível remove barreiras para começar"
            ],
            "actionStep": "Se não tem equipamento de exercício em casa, compre um conjunto de faixas elásticas hoje (são bem acessíveis). Se já tem algum equipamento, monte um canto dedicado de treino em casa — estenda seu tapete, organize suas faixas ou pesos, e torne o espaço convidativo.",
            "journalPrimary": "Qual tem sido sua maior barreira para exercício consistente — tempo, dinheiro, intimidação ou outra coisa? Como ter um espaço simples e pronto em casa poderia mudar sua relação com o movimento?"
        },
        74: {
            "introduction": "Você pode ter ouvido falar do índice glicêmico, mas hoje vamos aprender sobre seu primo mais prático e preciso: a carga glicêmica. Esse conceito te dá uma visão mais clara de como diferentes alimentos realmente afetam seu açúcar no sangue em porções do mundo real. É uma ferramenta que ajuda a fazer escolhas mais inteligentes de carboidratos sem restrição desnecessária.",
            "mainContent": "O índice glicêmico (IG) classifica alimentos em uma escala de 0-100 baseado na rapidez com que elevam o açúcar no sangue. Embora útil como ponto de partida, o IG tem uma limitação significativa: não considera quanto de um alimento você realmente come. É aqui que a carga glicêmica (CG) se torna muito mais prática e precisa.\nA carga glicêmica considera tanto a qualidade *quanto* a quantidade de carboidratos. É calculada multiplicando o IG de um alimento pelos gramas reais de carboidratos em uma porção típica, depois dividindo por 100. Uma CG de 10 ou menos é considerada baixa, 11-19 é moderada, e 20 ou acima é alta.\nAqui está por que isso importa: a melancia tem um índice glicêmico alto (72), o que pode fazer você pensar que é uma escolha ruim. Mas uma porção típica de melancia contém relativamente poucos carboidratos porque é principalmente água. Sua carga glicêmica é apenas 4 — muito baixa. Então a melancia é na verdade um alimento maravilhoso e amigável ao açúcar no sangue apesar de seu IG enganoso.\nUma estratégia ainda mais prática é o pareamento de alimentos. Quando come um alimento de alto IG junto com proteína, gordura saudável ou fibra, você reduz significativamente seu impacto glicêmico. Um pedaço de pão branco sozinho vai disparar seu açúcar rapidamente. Mas o mesmo pedaço de pão comido com abacate (gordura saudável) e peru (proteína) tem um efeito dramaticamente reduzido. Isso significa que não precisa evitar obsessivamente nenhum alimento — precisa apenas montar pratos equilibrados.\nPara sua jornada de bem-estar, a mensagem é simples: foque em montar refeições em torno de alimentos com carga glicêmica mais baixa — vegetais, leguminosas, grãos integrais e a maioria das frutas — e quando incluir alimentos de alto IG, combine-os com proteína, gordura ou fibra.",
            "keyTakeaways": [
                "A carga glicêmica é mais precisa que o índice glicêmico porque considera o tamanho da porção",
                "Alimentos com CG baixa (10 ou menos) têm impacto mínimo no açúcar no sangue",
                "Alguns alimentos de alto IG como melancia na verdade têm cargas glicêmicas muito baixas",
                "Parear carboidratos com proteína, gordura ou fibra reduz seu impacto glicêmico",
                "Monte pratos equilibrados em vez de evitar alimentos específicos"
            ],
            "actionStep": "Na sua próxima refeição, pratique a estratégia de pareamento: se está comendo carboidratos (pão, arroz, massa, fruta), garanta que proteína e/ou gordura saudável façam parte da mesma refeição. Observe se sua energia fica mais estável nas horas seguintes.",
            "journalPrimary": "Como entender a carga glicêmica muda sua visão dos carboidratos? Parece mais empoderador que simplesmente rotular carboidratos como \"bons\" ou \"ruins\"? Quais alimentos de alto IG poderia apreciar com menos culpa sabendo como pareá-los corretamente?"
        },
        75: {
            "introduction": "Hoje vamos ter uma conversa poderosa sobre a diferença entre *pensar* sobre mudança e *criar* mudança. Essa distinção — entre ação passiva e ação massiva — pode ser a chave que destrava o progresso que tem buscado. Não é sobre trabalhar mais duro; é sobre aparecer de forma diferente.",
            "mainContent": "Ação passiva parece produtiva na superfície. Inclui ler sobre nutrição, assistir vídeos de treino, pesquisar os melhores suplementos, fazer listas, criar planos elaborados e pensar sobre o que fará diferente. Essas atividades parecem progresso porque engajam sua mente. Mas aqui está a verdade desconfortável: ação passiva raramente produz resultados físicos. Você não pode pensar seu caminho para o bem-estar — precisa viver o caminho.\nAção massiva é diferente. É o trabalho desconfortável, às vezes sem glamour, de realmente *fazer* as coisas que tem aprendido. É preparar a refeição em vez de salvar a receita. É sair para caminhar em vez de pesquisar rotas de caminhada. É beber a água, comer os vegetais, fazer os agachamentos, ir dormir no horário. Ação massiva é onde teoria vira realidade.\nO que torna a ação massiva tão poderosa: ações pequenas e consistentes sempre superam explosões ocasionais de esforço extremo. Você não precisa de um plano perfeito, um dia perfeito ou motivação perfeita. Precisa apenas fazer a próxima coisa certa, agora. Caminhar 10 minutos. Beber um copo de água. Escolher vegetais no almoço. Essas ações individuais podem parecer pequenas, mas compostas ao longo de dias, semanas e meses, transformam sua vida.\nAlgo importante: ação massiva é enraizada em compromisso, não humor. Ação passiva espera motivação — \"Vou começar quando me sentir pronta\". Ação massiva acontece independente de como se sente — \"Posso não estar a fim, mas me comprometi com isso, então vou fazer\". E aqui está o paradoxo bonito: ação em si gera motivação. Você não espera se sentir motivada para agir; age, e a motivação vem depois.\nIsso não significa se empurrar até a exaustão. Ação massiva pode ser gentil. Caminhar em vez de correr. Preparar duas refeições em vez de sete. Beber um copo extra de água. O \"massivo\" não é sobre intensidade — é sobre consistência e seguir adiante.",
            "keyTakeaways": [
                "Ação passiva (ler, planejar, pesquisar) parece produtiva mas raramente cria resultados físicos",
                "Ação massiva significa fazer o trabalho desconfortável de realmente viver seu conhecimento",
                "Ações pequenas e consistentes sempre superam esforços extremos ocasionais",
                "Ação gera motivação — não o contrário",
                "\"Massivo\" se refere a consistência e seguir adiante, não intensidade"
            ],
            "actionStep": "Identifique uma coisa sobre a qual tem estado em \"ação passiva\" — algo que tem pesquisado, planejado ou pensado mas não fez de verdade. Faça hoje. Não perfeitamente, não completamente — apenas comece. Dê o primeiro passo real.",
            "journalPrimary": "Onde na jornada de bem-estar tem ficado presa em ação passiva — aprendendo e planejando sem fazer? Qual é o menor passo que poderia dar hoje para mudar para ação massiva? O que tem te impedido de começar?"
        },
        76: {
            "introduction": "Hoje vamos explorar o mundo vibrante dos sucos de vegetais — uma forma maravilhosa de aumentar sua ingestão de nutrientes e adicionar mais bondade das plantas ao seu dia. Suco fresco de vegetais pode ser um complemento lindo ao seu plano de nutrição, oferecendo uma dose concentrada de vitaminas e minerais em cada gole.",
            "mainContent": "Sucos de vegetais ganharam popularidade como forma de aumentar o consumo diário de vegetais, e com razão. Quando faz suco de vegetais frescos, está extraindo uma fonte concentrada de vitaminas, minerais e fitonutrientes que seu corpo pode absorver rápida e eficientemente. Pense como um jardim líquido — toda a bondade da natureza entregue em um copo refrescante.\nA chave para sucos saudáveis é manter os vegetais como estrela do show. Embora frutas adicionem doçura natural, também adicionam açúcar, que pode elevar o açúcar no sangue e trabalhar contra seus objetivos. Uma boa regra é fazer seu suco com pelo menos 80% de vegetais — folhas verdes como espinafre ou couve, pepinos, salsão e cenouras fazem bases excelentes. Se precisar de um toque de doçura, um pedaço pequeno de maçã ou algumas frutas vermelhas é suficiente.\nÉ importante entender que suco de vegetais é um complemento ao seu plano de nutrição, não substituto para refeições inteiras. Fazer suco remove muito da fibra que vegetais inteiros fornecem, e fibra é essencial para saciedade, saúde digestiva e regulação do açúcar no sangue. Pense no suco como um impulso de nutrientes entre refeições ou junto a um prato equilibrado.\nAo escolher entre sucos frescos e industrializados, fresco é sempre preferível. Muitos sucos comerciais contêm açúcares adicionados, conservantes e foram pasteurizados de formas que reduzem seu conteúdo nutricional. Se investir em um espremedor simples ou um bom liquidificador com coador, pode criar sucos frescos e vibrantes em casa em minutos.\nHidratação é outro benefício lindo dos sucos de vegetais. Muitos vegetais têm alto teor de água, então seu suco naturalmente ajuda a mantê-la hidratada ao longo do dia.",
            "keyTakeaways": [
                "Mantenha sucos predominantemente à base de vegetais, limitando frutas para reduzir açúcar",
                "Suco de vegetais complementa seu plano de nutrição mas não deve substituir refeições inteiras",
                "Suco fresco caseiro é muito superior a opções industrializadas",
                "Fazer suco fornece vitaminas concentradas, minerais e hidratação",
                "Comece simples e experimente combinações que você goste"
            ],
            "actionStep": "Experimente fazer um suco simples de vegetais hoje. Combine pepino, salsão, um punhado de espinafre e meio limão. Observe como se sente refrescada e energizada depois.",
            "journalPrimary": "Quais vegetais você gosta de comer que também poderia gostar em forma de suco? Como adicionar um suco de vegetais diário poderia apoiar seus objetivos gerais de nutrição?"
        },
        77: {
            "introduction": "Hoje vamos honrar uma verdade que muitos ignoram na jornada de bem-estar: a recuperação é tão importante quanto o próprio movimento. Seu corpo fica mais forte, se cura e se transforma não durante os treinos, mas durante o descanso que os segue. Vamos explorar como se recuperar com sabedoria e carinho.",
            "mainContent": "Quando se envolve em movimento gentil ou atividade física mais vigorosa, está criando microlesões minúsculas nas fibras musculares. Isso é completamente natural e é na verdade como o corpo constrói força — mas apenas se você der tempo e recursos para reparar. Sem recuperação adequada, esses pequenos estresses se acumulam, levando a fadiga, lesão e esgotamento.\nO sono é a base da recuperação. Durante o sono profundo, seu corpo libera hormônio do crescimento, repara tecidos e consolida as adaptações físicas da prática de movimento. Busque sete a nove horas de sono de qualidade por noite, e observe como seu corpo se sente e funciona melhor quando prioriza o descanso.\nA hidratação desempenha papel crítico na recuperação também. A água ajuda a transportar nutrientes para os músculos, eliminar resíduos metabólicos e manter a elasticidade dos tecidos conjuntivos. Após qualquer sessão de movimento, crie o hábito de beber água com atenção.\nDias de descanso não são dias de preguiça — são dias de crescimento. Incluir pelo menos um ou dois dias de descanso por semana na rotina de movimento permite que músculos, articulações e sistema nervoso se recuperem totalmente. Nesses dias, pode curtir alongamento suave, uma caminhada tranquila, ou simplesmente permitir que seu corpo fique parado.\nAlongamento e rolo de espuma são ferramentas de recuperação maravilhosas que podem reduzir tensão muscular, melhorar flexibilidade e aumentar fluxo sanguíneo para músculos cansados. Mesmo dez minutos de alongamento suave após o movimento pode fazer diferença significativa.\nAcima de tudo, ouça seu corpo. Se algo parece doloroso em vez de desafiador, se está incomumente fatigada, ou se sua motivação desapareceu completamente, são sinais de que precisa de mais recuperação. Honrar esses sinais é sabedoria, não fraqueza.",
            "keyTakeaways": [
                "A recuperação é quando o corpo realmente constrói força e se adapta",
                "Sono de qualidade é a ferramenta de recuperação mais poderosa que você tem",
                "Mantenha-se hidratada para apoiar reparo muscular e remoção de resíduos",
                "Dias de descanso são essenciais, não opcionais",
                "Alongamento e rolo de espuma melhoram a recuperação e reduzem dores"
            ],
            "actionStep": "Após sua próxima sessão de movimento, passe dez minutos alongando os músculos que mais usou. Foque em respiração lenta e profunda enquanto segura cada alongamento por 20-30 segundos.",
            "journalPrimary": "Como aborda a recuperação atualmente na sua rotina de bem-estar? Tende a se empurrar através da fadiga, ou honra a necessidade do corpo de descansar? O que poderia fazer diferente?"
        },
        78: {
            "introduction": "Já se perguntou por que algumas pessoas lutam para se sentir satisfeitas não importa quanto comam? Hoje vamos explorar a resistência à leptina — um fator fascinante e frequentemente incompreendido que pode tornar sua jornada de bem-estar mais desafiadora do que precisa ser. Entender isso pode ser uma virada de jogo para sua relação com fome e saciedade.",
            "mainContent": "A leptina é um hormônio produzido pelas suas células de gordura que age como mensageiro para o cérebro, sinalizando que você tem energia armazenada suficiente e que está tudo bem parar de comer. Em um sistema que funciona bem, a leptina ajuda a regular seu apetite naturalmente. Mas quando a resistência à leptina se desenvolve, esse sistema de comunicação se rompe.\nA resistência à leptina ocorre quando o cérebro para de responder adequadamente aos sinais da leptina, mesmo quando há muita leptina circulando. Imagine ligar para alguém, mas a pessoa não consegue te ouvir não importa quão alto fale — a mensagem está sendo enviada, mas não recebida. O cérebro essencialmente acredita que você ainda está com fome, mesmo quando o corpo tem energia armazenada mais que suficiente.\nEssa condição está intimamente ligada ao excesso de peso, alimentação crônica excessiva e altos níveis de inflamação no corpo. Quando o cérebro não \"ouve\" a leptina, dispara sinais de fome aumentados, desacelera o metabolismo para conservar energia e torna o corpo resistente a liberar gordura armazenada. Não é um problema de força de vontade — é um problema de comunicação hormonal.\nA boa notícia é que a sensibilidade à leptina pode ser melhorada através de várias estratégias de estilo de vida. Priorizar sono de qualidade é essencial, pois a privação de sono prejudica diretamente a sinalização da leptina. Movimento gentil regular ajuda a melhorar a sensibilidade hormonal do corpo de forma geral. Reduzir açúcares adicionados e alimentos processados diminui a inflamação que contribui para a resistência à leptina. E incluir alimentos anti-inflamatórios como peixes gordurosos, frutas vermelhas, folhas verdes e azeite apoia a capacidade do corpo de ouvir seus próprios sinais.\nPaciência é importante. Melhorar a sensibilidade à leptina é um processo gradual, mas conforme melhora, provavelmente perceberá que a fome se torna mais manejável, os desejos diminuem e o corpo começa a encontrar seu equilíbrio natural mais facilmente.",
            "keyTakeaways": [
                "A leptina é um hormônio que sinaliza saciedade ao cérebro",
                "A resistência à leptina significa que o cérebro não consegue \"ouvir\" esses sinais adequadamente",
                "Está ligada a inflamação, excesso de peso e alimentação excessiva",
                "Sono, movimento, redução de açúcar e alimentos anti-inflamatórios ajudam a restaurar a sensibilidade",
                "Melhorar a sensibilidade à leptina torna a fome mais manejável ao longo do tempo"
            ],
            "actionStep": "Inclua um alimento anti-inflamatório nas suas refeições hoje — um punhado de frutas vermelhas, uma porção de peixe gordo, ou uma porção generosa de folhas verdes — e saiba que está apoiando a comunicação hormonal do seu corpo.",
            "journalPrimary": "Já sentiu que não importa quanto comesse, não conseguia se sentir verdadeiramente satisfeita? Como entender a resistência à leptina muda como pensa sobre fome e saciedade?"
        },
        79: {
            "introduction": "Hoje vamos olhar com compaixão e honestidade para os açúcares adicionados — aqueles adoçantes sorrateiros escondidos em tantos alimentos que comemos todos os dias. Não é sobre privação ou eliminar toda doçura da vida. É sobre consciência, empoderamento e dar ao seu corpo a nutrição que ele realmente precisa.",
            "mainContent": "Açúcares adicionados são um dos maiores obstáculos ocultos na jornada de bem-estar. Diferente dos açúcares naturais encontrados em frutas e vegetais inteiros — que vêm embalados com fibra, vitaminas e minerais — açúcares adicionados fornecem calorias vazias que elevam o açúcar no sangue, disparam desejos e contribuem para inflamação, ganho de peso e quedas de energia. O desafio é que estão em toda parte, frequentemente escondidos em alimentos que não suspeitaria.\nAprender a ler rótulos é seu superpoder aqui. Açúcares adicionados têm muitos nomes — qualquer coisa terminando em \"-ose\" como glicose, frutose, sacarose e maltose é um açúcar. Mas também se escondem atrás de nomes como xarope de milho, néctar de agave, xarope de arroz, suco de cana e concentrado de frutas. Um único iogurte com sabor, barra de cereal ou molho de salada pode conter mais açúcar adicionado do que esperaria.\nObserve especialmente açúcar em alimentos salgados — molhos de massa, pão, condimentos e até frios frequentemente contêm açúcares adicionados. Essas fontes ocultas se acumulam ao longo do dia sem contribuir para sua satisfação ou nutrição.\nA coisa linda de reduzir açúcares adicionados é que suas papilas gustativas se ajustam. Quando gradualmente diminui a ingestão de açúcar, alimentos que antes pareciam sem graça começam a ter sabor naturalmente doce e delicioso. Um morango fresco se torna uma delícia. Uma batata-doce assada tem gosto de sobremesa. Isso não é sobre força de vontade — é sobre retreinar o paladar, e acontece naturalmente em duas a três semanas.\nSubstitua açúcares adicionados por doçura natural de frutas inteiras. Uma banana no smoothie matinal, frutas vermelhas na aveia, ou uma maçã crocante com pasta de amendoim podem satisfazer seu desejo por doce enquanto fornecem nutrição genuína. A palavra-chave é gradual — mudanças drásticas da noite para o dia frequentemente saem pela culatra, mas reduções pequenas e constantes criam transformação duradoura.",
            "keyTakeaways": [
                "Açúcares adicionados se escondem em muitos alimentos inesperados sob vários nomes",
                "Ler rótulos te empodera a fazer escolhas informadas",
                "Suas papilas gustativas se adaptam a menos açúcar em duas a três semanas",
                "Substitua açúcares adicionados por doçura natural de frutas inteiras",
                "Reduza gradualmente para mudança sustentável e duradoura"
            ],
            "actionStep": "Verifique os rótulos de três itens na sua cozinha que come regularmente. Procure açúcares adicionados sob qualquer um dos seus muitos nomes. Pode se surpreender com o que descobrir.",
            "journalPrimary": "Que papel o açúcar desempenha atualmente na sua alimentação? Existem alimentos açucarados específicos que busca por hábito em vez de prazer genuíno? Como reduzir poderia mudar sua energia e bem-estar?"
        },
        80: {
            "introduction": "Como começa sua manhã define o tom de tudo que vem depois. Hoje vamos explorar o poder transformador de uma rotina matinal — não um ritual rígido digno de Instagram, mas uma prática simples e amorosa que ajuda você a começar cada dia se sentindo centrada, energizada e alinhada com seus objetivos de bem-estar.",
            "mainContent": "Uma rotina matinal é uma das ferramentas mais poderosas para apoiar sua jornada de bem-estar. Quando começa o dia com intenção em vez de reação — pegar o celular, sair correndo pela porta, pular o café da manhã — você cria uma base de calma, clareza e autocuidado que se propaga por cada escolha que faz no resto do dia.\nConsistência começa com seu horário de acordar. Quando levanta mais ou menos no mesmo horário cada dia, apoia seu ritmo circadiano, que regula tudo desde níveis de energia e hormônios de fome até humor e metabolismo. Não precisa acordar ao amanhecer — simplesmente encontre um horário que funcione para sua vida e honre-o o mais consistentemente possível, mesmo nos fins de semana.\nHidratação deve ser uma das primeiras coisas que faz ao acordar. Após sete a nove horas sem água, seu corpo está naturalmente desidratado. Um copo grande de água — talvez com limão para uma limpeza gentil — reidrata suas células, apoia a digestão e ajuda você a se sentir mais alerta. Muitas pessoas confundem desidratação matinal com fadiga ou fome, então esse passo simples pode fazer diferença significativa.\nIncluir alguma forma de movimento gentil na rotina matinal — mesmo apenas cinco minutos de alongamento, uma breve caminhada, ou respiração profunda — desperta seu corpo, aumenta a circulação e envia uma mensagem poderosa de que você valoriza seu bem-estar físico.\nUm café da manhã equilibrado que inclui proteína, gorduras saudáveis e fibra estabiliza seu açúcar no sangue para a manhã, reduz desejos e fornece energia constante. Seja ovos com vegetais, um smoothie com proteína e verduras, ou iogurte com frutas vermelhas e castanhas, nutrir-se pela manhã é um ato de autorrespeito.\nFinalmente, definir uma intenção diária — mesmo algo tão simples como \"Escolho nutrição hoje\" ou \"Vou ouvir meu corpo\" — dá ao seu dia direção e propósito. Essa pequena prática conecta suas ações aos seus objetivos mais profundos e te ajuda a navegar desafios com mais consciência e graça.",
            "keyTakeaways": [
                "Um horário consistente de acordar apoia os ritmos naturais do seu corpo",
                "Hidratar primeiro reidrata o corpo e aumenta o alerta",
                "Movimento matinal gentil desperta o corpo e define um tom positivo",
                "Um café da manhã equilibrado estabiliza o açúcar no sangue e reduz desejos",
                "Definir uma intenção diária alinha suas ações com seus objetivos de bem-estar"
            ],
            "actionStep": "Amanhã de manhã, experimente esta rotina simples: beba um copo cheio de água, alongue por cinco minutos, tome um café da manhã equilibrado e defina uma intenção para o dia. Observe como muda a forma como seu dia se desenrola.",
            "journalPrimary": "Como é sua manhã atual? Se pudesse planejar uma rotina matinal que te fizesse sentir no seu melhor, o que incluiria? Qual pequena mudança poderia fazer começando amanhã?"
        },
    }

def apply_translations(data, translations):
    count = 0
    for lesson in data['lessons']:
        day = lesson['dayNumber']
        if day in translations:
            t = translations[day]
            lesson['content']['introduction'] = t['introduction']
            lesson['content']['mainContent'] = t['mainContent']
            lesson['content']['keyTakeaways'] = t['keyTakeaways']
            lesson['content']['actionStep'] = t['actionStep']
            lesson['journalPrompt']['primary'] = t['journalPrimary']
            count += 1
    return count

if __name__ == '__main__':
    filepath = 'src/i18n/locales/pt/lessons.json'
    with open(filepath, 'r') as f:
        data = json.load(f)
    translations = get_translations()
    count = apply_translations(data, translations)
    with open(filepath, 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Applied {count} translations (Days 61-80)")
