#!/usr/bin/env python3
"""Apply Brazilian Portuguese translations for days 81-100."""
import json

def get_translations():
    return {
        81: {
            "introduction": "Hoje vamos além do número na balança para explorar algo muito mais significativo — sua composição corporal. Entender a diferença entre gordura, músculo, água e osso ajuda você a ver o quadro completo da sua saúde e celebrar progressos que a balança sozinha jamais consegue captar.",
            "mainContent": "Uma das percepções mais libertadoras na jornada de bem-estar é que seu peso é apenas um número — e não um número particularmente informativo. A composição corporal conta uma história muito mais rica. Refere-se às proporções de gordura, músculo, osso e água que compõem seu peso total, e entender essas proporções te dá uma visão muito mais clara da sua saúde e progresso.\nAqui está uma verdade que surpreende muita gente: o tecido muscular é mais denso que o tecido adiposo, o que significa que ocupa menos espaço no corpo enquanto pesa mais na balança. É por isso que duas pessoas podem pesar exatamente o mesmo mas parecer e se sentir completamente diferentes. É também por isso que a balança às vezes fica igual — ou até sobe — enquanto suas roupas ficam mais confortáveis, sua energia melhora e você parece mais tonificada. Você não está falhando; está se transformando.\nFocar em perder gordura enquanto mantém ou constrói músculo magro é muito mais benéfico do que simplesmente tentar fazer o número da balança cair. O tecido muscular é metabolicamente ativo, o que significa que queima mais calorias em repouso que o tecido adiposo. Quanto mais músculo magro você carrega, mais eficientemente seu corpo queima energia ao longo do dia, mesmo dormindo ou sentada. É por isso que atividades de construção de força são uma parte tão valiosa da sua rotina de bem-estar.\nSe está curiosa sobre sua composição corporal, existem várias formas de medi-la. Balanças de bioimpedância, exames DEXA e medições de dobras cutâneas podem fornecer insights úteis. Até ferramentas simples como uma fita métrica — acompanhando cintura, quadris, braços e coxas ao longo do tempo — podem revelar mudanças que a balança perde completamente.\nConsidere usar múltiplas métricas para acompanhar seu progresso: como suas roupas vestem, como se sente, seus níveis de energia, suas medidas e, sim, seu peso também — mas como apenas uma peça de um quebra-cabeça muito maior. Quando libera seu apego a um único número e abraça o quadro maior, sua jornada se torna mais alegre e muito menos frustrante.",
            "keyTakeaways": [
                "A composição corporal importa mais que o peso total",
                "O músculo é mais denso que a gordura, ocupando menos espaço com o mesmo peso",
                "Construir músculo magro aumenta sua taxa metabólica em repouso",
                "Use múltiplas métricas — medidas, como roupas vestem, níveis de energia — não apenas a balança",
                "A balança pode não mudar mesmo quando seu corpo está se transformando lindamente"
            ],
            "actionStep": "Tire suas medidas corporais hoje — cintura, quadris, peito, um braço e uma coxa. Registre-as junto com a data de hoje. Esses números vão contar uma história mais completa do seu progresso ao longo do tempo.",
            "journalPrimary": "Como sua relação com a balança afetou sua jornada de bem-estar? O que mudaria se focasse menos no peso e mais em como seu corpo se sente, se move e aparenta?"
        },
        82: {
            "introduction": "Hoje vamos descobrir uma das ferramentas mais versáteis, acessíveis e eficazes para construir força — as faixas de resistência. Seja iniciante na jornada de movimento ou ativa há anos, essas faixas simples podem transformar sua prática de formas que talvez não esperasse.",
            "mainContent": "Faixas de resistência são faixas elásticas que fornecem tensão quando esticadas, criando resistência contra a qual seus músculos precisam trabalhar. Vêm em vários níveis de resistência — de leve a pesada — e podem ser usadas para praticamente qualquer grupo muscular do corpo. São uma das ferramentas mais subestimadas no mundo do bem-estar, e quando começar a usar, vai entender por que tantas pessoas as amam.\nUma das maiores vantagens das faixas de resistência é a acessibilidade. São leves, portáteis e baratas, perfeitas para treinos em casa, viagens ou adicionar variedade à rotina na academia. Diferente de pesos pesados que podem intimidar ou exigir espaço significativo, um conjunto de faixas cabe em uma gaveta ou mala e pode oferecer um treino de corpo inteiro em qualquer lugar.\nO que torna as faixas únicas é que fornecem tensão constante ao longo de toda a amplitude de movimento. Com pesos livres, frequentemente há pontos no exercício onde a gravidade faz o trabalho por você. Mas com faixas, seus músculos estão engajados do início ao fim, o que pode levar a ativação muscular e construção de força mais eficazes. Essa tensão constante também as torna mais gentis com as articulações, o que é particularmente valioso se está gerenciando alguma preocupação articular.\nFaixas de resistência são maravilhosas para iniciantes porque a resistência é gentil e progressiva — você pode facilmente controlar quanto desafio está criando ajustando o esticamento da faixa. Conforme fica mais forte, simplesmente passa para uma faixa com maior resistência. Para praticantes mais avançadas, as faixas adicionam um tipo diferente de desafio que complementa o treino de força tradicional.\nExistem inúmeros tutoriais gratuitos online que podem guiar você através de treinos com faixas para cada nível e objetivo. De exercícios para parte superior como rosca bíceps e elevação lateral até movimentos de parte inferior como agachamentos e elevação de glúteos, as possibilidades são quase infinitas.",
            "keyTakeaways": [
                "Faixas de resistência são acessíveis, portáteis e eficazes para todos os níveis",
                "Fornecem tensão constante ao longo de cada movimento",
                "São mais gentis com as articulações que pesos tradicionais",
                "Disponíveis em vários níveis de resistência para desafio progressivo",
                "Tutoriais gratuitos online facilitam começar"
            ],
            "actionStep": "Se ainda não tem faixas de resistência, compre um conjunto básico hoje — são bem acessíveis. Se já tem, experimente uma rotina simples de dez minutos de corpo inteiro com elas. Procure um treino para iniciantes com faixas online para te guiar.",
            "journalPrimary": "O que te impediu de atividades de construção de força no passado? Como as faixas de resistência poderiam tornar o treino de força mais acessível e prazeroso para você?"
        },
        83: {
            "introduction": "Viajar é um dos grandes prazeres da vida, mas também pode parecer um desafio na jornada de bem-estar. Hoje vamos explorar estratégias práticas e compassivas para se manter conectada aos seus hábitos saudáveis enquanto está em movimento — porque seu bem-estar não tira férias só porque você tirou.",
            "mainContent": "Viajar — seja a trabalho ou lazer — interrompe suas rotinas normais, e tudo bem. O objetivo não é manter sua rotina exata de casa enquanto está fora; é fazer as melhores escolhas disponíveis enquanto ainda curte a experiência. Com um pouco de planejamento e mentalidade flexível, você pode viajar sem sentir que abandonou seu progresso.\nLevar lanches saudáveis é uma das estratégias de viagem mais simples e eficazes. Aeroportos, postos de gasolina e lobbies de hotel são cheios de opções processadas e ricas em açúcar que te deixam indisposta e insatisfeita. Ter suas próprias castanhas, frutas secas, barras de proteína ou vegetais cortados significa que sempre tem uma opção nutritiva ao alcance, mesmo quando o ambiente não apoia seus objetivos.\nAntes de chegar ao destino, tire alguns minutos para pesquisar suas opções de comida. Procure restaurantes com itens saudáveis no cardápio, mercados perto do hotel onde possa comprar frutas frescas, vegetais e fontes de proteína, e feiras livres se tiver sorte de encontrar uma. Ter um plano flexível remove o estresse de tomar decisões quando está cansada, com fome e cercada por opções desconhecidas.\nMovimento durante viagens não precisa significar encontrar uma academia. Caminhar é uma das melhores formas de explorar um lugar novo mantendo o corpo ativo. Faça tours a pé, passeie por bairros locais, trilhe caminhos próximos, ou simplesmente escolha caminhar em vez de pegar um táxi quando as distâncias são manejáveis.\nManter-se hidratada durante viagens é especialmente importante, particularmente em voos quando o ar reciclado desidrata. Carregue uma garrafa reutilizável e faça da hidratação uma prioridade. E faça o possível para manter seu horário de sono — jet lag e noites tardias podem perturbar seus hormônios de fome e níveis de energia.\nAcima de tudo, seja gentil consigo mesma. Viagem é para ser curtida. Se experimentar uma especialidade local ou pular um treino para explorar, está perfeitamente bem. Uma refeição ou um dia não definem sua jornada.",
            "keyTakeaways": [
                "Leve lanches saudáveis para evitar depender de alimentos processados",
                "Pesquise opções de restaurantes e mercados no destino com antecedência",
                "Caminhe para explorar — é movimento e aventura combinados",
                "Mantenha-se hidratada e priorize o sono o máximo possível",
                "Seja gentil consigo mesma e curta a experiência sem culpa"
            ],
            "actionStep": "Se tem viagem planejada, passe dez minutos pesquisando opções saudáveis de alimentação no destino. Se não tem viagem planejada, crie uma lista de \"kit de bem-estar de viagem\" com lanches saudáveis e itens essenciais para sua próxima aventura.",
            "journalPrimary": "Como costuma lidar com seus hábitos de alimentação e movimento quando viaja? Que estratégias poderiam te ajudar a se sentir mais confiante e preparada para a próxima viagem?"
        },
        84: {
            "introduction": "Inflamação é uma palavra que talvez tenha ouvido com frequência, mas hoje vamos realmente entender o que significa para seu corpo e sua jornada de bem-estar. A inflamação crônica é uma contribuinte silenciosa para o ganho de peso, fadiga e muitos desafios de saúde — e a notícia linda é que o que você come pode ser uma das suas ferramentas mais poderosas para acalmá-la.",
            "mainContent": "A inflamação é a resposta natural do corpo a lesões ou infecções — na verdade é um sinal de que seu sistema imunológico está funcionando. Quando corta o dedo e fica vermelho e inchado, é a inflamação aguda fazendo seu trabalho protetor. O problema surge quando a inflamação se torna crônica — um estado persistente de baixo nível que silenciosamente danifica tecidos, perturba o equilíbrio hormonal e promove armazenamento de gordura, especialmente na região abdominal.\nA inflamação crônica é alimentada por muitos fatores da vida moderna: alimentos processados, açúcares refinados, excesso de álcool, sono ruim, estresse crônico e toxinas ambientais. Com o tempo, esse estado inflamatório contínuo contribui não apenas para ganho de peso, mas para condições como doenças cardíacas, diabetes tipo 2, dor articular e até declínio cognitivo. A boa notícia é que suas escolhas alimentares podem poderosamente mudar o equilíbrio.\nUma abordagem anti-inflamatória à nutrição enfatiza alimentos integrais e ricos em nutrientes que ativamente acalmam a inflamação no corpo. Peixes gordurosos como salmão, sardinha e cavalinha são ricos em ácidos graxos ômega-3, que são potentes agentes anti-inflamatórios. Frutas vermelhas — mirtilo, morango, framboesa — são cheias de antioxidantes que protegem suas células. Folhas verdes como espinafre e couve, azeite extravirgem, castanhas como amêndoas e nozes, e especiarias como cúrcuma e gengibre têm propriedades anti-inflamatórias bem documentadas.\nIgualmente importante é reduzir os alimentos que alimentam a inflamação. Alimentos processados, carboidratos refinados como pão branco e confeitaria, excesso de açúcar, frituras e óleos de sementes altamente processados contribuem para o ciclo inflamatório. Você não precisa eliminar tudo da noite para o dia — até pequenas mudanças em direção a mais alimentos integrais e menos processados podem fazer diferença significativa.\nA beleza da alimentação anti-inflamatória é que os benefícios se estendem muito além do controle de peso. Muitas pessoas relatam melhora na energia, pele melhor, redução de dor articular, pensamento mais claro e humor melhor em poucas semanas. Você não está apenas nutrindo seu corpo — está curando-o de dentro para fora.",
            "keyTakeaways": [
                "A inflamação crônica contribui para ganho de peso, fadiga e doenças",
                "Alimentos anti-inflamatórios incluem peixes gordurosos, frutas vermelhas, folhas verdes, azeite e castanhas",
                "Alimentos processados, açúcares refinados e frituras alimentam a inflamação",
                "Pequenas mudanças alimentares podem criar melhorias significativas",
                "Os benefícios se estendem para energia, pele, humor, saúde articular e clareza cognitiva"
            ],
            "actionStep": "Escolha um alimento anti-inflamatório para adicionar às suas refeições hoje e um alimento inflamatório para reduzir. Por exemplo, adicione uma porção de frutas vermelhas e reduza a ingestão de pão refinado. Pequenas mudanças criam grande impacto.",
            "journalPrimary": "Como a inflamação crônica pode estar afetando seu corpo e sua jornada de bem-estar? Quais alimentos anti-inflamatórios você já gosta, e quais novos tem curiosidade de experimentar?"
        },
        85: {
            "introduction": "Sonhos são lindos, mas metas são o que transformam sonhos em realidade. Hoje vamos aprender sobre metas SMART — um método comprovado que transforma desejos vagos em passos claros e alcançáveis. Quando suas metas são bem definidas, seu caminho adiante se torna infinitamente mais claro e motivador.",
            "mainContent": "Muitas pessoas começam sua jornada de bem-estar com metas como \"Quero ficar saudável\" ou \"Quero perder peso\". Essas intenções são maravilhosas, mas também são vagas — e metas vagas são difíceis de perseguir porque você nunca sabe exatamente o que está buscando ou quando alcançou. Metas SMART mudam isso adicionando estrutura e clareza às suas aspirações.\nSMART significa Específica (Specific), Mensurável (Measurable), Alcançável (Achievable), Relevante (Relevant) e com Prazo (Time-bound). Vamos detalhar cada elemento no contexto da sua jornada de bem-estar. Específica significa que sua meta é clara e definida. Em vez de \"Quero comer melhor\", uma meta específica seria \"Vou comer uma porção de vegetais em cada almoço e jantar\".\nMensurável significa que você pode acompanhar seu progresso. \"Quero me mover mais\" se torna \"Vou caminhar por 30 minutos cinco dias por semana\". Quando pode medir seu progresso, pode celebrar suas vitórias e identificar onde ajustes são necessários. Alcançável significa que sua meta é realista dadas suas circunstâncias atuais. Definir uma meta de correr uma maratona no próximo mês quando não tem caminhado regularmente não é alcançável — mas construir até uma corrida de 5K em três meses pode ser perfeito.\nRelevante significa que sua meta se alinha com seus valores mais profundos e o que realmente importa para você. Se uma meta não se conecta a algo que genuinamente se importa, a motivação vai desaparecer rápido. Pergunte-se: \"Por que essa meta importa para mim? Como se conecta com a vida que quero viver?\" Com Prazo significa que sua meta tem um prazo. \"Um dia\" não é uma linha do tempo. \"Até 31 de março\" te dá urgência e uma linha de chegada.\nAqui está um exemplo de transformar um desejo vago em meta SMART: \"Quero perder peso\" se torna \"Vou perder 5 quilos preparando refeições equilibradas em casa cinco dias por semana e caminhando 30 minutos diariamente nas próximas 12 semanas\". Viu a diferença? Um é um desejo; o outro é um plano.\nEscreva suas metas. Pesquisas mostram consistentemente que pessoas que escrevem suas metas são significativamente mais propensas a alcançá-las. Coloque-as em algum lugar que veja diariamente e revise semanalmente para acompanhar progresso e fazer ajustes.",
            "keyTakeaways": [
                "Metas SMART são Específicas, Mensuráveis, Alcançáveis, Relevantes e com Prazo",
                "Metas vagas levam a resultados vagos — clareza cria ação",
                "Cada meta deve se conectar aos seus valores e motivações mais profundos",
                "Escrever metas aumenta significativamente suas chances de alcançá-las",
                "Revise e ajuste suas metas regularmente conforme progride"
            ],
            "actionStep": "Escreva uma meta SMART para sua jornada de bem-estar. Garanta que atende todos os cinco critérios. Coloque em algum lugar visível — espelho do banheiro, papel de parede do celular, ou primeira página do diário.",
            "journalPrimary": "Qual é uma meta de bem-estar que realmente importa para você agora? Como pode torná-la mais Específica, Mensurável, Alcançável, Relevante e com Prazo?"
        },
        86: {
            "introduction": "Hoje vamos dar um passo — talvez um pouco nervosas — no mundo da exposição ao frio. Embora possa parecer desconfortável, há evidências crescentes de que encontros breves com o frio podem apoiar seu metabolismo, melhorar o humor e até ajudar seu corpo a queimar gordura com mais eficiência. Vamos explorar essa prática fascinante juntas.",
            "mainContent": "A terapia de exposição ao frio tem sido praticada por séculos em várias culturas ao redor do mundo, desde natação no gelo escandinava até rituais japoneses de água fria. Nos últimos anos, a ciência começou a confirmar o que essas tradições há muito sugeriam: exposição breve e controlada ao frio pode ter benefícios notáveis para corpo e mente.\nUm dos benefícios mais empolgantes da exposição ao frio se relaciona a um tipo especial de gordura no corpo chamada tecido adiposo marrom, ou gordura marrom. Diferente da gordura branca, que armazena energia, a gordura marrom queima energia para gerar calor. Quando expõe seu corpo a temperaturas frias, a gordura marrom se ativa para te aquecer, queimando calorias no processo. Exposição regular ao frio pode aumentar a quantidade e atividade de gordura marrom no seu corpo, dando ao metabolismo um impulso natural e gentil.\nA exposição ao frio também dispara a liberação de norepinefrina, um hormônio e neurotransmissor que melhora alerta, foco e humor. Muitas pessoas que praticam exposição regular ao frio relatam se sentir mais energizadas, mentalmente claras e emocionalmente resilientes. É como um café natural para todo o sistema — revigorante sem a agitação ou queda.\nA beleza da exposição ao frio é que você não precisa pular em uma banheira de gelo para experimentar benefícios. Pode começar gentilmente simplesmente terminando seu banho diário com 30 segundos de água fria. Sim, vai ser desconfortável no início — mas foque em respiração lenta e profunda e vai descobrir que seu corpo se adapta mais rápido do que esperava. Com o tempo, pode gradualmente aumentar a duração conforme sua tolerância cresce.\nÉ importante abordar a exposição ao frio com respeito e progressão gradual. Se tem condições cardíacas ou preocupações com pressão arterial, consulte seu profissional de saúde antes de começar. E lembre-se — não é sobre sofrimento ou punição. É sobre gentilmente expandir sua zona de conforto e descobrir do que seu corpo é capaz.",
            "keyTakeaways": [
                "A exposição ao frio ativa a gordura marrom, que queima calorias para gerar calor",
                "Dispara liberação de norepinefrina, melhorando humor e alerta",
                "Comece simplesmente terminando o banho com 30 segundos de água fria",
                "Progrida gradualmente conforme sua tolerância aumenta",
                "Consulte um profissional de saúde se tem preocupações cardíacas ou de pressão"
            ],
            "actionStep": "No final do banho hoje, vire a água para frio por apenas 15-30 segundos. Foque em respiração profunda e lenta. Observe como se sente depois — muitas pessoas experimentam uma onda de energia e alerta.",
            "journalPrimary": "Como se sente sobre sair da sua zona de conforto? Qual é sua reação à ideia de exposição ao frio, e o que isso pode te ensinar sobre sua capacidade de lidar com desconforto em outras áreas da jornada de bem-estar?"
        },
        87: {
            "introduction": "Hoje vamos explorar o mundo maravilhoso dos alimentos fermentados — preparações tradicionais que nutrem seres humanos há milhares de anos. Esses alimentos ricos em probióticos apoiam a saúde intestinal, que por sua vez apoia praticamente todos os aspectos do bem-estar, da digestão e função imunológica ao humor e controle de peso.",
            "mainContent": "A fermentação é um dos métodos mais antigos de conservação de alimentos na história humana, e nossos ancestrais estavam em algo notável. Durante a fermentação, bactérias benéficas quebram açúcares e amidos nos alimentos, criando probióticos — microrganismos vivos que apoiam a saúde do microbioma intestinal. Um microbioma intestinal próspero é essencial para digestão eficiente, absorção de nutrientes, função imunológica e até bem-estar mental.\nAlguns dos alimentos fermentados mais populares e acessíveis incluem kimchi, repolho fermentado coreano apimentado; chucrute, seu primo alemão; missô, uma pasta salgada japonesa feita de soja fermentada; tempeh, proteína de soja fermentada; kefir, bebida de leite fermentado ácida; e iogurte com culturas vivas ativas. Cada um introduz diferentes cepas de bactérias benéficas ao intestino, e por isso variedade é fundamental.\nA conexão entre saúde intestinal e controle de peso é cada vez mais bem documentada. Um microbioma intestinal diverso e equilibrado ajuda a regular hormônios do apetite, apoia metabolismo eficiente, reduz inflamação e até influencia desejos alimentares. Quando o intestino está saudável, o corpo está mais preparado para processar os alimentos que recebe e manter um peso saudável naturalmente.\nSe é nova com alimentos fermentados, comece com quantidades pequenas e aumente gradualmente. Seu intestino precisa de tempo para se ajustar ao influxo de novas bactérias. Comece com uma colher de chucrute junto à refeição, uma porção pequena de iogurte, ou um pouco de kefir no smoothie, e vá construindo a partir daí.\nQualidade importa ao escolher alimentos fermentados. Procure produtos crus, não pasteurizados e que contenham culturas vivas — a pasteurização mata as bactérias benéficas que tornam esses alimentos tão valiosos. Muitos alimentos fermentados também podem ser feitos em casa com ingredientes simples e equipamento mínimo, o que pode ser um projeto divertido e gratificante na cozinha.",
            "keyTakeaways": [
                "Alimentos fermentados são ricos em probióticos que apoiam a saúde intestinal",
                "Um microbioma intestinal saudável apoia controle de peso, imunidade e humor",
                "Inclua uma variedade de alimentos fermentados para bactérias benéficas diversas",
                "Comece com quantidades pequenas e aumente gradualmente",
                "Escolha produtos crus, não pasteurizados, com culturas vivas ativas"
            ],
            "actionStep": "Adicione um alimento fermentado às suas refeições hoje. Experimente uma colher de chucrute no jantar, iogurte com culturas vivas no café da manhã, ou um copo pequeno de kefir como lanche. Observe como sua digestão se sente.",
            "journalPrimary": "Qual é sua relação atual com alimentos fermentados? Já experimentou algum antes? Quais te dão curiosidade, e como poderia incorporá-los à sua rotina de nutrição regular?"
        },
        88: {
            "introduction": "Hoje vamos nos alongar — tanto nossos corpos quanto nossa compreensão do que significa aptidão verdadeira. Flexibilidade é frequentemente o pilar esquecido do bem-estar físico, ofuscado pelo cardio e treino de força. Mas como vai descobrir, manter e melhorar sua flexibilidade é essencial para prevenir lesões, reduzir dor e simplesmente se sentir bem no seu corpo.",
            "mainContent": "Flexibilidade refere-se à amplitude de movimento disponível nas articulações e à capacidade dos músculos de se alongar e se mover em toda sua extensão. Embora possa não parecer tão empolgante quanto outras formas de movimento, manter e melhorar sua flexibilidade é essencial para prevenir lesões, reduzir dor, melhorar desempenho em todos os tipos de atividade e simplesmente se sentir bem no corpo.\nQuando seus músculos estão tensos e articulações rígidas, o corpo compensa alterando padrões de movimento, o que pode levar a tensão, dor e eventualmente lesão. Algo tão simples como alcançar uma prateleira alta ou abaixar para amarrar o sapato se torna mais difícil e potencialmente doloroso. Mantendo boa flexibilidade, você mantém o corpo funcionando como foi projetado, com facilidade e graça.\nO trabalho de flexibilidade também serve como forma poderosa de alívio do estresse. Quando segura um alongamento e foca na respiração, ativa o sistema nervoso parassimpático — o modo \"descansar e digerir\" do corpo. Isso reduz níveis de cortisol, acalma a mente e cria sensação de paz e relaxamento. Muitas pessoas descobrem que uma rotina de alongamento antes de dormir melhora significativamente a qualidade do sono.\nA boa notícia é que melhorar a flexibilidade não exige horas de esforço. Apenas dez minutos de alongamento diário — focando nos grupos musculares principais como isquiotibiais, flexores do quadril, ombros e costas — pode fazer diferença significativa ao longo do tempo. Segure cada alongamento por 20 a 30 segundos, respire profundamente e nunca force o corpo além do que parece confortável. A flexibilidade melhora gradualmente com prática consistente, não com empurrões agressivos.\nConsidere incorporar práticas como yoga, tai chi ou sessões dedicadas de alongamento à sua rotina semanal. Essas não só melhoram a flexibilidade, mas também melhoram consciência corporal, equilíbrio e mindfulness — tudo isso apoia sua jornada geral de bem-estar.",
            "keyTakeaways": [
                "Flexibilidade previne lesões e reduz dor",
                "Alongamento ativa respostas de relaxamento, reduzindo estresse",
                "Apenas dez minutos de alongamento diário fazem diferença significativa",
                "Nunca force um alongamento — trabalhe dentro da sua faixa confortável",
                "Yoga e tai chi são práticas excelentes para construir flexibilidade"
            ],
            "actionStep": "Programe um timer de dez minutos e faça uma rotina gentil de alongamento de corpo inteiro. Foque em pescoço, ombros, costas, quadris, isquiotibiais e panturrilhas. Respire profundamente com cada alongamento e observe como o corpo se sente depois.",
            "journalPrimary": "Onde você carrega mais tensão e rigidez no corpo? Como uma prática regular de flexibilidade poderia mudar como se sente física e emocionalmente?"
        },
        89: {
            "introduction": "Hoje vamos desmistificar um dos números mais importantes na jornada de bem-estar — sua Taxa Metabólica Basal, ou TMB. Entender quantas calorias seu corpo queima simplesmente para te manter viva te dá uma base poderosa para tomar decisões nutricionais informadas e compassivas.",
            "mainContent": "Sua Taxa Metabólica Basal é o número de calorias que seu corpo queima em repouso completo para manter funções básicas de vida — respirar, circular sangue, regular temperatura corporal, crescer e reparar células, e manter órgãos funcionando. Se ficasse na cama o dia todo sem fazer absolutamente nada, a TMB é a energia que seu corpo ainda precisaria apenas para sobreviver. E aqui está o que pode surpreender: a TMB responde por aproximadamente 60 a 70 por cento do total de calorias que queima por dia.\nIsso significa que a vasta maioria do seu gasto energético diário não vem do movimento ou exercício — vem simplesmente de estar viva. Entender isso muda como pensa sobre metabolismo e nutrição. Seu corpo precisa de uma quantidade significativa de energia apenas para funcionar, e comer cronicamente abaixo disso pode prejudicar seu metabolismo sinalizando ao corpo que precisa conservar energia em vez de queimá-la.\nVários fatores influenciam sua TMB. A idade tem papel — o metabolismo naturalmente desacelera com o envelhecimento, parcialmente devido à perda de massa muscular. Peso e altura afetam a TMB, já que corpos maiores requerem mais energia para manter. Massa muscular é fator particularmente importante — tecido muscular é metabolicamente ativo, queimando mais calorias em repouso que tecido adiposo. Essa é uma das razões principais pelas quais construir músculo magro é tão valioso para o metabolismo.\nVocê pode estimar sua TMB usando calculadoras online — a equação de Mifflin-St Jeor é uma das fórmulas mais usadas e precisas. Embora sejam estimativas e não números exatos, fornecem um ponto de partida útil para entender as necessidades energéticas basais do corpo. A partir da TMB, pode considerar seu nível de atividade para determinar seu Gasto Energético Diário Total (GEDT).\nConhecer sua TMB ajuda a evitar duas armadilhas comuns: comer muito pouco, o que pode desacelerar o metabolismo e levar à perda muscular, e comer demais sem consciência. Te empodera a se nutrir adequadamente — combustível suficiente para manter seu fogo metabólico queimando vivamente, enquanto ainda apoia seus objetivos de bem-estar.",
            "keyTakeaways": [
                "A TMB é a energia que seu corpo queima em repouso para manter funções básicas",
                "Responde por 60-70% do gasto calórico diário total",
                "Massa muscular, idade, peso e altura influenciam sua TMB",
                "Calculadoras online podem ajudar a estimar sua TMB",
                "Entender a TMB ajuda a se nutrir adequadamente — nem demais, nem de menos"
            ],
            "actionStep": "Use uma calculadora online de TMB (pesquise \"calculadora TMB Mifflin-St Jeor\") para estimar sua taxa metabólica basal. Anote esse número e reflita sobre o que ele diz sobre as necessidades energéticas do seu corpo.",
            "journalPrimary": "Ficou surpresa com a estimativa da sua TMB? Como saber esse número muda a forma como pensa sobre nutrir seu corpo? Tem comido o suficiente para apoiar seu metabolismo?"
        },
        90: {
            "introduction": "Parabéns, alma linda — você chegou ao final do terceiro mês! Hoje marca uma mudança importante na jornada: sair de uma mentalidade de \"programa\" para um estilo de vida sustentável. Isso não é algo temporário que você está \"seguindo\" — é uma forma de viver que está abraçando para sempre.",
            "mainContent": "Se existe uma lição que engloba tudo que aprendeu até agora, é esta: a abordagem de bem-estar mais eficaz é aquela que você pode manter pelo resto da vida. Restrições temporárias, programas extremos e regras rígidas podem produzir resultados de curto prazo, mas quase sempre levam ao esgotamento, frustração e retorno aos velhos padrões. Transformação verdadeira acontece quando escolhas saudáveis se tornam tão naturais quanto respirar — não porque está se forçando, mas porque são simplesmente parte de quem você é.\nA mudança da \"mentalidade de dieta\" para vida sustentável começa focando em hábitos em vez de restrições. Em vez de pensar no que não pode comer, foque em todos os alimentos nutritivos e deliciosos que pode curtir. Em vez de se punir com treinos exaustivos, encontre formas de movimento que tragam alegria e façam se sentir viva. Quando suas práticas de bem-estar parecem presentes em vez de obrigações, a consistência se torna fácil.\nFlexibilidade é essencial para sustentabilidade. A vida sempre vai apresentar ocasiões que não se alinham perfeitamente com sua rotina de bem-estar — feriados, celebrações, viagens, períodos estressantes. Uma abordagem sustentável inclui esses momentos sem culpa ou pânico. Você curte o bolo de aniversário, o jantar de feriado, o dia preguiçoso de férias — e depois volta aos seus hábitos nutritivos com facilidade porque são sua base natural, não um programa rígido do qual \"caiu\".\nConstruir um ambiente de apoio torna a vida sustentável muito mais fácil. Abasteça sua cozinha com opções nutritivas. Cerque-se de pessoas que apoiam e inspiram seus objetivos. Crie rotinas que naturalmente incorporem escolhas saudáveis. Quando seu ambiente te apoia, precisa de menos força de vontade — e força de vontade é um recurso limitado que não deveria ser sua estratégia principal.\nTire um momento hoje para apreciar o quanto caminhou. Três meses de aprendizado, crescimento e prática de novos hábitos é uma conquista notável. O conhecimento que ganhou, a consciência que desenvolveu e os hábitos que construiu são seus para sempre. Isso não é o fim de nada — é o começo de uma vida inteira de bem-estar, vitalidade e amor-próprio.",
            "keyTakeaways": [
                "Vida sustentável foca em hábitos, não restrições",
                "Flexibilidade permite curtir momentos da vida sem descarrilar o progresso",
                "Um ambiente de apoio reduz a necessidade de força de vontade",
                "Encontre movimento e nutrição que genuinamente goste",
                "Essa é uma transformação de estilo de vida, não um programa temporário"
            ],
            "actionStep": "Escreva uma carta para si mesma descrevendo o estilo de vida que está criando — não a \"dieta\" que está seguindo, mas a forma de viver que está abraçando. Inclua os hábitos que construiu, as mudanças que percebeu e sua visão para os meses à frente.",
            "journalPrimary": "Como sua mentalidade mudou nos últimos três meses? Quais hábitos se tornaram naturais? Como é o \"bem-estar sustentável\" na sua vida única?"
        },
        91: {
            "introduction": "Bem-vinda ao Mês Quatro — um mês dedicado a aprofundar seu conhecimento e refinar sua abordagem. Começamos com um dos grupos alimentares mais extraordinários da natureza: as leguminosas. Feijões, lentilhas e ervilhas são superalimentos humildes que merecem um lugar de destaque no seu plano de nutrição.",
            "mainContent": "Leguminosas — incluindo feijões, lentilhas, grão-de-bico e ervilhas — estão entre os alimentos mais nutritivamente poderosos e economicamente acessíveis do planeta. Culturas ao redor do mundo dependeram de leguminosas como alimentos básicos por milhares de anos, e a ciência nutricional moderna confirma o que dietas tradicionais há muito demonstram: esses alimentos humildes são aliados extraordinários na jornada de bem-estar.\nO que torna as leguminosas tão especiais? Primeiro, são notavelmente ricas tanto em proteína quanto em fibra — uma combinação relativamente rara no mundo alimentar. Uma xícara de lentilhas cozidas fornece cerca de 18 gramas de proteína e 16 gramas de fibra. Essa dupla poderosa promove saciedade profunda e duradoura, ajudando você a se sentir satisfeita por horas após comer. Quando se sente genuinamente satisfeita, é muito menos provável buscar lanches processados ou comer demais na próxima refeição.\nLeguminosas também são excepcionalmente baixas em gordura enquanto ricas em carboidratos complexos que o corpo digere lentamente. Essa digestão lenta mantém o açúcar no sangue estável, prevenindo os picos e quedas que disparam desejos e quedas de energia. Para quem busca gerenciar o açúcar no sangue ou reduzir a dependência de carboidratos refinados, leguminosas são revolucionárias.\nDo ponto de vista prático, leguminosas são uma das fontes mais acessíveis de nutrição de qualidade. Feijões e lentilhas secos custam centavos por porção e podem ser armazenados por meses. São também incrivelmente versáteis — de sopas e ensopados a saladas, pastas como homus e até sobremesas. Feijões em conserva são opção conveniente quando o tempo é curto; basta enxaguá-los para reduzir o sódio.\nSe não está comendo leguminosas regularmente, busque incluir pelo menos uma porção diária. Comece com variedades que goste — talvez feijão-preto em um bowl, lentilhas em uma sopa quentinha, ou grão-de-bico tostado com especiarias como lanche crocante. Se sentir desconforto digestivo, comece com porções menores e aumente gradualmente, conforme suas bactérias intestinais se adaptam à fibra aumentada.",
            "keyTakeaways": [
                "Leguminosas são ricas em proteína e fibra, promovendo saciedade duradoura",
                "Estabilizam o açúcar no sangue com carboidratos complexos de digestão lenta",
                "Extremamente acessíveis e versáteis na culinária",
                "Busque pelo menos uma porção de leguminosas por dia",
                "Comece com porções pequenas se é nova em comê-las regularmente"
            ],
            "actionStep": "Inclua uma porção de leguminosas nas suas refeições hoje. Experimente adicionar feijão-preto a uma salada, fazer uma sopa de lentilha, ou lanchar homus com vegetais. Observe quão satisfeita se sente.",
            "journalPrimary": "Quais leguminosas você curtiu no passado? Como poderia incorporá-las mais regularmente no seu plano de nutrição? Que receitas novas com leguminosas te dão curiosidade?"
        },
        92: {
            "introduction": "Hoje vamos provar que movimento é para todo corpo, em toda situação. Seja trabalhando em uma mesa, tendo desafios de mobilidade, ou simplesmente querendo adicionar mais movimento gentil ao dia, exercícios na cadeira são uma forma eficaz e acessível de manter seu corpo ativo e sua energia alta.",
            "mainContent": "Uma das verdades mais bonitas sobre o movimento é que não exige academia, equipamento especial, ou mesmo a capacidade de ficar de pé por longos períodos. Exercícios na cadeira são treinos eficazes e acessíveis que podem ser feitos por praticamente qualquer pessoa, em qualquer lugar que haja uma cadeira firme. São perfeitos para quem trabalha em escritório sentada por horas, para quem se recupera de lesão, para pessoas com limitações de mobilidade, e para qualquer pessoa que queira adicionar mais movimento ao dia.\nMarchas sentadas são um ponto de partida maravilhoso — simplesmente levante os joelhos alternadamente como se estivesse marchando sentada. Isso faz o sangue fluir, engaja o core e gentilmente eleva a frequência cardíaca. Tente fazer por um a dois minutos para aquecer o corpo e sacudir a rigidez de ficar sentada.\nAgachamentos na cadeira são surpreendentemente eficazes para construir força na parte inferior do corpo. Fique de pé na frente da cadeira, abaixe lentamente como se fosse sentar, toque levemente o assento e levante novamente. Esse movimento engaja quadríceps, glúteos e core. Comece com dez repetições e aumente conforme fica mais forte. A cadeira oferece segurança e confiança, sabendo que está lá se precisar sentar.\nTorções sentadas são excelentes para o core e mobilidade da coluna. Sentada ereta, gire gentilmente a parte superior do corpo para um lado, segure por alguns segundos, depois gire para o outro. Esse movimento ajuda na digestão, alivia tensão nas costas e fortalece os músculos que sustentam a coluna.\nA beleza dos exercícios na cadeira é que podem ser feitos em intervalos curtos ao longo do dia — alguns minutos a cada hora podem reduzir significativamente os efeitos negativos de ficar sentada por muito tempo. Programe um lembrete gentil no celular para fazer uma pausa de movimento, e vai se impressionar com quanto melhor se sente no final do dia.",
            "keyTakeaways": [
                "Exercícios na cadeira são acessíveis para todos os níveis e faixas de mobilidade",
                "Combatem eficazmente os efeitos negativos de ficar sentada por muito tempo",
                "Pausas curtas de movimento ao longo do dia se acumulam significativamente",
                "Não é necessário equipamento especial — apenas uma cadeira firme",
                "Tutoriais online gratuitos guiam rotinas completas de treino na cadeira"
            ],
            "actionStep": "Programe três alarmes ao longo do dia como lembretes para fazer uma pausa de dois minutos de exercícios na cadeira. Experimente marchas sentadas, agachamentos na cadeira ou torções sentadas. Observe como essas pausas breves afetam sua energia e foco.",
            "journalPrimary": "Que oportunidades existem na sua rotina diária para mais movimento, mesmo sentada? Como exercícios regulares na cadeira poderiam mudar como se sente durante o dia de trabalho?"
        },
        93: {
            "introduction": "Hoje vamos explorar um mineral menos conhecido mas importante — o cromo. Esse mineral-traço desempenha um papel fascinante na regulação do açúcar no sangue e pode ajudar a reduzir aqueles desejos persistentes que podem desafiar sua jornada de bem-estar. Vamos descobrir como esse nutriente discreto pode apoiar seus objetivos.",
            "mainContent": "O cromo é um mineral-traço, o que significa que seu corpo precisa em quantidades muito pequenas, mas essas pequenas quantidades podem ter impacto significativo na saúde metabólica. Seu papel principal é melhorar a ação da insulina — o hormônio responsável por mover açúcar do sangue para as células como energia. Quando a insulina funciona eficientemente, o açúcar no sangue fica estável, a energia permanece consistente e aqueles desejos intensos por doces e carboidratos diminuem significativamente.\nPesquisas sugerem que o cromo pode melhorar a sensibilidade à insulina, significando que suas células respondem mais eficazmente aos sinais da insulina. Isso é particularmente relevante para pessoas que experimentam flutuações de açúcar no sangue — quedas de energia à tarde, necessidade repentina e urgente de algo doce, ou dificuldade de se sentir satisfeita após refeições. Quando o açúcar no sangue está estável, fazer escolhas alimentares saudáveis se torna naturalmente mais fácil.\nA melhor forma de obter cromo é através de alimentos integrais. Brócolis é uma das fontes vegetais mais ricas. Uvas, batatas, alho, manjericão e grãos integrais também contêm quantidades significativas. Fontes animais incluem peru, carne bovina e ovos. Comer um plano de nutrição variado baseado em alimentos integrais geralmente fornece cromo adequado para a maioria das pessoas.\nNo entanto, níveis de cromo podem ser esgotados pelo alto consumo de açúcar, estresse e atividade física intensa. Se tem comido uma dieta rica em açúcares refinados e alimentos processados, suas reservas de cromo podem estar mais baixas que o ideal. Conforme transiciona para alimentos mais integrais e nutritivos, sua ingestão de cromo vai melhorar naturalmente.\nAlgumas pessoas consideram suplementação de cromo, particularmente aquelas lidando com resistência à insulina ou desejos persistentes por carboidratos. Embora alguns estudos mostrem resultados promissores, é importante consultar seu profissional de saúde antes de iniciar qualquer suplementação.",
            "keyTakeaways": [
                "O cromo melhora a função da insulina e apoia estabilidade do açúcar no sangue",
                "Açúcar no sangue estável reduz desejos e apoia energia consistente",
                "Fontes alimentares incluem brócolis, uvas, batatas, carnes e grãos integrais",
                "Alto consumo de açúcar e estresse podem esgotar níveis de cromo",
                "Consulte um profissional de saúde antes de considerar suplementos de cromo"
            ],
            "actionStep": "Inclua um alimento rico em cromo nas suas refeições hoje — uma porção generosa de brócolis, uma porção de grãos integrais, ou um pouco de peru. Preste atenção em como seu açúcar no sangue e desejos se sentem ao longo do dia.",
            "journalPrimary": "Experimenta desejos frequentes por doces ou carboidratos? Como a estabilidade do açúcar no sangue poderia mudar suas escolhas alimentares e níveis de energia diários?"
        },
        94: {
            "introduction": "Hoje vamos explorar uma das abordagens mais libertadoras de nutrição que você já encontrou — a alimentação intuitiva. Essa prática te convida a reconstruir a confiança com seu corpo, honrar sua fome e saciedade, e encontrar paz com a comida — tudo isso apoiando seus objetivos de bem-estar.",
            "mainContent": "A alimentação intuitiva é um método desenvolvido pelas nutricionistas Evelyn Tribole e Elyse Resch que te encoraja a se afastar de regras externas sobre comida e em vez disso sintonizar com a sabedoria do próprio corpo. Após anos — às vezes décadas — seguindo vários planos, contando calorias e rotulando alimentos como \"bons\" ou \"ruins\", muitas pessoas perderam contato com a capacidade natural do corpo de regular a alimentação. A alimentação intuitiva é sobre reconectar com essa sabedoria inata.\nO primeiro princípio é rejeitar a mentalidade de dieta — soltar a crença de que existe mais um plano, mais uma restrição que finalmente vai \"funcionar\". Isso não significa abandonar seus objetivos de bem-estar; significa persegui-los de um lugar de autoconfiança em vez de autocontrole. Quando para de lutar contra o corpo e começa a colaborar com ele, algo mágico muda.\nHonrar sua fome é fundamental. Fome não é o inimigo — é a forma do corpo comunicar que precisa de combustível. Quando consistentemente ignora ou suprime a fome, se prepara para desejos intensos e alimentação excessiva depois. Ao responder aos primeiros sinais de fome com comida adequada e nutritiva, mantém o corpo abastecido e a relação com a comida pacífica.\nFazer as pazes com a comida significa dar a si mesma permissão incondicional para comer todos os alimentos. Pode parecer contraintuitivo, mas pesquisas mostram consistentemente que quando alimentos são verdadeiramente permitidos — não apenas tecnicamente permitidos cercados de culpa — seu poder diminui. O efeito do fruto proibido é real: quanto mais restringe um alimento, mais deseja e eventualmente come compulsivamente. Quando todos os alimentos são emocionalmente neutros, pode fazer escolhas baseadas no que realmente nutre e satisfaz.\nSentir sua saciedade é a habilidade complementar de honrar a fome. Envolve pausar durante as refeições para checar com o corpo — percebendo como a comida está, como o estômago se sente, e quando alcançou satisfação confortável. Não é sobre parar em um ponto rígido; é sobre desenvolver consciência e confiança nos sinais do corpo.",
            "keyTakeaways": [
                "A alimentação intuitiva reconstrói a confiança entre você e seu corpo",
                "Rejeitar a mentalidade de dieta não significa abandonar objetivos de bem-estar",
                "Honrar a fome previne o ciclo restringir-comer compulsivamente",
                "Fazer as pazes com a comida reduz o poder dos desejos",
                "Sentir a saciedade se desenvolve através de consciência nas refeições"
            ],
            "actionStep": "Na próxima refeição, pause na metade para checar com seu corpo. Pergunte: \"Quanta fome ainda tenho? Como essa comida está? Estou me aproximando de satisfação confortável?\" Simplesmente observe — sem julgamento necessário.",
            "journalPrimary": "Como seria sua relação com a comida se realmente confiasse no seu corpo? Quais princípios da alimentação intuitiva parecem mais desafiadores — e mais libertadores — para você?"
        },
        95: {
            "introduction": "Hoje vamos sair para cumprimentar o sol da manhã — e descobrir que esse ato simples é uma das coisas mais poderosas que pode fazer pelo metabolismo, humor, sono e bem-estar geral. A luz natural da manhã é um presente gratuito que muitas de nós esquecemos de abrir.",
            "mainContent": "A exposição à luz solar matinal é uma das práticas de bem-estar mais simples, mais naturais e mais subestimadas disponíveis. Quando a luz solar entra nos seus olhos nas primeiras horas do dia, envia sinais poderosos ao cérebro que calibram todo o seu ritmo circadiano — o relógio interno do corpo que regula sono, vigília, fome, metabolismo e produção hormonal.\nSeu ritmo circadiano é essencialmente o maestro da orquestra do corpo, coordenando quando hormônios são liberados, quando sente fome, quando se sente alerta e quando se sente sonolenta. Quando esse ritmo está bem calibrado pela exposição consistente à luz matinal, tudo funciona mais harmoniosamente. O sono melhora, o que impacta diretamente os hormônios de fome e a capacidade do corpo de gerenciar peso. Os níveis de energia ficam mais consistentes. O humor se eleva. Até a digestão funciona mais eficientemente.\nA conexão entre luz matinal e qualidade do sono é particularmente importante para a jornada de bem-estar. Exposição à luz matinal brilhante ajuda o corpo a produzir melatonina — seu hormônio do sono — no momento certo à noite. Sono melhor significa melhor regulação de leptina e grelina (seus hormônios de fome e saciedade), níveis reduzidos de cortisol, melhor sensibilidade à insulina e mais energia para movimento e preparação de refeições saudáveis.\nA luz solar matinal também aumenta a produção de serotonina — o neurotransmissor associado à felicidade e bem-estar. Essa elevação natural do humor pode reduzir alimentação emocional, melhorar motivação e te ajudar a começar cada dia com mentalidade positiva.\nBusque 15 a 30 minutos de exposição à luz solar matinal, idealmente na primeira hora após acordar. Não precisa encarar o sol — simplesmente estar ao ar livre com o rosto exposto à luz natural é suficiente. Combine com uma caminhada matinal, tome o café da manhã ao ar livre, ou simplesmente sente-se perto de uma janela clara. Mesmo em dias nublados, a luz ao ar livre é significativamente mais brilhante que iluminação interna e ainda fornece benefícios significativos.",
            "keyTakeaways": [
                "A luz solar matinal calibra seu ritmo circadiano, melhorando sono e metabolismo",
                "Sono melhor apoia regulação dos hormônios de fome e controle de peso",
                "Luz solar aumenta serotonina, melhorando humor e reduzindo alimentação emocional",
                "Busque 15-30 minutos de luz matinal na primeira hora após acordar",
                "Mesmo luz nublada ao ar livre é muito mais brilhante e benéfica que iluminação interna"
            ],
            "actionStep": "Amanhã de manhã, passe pelo menos 15 minutos ao ar livre na luz natural na primeira hora após acordar. Faça uma caminhada, tome sua bebida matinal ao ar livre, ou simplesmente fique na luz do sol. Observe como afeta seu humor e energia ao longo do dia.",
            "journalPrimary": "Quanta luz solar matinal costuma receber? Como sua energia e humor se comparam em dias que passa tempo ao ar livre de manhã versus dias que não?"
        },
        96: {
            "introduction": "Aqui vai uma percepção fascinante que vai mudar como pensa sobre nutrição: seu corpo realmente queima calorias apenas por digerir comida. Hoje vamos explorar o efeito térmico dos alimentos — e descobrir como escolher os alimentos certos pode dar ao metabolismo um impulso natural a cada refeição.",
            "mainContent": "O efeito térmico dos alimentos, ou ETA, refere-se à energia que seu corpo usa para digerir, absorver e processar os nutrientes das refeições. Toda vez que come, seu metabolismo temporariamente aumenta conforme o corpo trabalha para quebrar alimentos, extrair nutrientes e transportá-los onde são necessários. Esse processo responde por aproximadamente 10 por cento do seu gasto energético diário total — uma porção significativa que muitas pessoas ignoram.\nO que é verdadeiramente fascinante é que macronutrientes diferentes têm efeitos térmicos dramaticamente diferentes. A proteína tem o maior efeito térmico de todos — seu corpo usa 20 a 35 por cento das calorias da proteína apenas para digeri-la e processá-la. Isso significa que se come 100 calorias de proteína, seu corpo queima 20 a 35 dessas calorias durante a digestão. A proteína literalmente custa mais energia ao corpo para processar.\nCarboidratos têm efeito térmico moderado, com cerca de 5 a 15 por cento das calorias queimadas durante a digestão. Carboidratos complexos com fibra tendem a ter efeito térmico maior que carboidratos simples e refinados porque exigem mais trabalho digestivo. Gorduras têm o menor efeito térmico com apenas 0 a 5 por cento — seu corpo processa gordura dietética muito eficientemente, exigindo energia mínima.\nEssa é uma das muitas razões pelas quais priorizar proteína no plano de nutrição é tão valioso. Além do papel na construção e manutenção muscular, saciedade e estabilização do açúcar no sangue, a proteína realmente impulsiona o metabolismo pelo simples ato de digeri-la. Incluir uma fonte de qualidade de proteína em cada refeição e lanche é como adicionar lenha ao seu fogo metabólico ao longo do dia.\nEntender o ETA também ajuda a explicar por que alimentos integrais e não processados tendem a apoiar o controle de peso melhor que alternativas processadas, mesmo quando as contagens calóricas são similares. Alimentos integrais geralmente exigem mais esforço digestivo, produzindo maior efeito térmico.",
            "keyTakeaways": [
                "Seu corpo queima calorias digerindo comida — esse é o efeito térmico dos alimentos",
                "Proteína tem o maior efeito térmico com 20-35% das calorias queimadas durante digestão",
                "Carboidratos queimam 5-15% e gorduras queimam 0-5% durante digestão",
                "Priorizar proteína naturalmente impulsiona o metabolismo",
                "Alimentos integrais não processados têm maior efeito térmico que alimentos processados"
            ],
            "actionStep": "Garanta que cada refeição e lanche hoje inclua uma fonte de proteína de qualidade. Seja ovos no café da manhã, frango no almoço, ou peixe no jantar, priorize proteína e observe quão satisfeita e energizada se sente.",
            "journalPrimary": "Quanta proteína atualmente inclui nas refeições? Sabendo que proteína impulsiona o metabolismo através da digestão, como poderia ajustar sua nutrição para incluir mais?"
        },
        97: {
            "introduction": "Hoje vamos ter uma conversa honesta e compassiva sobre álcool e como afeta seus objetivos de bem-estar. Não é sobre julgamento ou exigir perfeição — é sobre te dar o conhecimento para fazer escolhas conscientes que se alinham com a vida que está criando.",
            "mainContent": "O álcool é profundamente entrelaçado na cultura social, e muitas pessoas o apreciam como parte de celebrações, relaxamento e conexão. Entender como o álcool interage com seu corpo e objetivos de bem-estar permite fazer escolhas conscientes em vez de cair em hábitos que podem não te servir.\nA primeira coisa a entender é que o álcool fornece o que nutricionistas chamam de \"calorias vazias\" — com 7 calorias por grama, fica entre carboidratos (4 calorias por grama) e gordura (9 calorias por grama) na escala energética, mas fornece virtualmente nenhum valor nutricional. Um copo de vinho contém cerca de 120-150 calorias, uma cerveja cerca de 150-200, e um coquetel pode facilmente exceder 300 ou mais, especialmente com mixers açucarados. Essas calorias se acumulam rapidamente, particularmente porque calorias líquidas tendem a não registrar nos sinais de fome — você não se sente \"cheia\" delas como faria com comida.\nMas o impacto calórico é apenas parte da história. Quando consome álcool, seu corpo prioriza metabolizá-lo acima de tudo porque reconhece álcool como toxina. Isso significa que enquanto o fígado está processando álcool, o metabolismo de gorduras, carboidratos e proteínas é essencialmente pausado. A queima de gordura desacelera dramaticamente até o álcool ser totalmente processado. Essa interrupção metabólica pode persistir por horas após a última dose.\nO álcool também prejudica o julgamento e baixa inibições — e isso se estende às escolhas alimentares. Beliscar tarde da noite, porções maiores e buscar alimentos menos nutritivos são comuns após beber. A qualidade do sono também é significativamente afetada; embora o álcool possa ajudar a adormecer inicialmente, perturba os estágios mais profundos do sono essenciais para regulação hormonal, recuperação muscular e saúde metabólica.\nSe escolhe incluir álcool na vida, moderação e atenção são fundamentais. Limite o consumo a ocasiões intencionais e ocasionais em vez de beber diário habitual. Escolha opções com menos calorias quando possível. Mantenha-se hidratada alternando bebidas alcoólicas com água. E mais importante, observe como o álcool realmente te faz sentir — não apenas no momento, mas na manhã seguinte e nos dias que seguem.",
            "keyTakeaways": [
                "O álcool fornece calorias vazias (7 cal/g) sem benefício nutricional",
                "Seu corpo pausa a queima de gordura para priorizar metabolizar o álcool",
                "O álcool prejudica escolhas alimentares e perturba a qualidade do sono",
                "Consumo consciente e ocasional é mais sustentável que eliminação estrita",
                "Mantenha-se hidratada e observe como o álcool realmente afeta seu bem-estar"
            ],
            "actionStep": "Se atualmente consome álcool regularmente, reflita honestamente sobre como está afetando sua energia, sono e progresso de bem-estar. Considere reduzir uma dose esta semana e substituir por uma água com gás refrescante com limão.",
            "journalPrimary": "Que papel o álcool desempenha atualmente na sua vida? Como afeta sua energia, sono e escolhas alimentares? Como seria uma abordagem consciente e intencional do álcool para você?"
        },
        98: {
            "introduction": "Hoje vamos olhar para uma das formas de movimento mais acessíveis, eficazes e completamente gratuitas disponíveis para quase todos — subir escadas. Escadas estão em toda parte e oferecem um treino surpreendentemente poderoso que combina benefícios cardiovasculares com construção de força.",
            "mainContent": "Subir escadas é um movimento que muitas de nós encontramos diariamente mas raramente pensamos como ferramenta de bem-estar. No entanto, escolher as escadas em vez do elevador ou escada rolante é uma das formas mais simples de incorporar atividade física significativa na vida cotidiana — sem academia, sem equipamento especial, sem tempo extra.\nA queima calórica de subir escadas é impressionante. Estudos mostram que subir escadas queima aproximadamente duas a três vezes mais calorias que caminhar em terreno plano no mesmo ritmo. Isso porque subir escadas é essencialmente um movimento vertical — você está levantando todo o peso do corpo contra a gravidade a cada degrau. Isso exige esforço significativo das pernas, glúteos e core, tornando tanto uma atividade cardiovascular quanto de construção de força.\nAlém da queima calórica, subir escadas constrói força funcional nos músculos que usa todos os dias. Quadríceps, isquiotibiais, glúteos e panturrilhas trabalham juntos para te impulsionar a cada degrau. O core se engaja para estabilizar o corpo. Com o tempo, subir escadas regularmente pode melhorar equilíbrio, fortalecer ossos e tornar atividades cotidianas mais fáceis e sem esforço.\nOs benefícios cardiovasculares são igualmente impressionantes. Subir escadas eleva a frequência cardíaca rápida e eficazmente, melhorando saúde do coração e capacidade pulmonar. Pesquisas mostraram que mesmo pequenas quantidades diárias — tão poucas quanto três a cinco lances por dia — podem reduzir significativamente o risco cardiovascular. É uma forma potente de movimento escondida à vista de todos.\nA forma mais simples de incorporar é pela substituição — escolha as escadas em vez do elevador sempre que possível. Se trabalha ou mora em um prédio com escadas, essa única mudança de hábito pode adicionar movimento significativo ao dia sem nenhum compromisso de tempo extra. Conforme seu condicionamento melhora, pode se desafiar subindo dois degraus de cada vez, aumentando o ritmo, ou buscando lances mais longos.",
            "keyTakeaways": [
                "Subir escadas queima duas a três vezes mais calorias que caminhar em terreno plano",
                "Constrói força nas pernas, melhora equilíbrio e fortalece ossos",
                "Até três a cinco lances diários oferecem benefícios cardiovasculares significativos",
                "É gratuito, não exige equipamento e pode ser feito em qualquer lugar com escadas",
                "Simplesmente escolher escadas em vez de elevadores cria um hábito poderoso de movimento diário"
            ],
            "actionStep": "Comprometa-se a usar as escadas toda vez que encontrá-las hoje — no trabalho, no mercado, em casa. Se quer um desafio extra, encontre uma escadaria e suba três a cinco vezes como sessão dedicada de movimento.",
            "journalPrimary": "Onde na sua vida diária poderia substituir escadas por elevadores ou escadas rolantes? Como essa mudança simples poderia adicionar movimento significativo à sua rotina ao longo do tempo?"
        },
        99: {
            "introduction": "Hoje vamos celebrar um dos alimentos mais perfeitos que a natureza tem a oferecer — o humilde ovo. Acessível, versátil, rico em nutrientes e incrivelmente saciante, ovos são uma verdadeira potência para sua jornada de bem-estar. Vamos descobrir por que merecem um lugar de destaque na sua alimentação.",
            "mainContent": "Ovos são um dos alimentos mais eficazes, acessíveis e ricos em nutrientes que pode incluir no plano de nutrição. Por décadas, foram injustamente demonizados por preocupações com colesterol, mas a ciência nutricional moderna reabilitou sua reputação, revelando ovos como um dos alimentos mais completos da natureza.\nUm único ovo grande contém aproximadamente 70 a 80 calorias — um custo calórico notavelmente baixo pela riqueza nutricional que fornece. Cada ovo entrega cerca de 6 gramas de proteína de alta qualidade e completa, significando que contém todos os aminoácidos essenciais que o corpo precisa para reparo muscular, função imunológica e saúde metabólica. Essa proteína é altamente biodisponível — o corpo pode absorver e usar eficientemente.\nA gema, frequentemente temida e descartada, é na verdade onde reside a maioria da magia nutricional. Contém colina — nutriente crítico para metabolismo de gordura, função cerebral e saúde do fígado que a maioria das pessoas não consome o suficiente. A gema também fornece vitaminas A, D, E, B12, riboflavina e folato, junto com minerais como ferro, selênio, fósforo e zinco. Comer ovos inteiros dá dramaticamente mais valor nutricional que apenas claras.\nDe perspectiva de bem-estar, ovos são unicamente saciantes. A combinação de proteína e gorduras saudáveis estabiliza o açúcar no sangue, reduz desejos e fornece energia consistente pela manhã. Estudos mostraram que comer ovos no café da manhã pode reduzir a ingestão calórica ao longo do resto do dia comparado a opções de café da manhã ricas em carboidratos. Literalmente ajudam a comer menos sem tentar.\nA versatilidade dos ovos é incomparável. Mexidos, cozidos, pochê, assados, em omeletes, frittatas ou adicionados a saladas — as possibilidades são infinitas. Cozinham rápido, exigem ingredientes mínimos e combinam bem com vegetais, grãos integrais e outros alimentos nutritivos. E a poucos centavos por ovo, são uma das fontes de proteína de alta qualidade mais economicamente acessíveis.",
            "keyTakeaways": [
                "Ovos são baixos em calorias mas cheios de proteína completa e nutrientes essenciais",
                "A gema contém a maioria das vitaminas, minerais e colina — coma o ovo inteiro",
                "Ovos estabilizam o açúcar no sangue e reduzem desejos ao longo do dia",
                "São incrivelmente versáteis, rápidos de cozinhar e acessíveis",
                "Um dos alimentos mais eficazes e sustentáveis para sua jornada de bem-estar"
            ],
            "actionStep": "Inclua ovos em uma das suas refeições hoje. Experimente uma omelete de vegetais no café da manhã, um ovo cozido como lanche, ou uma frittata no jantar. Saboreie a nutrição e simplicidade desse alimento notável.",
            "journalPrimary": "Com que frequência inclui ovos no plano de nutrição? Quais são suas formas favoritas de prepará-los, e que novas receitas com ovos poderia curtir explorar?"
        },
        100: {
            "introduction": "Hoje é um marco — Dia 100 da sua jornada de bem-estar! Respire fundo, coloque a mão no coração e deixe essa verdade absorver: você apareceu para si mesma cem vezes. Isso é extraordinário. Isso é poderoso. Isso é prova de que você é capaz de muito mais do que jamais imaginou.",
            "mainContent": "Em um mundo que constantemente nos empurra para a próxima meta, o próximo marco, a próxima melhoria, é fácil esquecer o poder incrível de pausar para reconhecer onde está agora. Cem dias de aprendizado, crescimento e prática de novos hábitos não é pouca coisa — é um compromisso profundo consigo mesma, e merece ser celebrado plenamente.\nTire um tempo hoje para revisar sua jornada desde o início. Se tem escrito no diário, leia suas primeiras entradas. Perceba as perguntas que fazia, as dúvidas que carregava, as esperanças que tinha. Agora olhe onde está hoje. Seu conhecimento expandiu enormemente — você entende como seu corpo funciona, o que o nutre, como movê-lo, e como cuidar da mente e emoções. Esse conhecimento é seu para sempre.\nMas conhecimento não é a coisa mais importante que ganhou. Olhe como seus hábitos mudaram. Refeições que antes exigiam esforço tremendo agora podem parecer naturais. Movimento que antes parecia assustador agora pode ser algo que espera com ansiedade. Padrões de pensamento que antes sabotavam seu progresso agora podem ser recebidos com consciência e compaixão. Essas mudanças nos padrões diários são a verdadeira base de transformação duradoura.\nPerceba mudanças além do físico. Sua energia melhorou? Dorme melhor? Se sente mais confiante, mais sintonizada com o corpo, mais compassiva consigo mesma? Lida com estresse diferente? Essas vitórias além da balança são frequentemente mais significativas e duradouras que qualquer número na balança, e merecem ser vistas e celebradas.\nSe se sentir confortável, tire fotos de progresso hoje e compare com fotos do início da jornada. Tire novas medidas e compare com os números iniciais. Mas também — e talvez mais importante — anote as mudanças internas. Como sua relação com a comida evoluiu? Como seu diálogo interno mudou? O que pode fazer agora que não podia há 100 dias? Celebre-se com uma recompensa sem comida que traga alegria: um livro novo, uma massagem, uma trilha na natureza, tempo com alguém querido, ou simplesmente uma tarde de descanso.",
            "keyTakeaways": [
                "Cem dias de compromisso é uma conquista notável que merece ser celebrada",
                "Revise seu diário e perceba o quanto caminhou — em conhecimento, hábitos e mentalidade",
                "Vitórias além da balança são frequentemente os marcadores mais significativos de progresso",
                "Celebre com recompensas sem comida que tragam alegria",
                "Esse marco não é a linha de chegada — é um lindo checkpoint em uma jornada para a vida toda"
            ],
            "actionStep": "Escreva uma lista de pelo menos dez coisas que mudaram para melhor desde o início dessa jornada. Inclua mudanças físicas, mudanças de hábitos, mudanças de mentalidade e qualquer outra coisa que venha à mente. Depois recompense-se com algo que te faz sentir maravilhosa — você mereceu.",
            "journalPrimary": "Olhando para os últimos 100 dias, do que tem mais orgulho? O que te surpreendeu nessa jornada? O que diria para a versão de si mesma que começou no Dia 1?"
        },
    }

def apply_translations(data, translations):
    count = 0
    for lesson in data['lessons']:
        day = lesson['dayNumber']
        if day in translations:
            t = translations[day]
            lesson['content']['introduction'] = t['introduction']
            lesson['content']['mainContent'] = t['mainContent']
            lesson['content']['keyTakeaways'] = t['keyTakeaways']
            lesson['content']['actionStep'] = t['actionStep']
            lesson['journalPrompt']['primary'] = t['journalPrimary']
            count += 1
    return count

if __name__ == '__main__':
    filepath = 'src/i18n/locales/pt/lessons.json'
    with open(filepath, 'r') as f:
        data = json.load(f)
    translations = get_translations()
    count = apply_translations(data, translations)
    with open(filepath, 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Applied {count} translations (Days 81-100)")
