#!/usr/bin/env python3
"""Apply Brazilian Portuguese translations for days 101-120."""
import json

def get_translations():
    return {
        101: {
            "introduction": "Hoje vamos abrir um baú de nutrição — nozes e sementes. Esses alimentos pequenos mas poderosos carregam uma combinação impressionante de gorduras saudáveis, proteína e minerais essenciais que apoiam seu bem-estar de dentro para fora. Vamos explorar como aproveitá-los com sabedoria e abundância.",
            "mainContent": "Nozes e sementes estão entre as fontes mais concentradas de nutrição da natureza. Amêndoas, nozes, pistaches, castanhas de caju, sementes de girassol, de abóbora, de linhaça e de chia — cada uma traz seu perfil único de nutrientes, mas compartilham qualidades comuns que as tornam aliadas excepcionais na jornada de bem-estar.\nGorduras saudáveis são as estrelas das nozes e sementes. São ricas em gorduras monoinsaturadas e poli-insaturadas — os tipos que apoiam saúde cardíaca, função cerebral e produção hormonal. Nozes são particularmente notáveis pelo conteúdo de ômega-3, enquanto amêndoas são ricas em vitamina E. Sementes de linhaça e chia fornecem fibra e ômega-3 de origem vegetal.\nAlém das gorduras saudáveis, nozes e sementes são boas fontes de proteína vegetal e fibra — a combinação mágica que promove saciedade duradoura. Um punhado pequeno como lanche pode manter você satisfeita por horas, tornando-as ferramentas poderosas para gerenciar a fome entre refeições.\nNozes e sementes também são ricas em minerais essenciais como magnésio, zinco, selênio e ferro. Esses minerais apoiam tudo, desde função imunológica e saúde óssea até metabolismo energético e equilíbrio hormonal.\nPorém, a porção importa. Nozes e sementes são densas em calorias — uma porção de 30 gramas (um punhado pequeno) contém cerca de 160-200 calorias. Isso não é motivo para evitá-las, mas é razão para saboreá-las com atenção. Escolha variedades cruas ou tostadas sem sal, sem óleos ou açúcares adicionados. Evite versões cobertas de chocolate ou caramelizadas que adicionam calorias vazias.\nIncorpore nozes e sementes de várias formas: como lanche sozinho, polvilhadas em saladas, misturadas em iogurte ou aveia, adicionadas a refogados, ou moídas em pastas como tahine ou pasta de amendoim. Variedade é fundamental — cada tipo oferece benefícios nutricionais únicos.",
            "keyTakeaways": ["Nozes e sementes são ricas em gorduras saudáveis, proteína e fibra", "Promovem saciedade e apoiam saúde cardíaca, função cerebral e hormônios", "Uma porção de 30 gramas é ideal — cerca de um punhado pequeno", "Escolha variedades cruas ou tostadas sem óleos ou açúcares adicionados", "Inclua uma variedade para a gama mais ampla de benefícios nutricionais"],
            "actionStep": "Meça uma porção de 30 gramas das suas nozes ou sementes favoritas e aproveite como lanche consciente à tarde. Perceba quão satisfatório essa pequena quantidade é quando come devagar e com atenção.",
            "journalPrimary": "Quais nozes e sementes você mais gosta? Como poderia incorporá-las à nutrição diária — como lanches, em saladas, ou como coberturas para refeições?"
        },
        102: {
            "introduction": "E se seu deslocamento diário ou tarefas pudessem servir como prática de movimento? Hoje vamos explorar o transporte ativo — a arte de incorporar atividade física nas jornadas que já está fazendo. É uma das formas mais fáceis de adicionar movimento significativo à vida.",
            "mainContent": "Transporte ativo significa usar sua própria energia física para ir de um lugar a outro — caminhar, pedalar, patinar, ou até correr como parte do deslocamento diário em vez de depender apenas de carros, ônibus ou outras opções motorizadas. É um conceito que foi norma durante a maior parte da história humana, e retornar a ele mesmo parcialmente pode ter impacto profundo na saúde.\nA beleza do transporte ativo é que não exige tempo extra para \"exercício\". Em vez disso, transforma tempo que já está gastando — deslocando, fazendo tarefas, indo a compromissos — em oportunidades de movimento. Caminhar até o mercado, pedalar até o trabalho, ou descer do ônibus dois pontos antes são formas de fazer movimento acontecer naturalmente dentro do dia.\nEstacionar mais longe do destino é uma das estratégias mais simples. Aquelas vagas extras significam minutos extras de caminhada que se acumulam significativamente ao longo da semana. Da mesma forma, escolher escadas em vez de elevadores e caminhar durante ligações telefônicas transformam atividades passivas em oportunidades de movimento.\nReuniões caminhando são outra forma criativa de combinar produtividade com atividade física. Se pode ter uma conversa ao telefone ou com um colega caminhando, está ganhando movimento que de outra forma seria tempo sentada. Muitas pessoas relatam que pensam mais claramente e são mais criativas quando se movem.\nSegurança e praticidade são considerações importantes. Use calçados confortáveis se vai caminhar mais, planeje rotas seguras para ciclismo e considere o clima. Leve roupas extras se necessário. Comece com uma mudança de cada vez e construa conforme se torna confortável.",
            "keyTakeaways": ["Transporte ativo transforma deslocamentos diários em oportunidades de movimento", "Caminhar, pedalar e outros meios autopropulsados não exigem tempo extra", "Estacione mais longe, desça do ônibus antes, ou caminhe distâncias curtas", "Reuniões caminhando melhoram tanto produtividade quanto atividade física", "Pequenas escolhas de transporte ativo se acumulam em movimento diário significativo"],
            "actionStep": "Identifique uma viagem que faz regularmente de carro ou transporte público que poderia ser feita — total ou parcialmente — a pé ou de bicicleta. Experimente hoje ou planeje para esta semana.",
            "journalPrimary": "Onde na sua rotina diária poderia substituir transporte motorizado por caminhada ou ciclismo? O que poderia perceber ou curtir nessas jornadas que perde de dentro de um carro?"
        },
        103: {
            "introduction": "Hoje vamos iluminar o magnésio — um mineral envolvido em mais de 300 reações bioquímicas no corpo, mas que muitas pessoas não consomem o suficiente. Da produção de energia à qualidade do sono, o magnésio é uma potência silenciosa que influencia profundamente sua jornada de bem-estar.",
            "mainContent": "O magnésio é um dos minerais mais importantes do corpo, envolvido na produção de energia, função muscular e nervosa, regulação do açúcar no sangue, controle da pressão arterial e síntese de proteínas. É essencial para literalmente centenas de reações enzimáticas que te mantêm viva e funcionando. No entanto, estudos sugerem que uma porção significativa da população não consome magnésio adequado — tornando-o uma das deficiências nutricionais mais comuns no mundo moderno.\nPara sua jornada de bem-estar especificamente, o papel do magnésio na qualidade do sono é particularmente significativo. O magnésio ajuda a ativar o sistema nervoso parassimpático — o sistema responsável por te acalmar e relaxar. Também regula a melatonina, o hormônio que guia os ciclos de sono-vigília. Magnésio inadequado está ligado a dificuldade para adormecer, sono agitado e insônia — e como já aprendeu, sono ruim sabota praticamente todos os outros aspectos do bem-estar.\nO magnésio também desempenha papel crucial na função muscular e recuperação. Ajuda os músculos a relaxar após contração, o que é por que a deficiência de magnésio frequentemente se manifesta como cãibras, tensão e dores musculares. Se experimenta pernas inquietas à noite ou cãibras frequentes, magnésio inadequado pode ser um fator.\nO estresse esgota as reservas de magnésio, e baixo magnésio amplifica a resposta ao estresse — criando um ciclo vicioso. Garantir magnésio adequado pode ajudar a quebrar esse ciclo, apoiando a capacidade do corpo de gerenciar estresse com mais graça.\nFontes alimentares ricas em magnésio incluem folhas verde-escuras (espinafre, couve), castanhas e sementes (amêndoas, sementes de abóbora, castanha de caju), leguminosas, grãos integrais, abacate e chocolate amargo (sim, chocolate amargo!). Incluir essas fontes regularmente geralmente fornece magnésio adequado para a maioria das pessoas.",
            "keyTakeaways": ["O magnésio está envolvido em mais de 300 processos do corpo, mas muitas pessoas são deficientes", "Apoia a qualidade do sono acalmando o sistema nervoso e regulando melatonina", "Ajuda os músculos a relaxar, recuperar e gerenciar estresse", "Fontes ricas incluem chocolate amargo, abacate, castanhas, folhas verdes e sementes", "Consulte um profissional de saúde se suspeitar de deficiência"],
            "actionStep": "Inclua pelo menos dois alimentos ricos em magnésio nas refeições hoje. Aproveite um punhado de amêndoas, adicione espinafre ao almoço, tenha um pouco de chocolate amargo de sobremesa, ou adicione sementes de abóbora a uma salada.",
            "journalPrimary": "Experimenta sinais que possam sugerir baixo magnésio — cãibras musculares, sono ruim, estresse ou fadiga? Como priorizar alimentos ricos em magnésio poderia melhorar como se sente?"
        },
        104: {
            "introduction": "Feriados, aniversários, reuniões familiares e celebrações são alguns dos momentos mais alegres da vida — e também podem parecer campos minados na jornada de bem-estar. Hoje vamos desenvolver estratégias para navegar essas ocasiões com confiança, prazer e zero culpa.",
            "mainContent": "Ocasiões especiais são parte natural e maravilhosa da vida, e sua jornada de bem-estar deveria melhorar essas experiências, não diminuí-las. O objetivo não é ser \"perfeita\" em cada encontro ou ficar no canto comendo palitos de cenoura enquanto todo mundo celebra. É curtir esses momentos plenamente mantendo equilíbrio geral e autorrespeito.\nUma das estratégias mais eficazes é nunca chegar com fome. Quando aparece faminta em uma celebração, sua força de vontade está no mínimo e tudo parece irresistível. Coma um lanche equilibrado ou refeição pequena antes — algo com proteína e fibra que estabilize o açúcar no sangue e reduza a tendência de comer tudo à vista.\nChegando na celebração, faça uma passagem por toda a mesa antes de se servir. Olhe todas as opções, depois decida conscientemente o que realmente quer curtir. Escolha as coisas que mais apelam — a especialidade caseira da sua avó, a sobremesa favorita — e pule os itens genéricos que estão ali \"só por estar\". Qualidade acima de quantidade.\nPreencha pelo menos metade do prato com vegetais e saladas quando disponíveis. Depois adicione porções moderadas de proteínas e outras comidas que genuinamente deseja. Coma devagar, saboreie cada mordida, e cheque com seu corpo ao longo da refeição.\nLembre-se que celebrações são sobre conexão, não apenas comida. Foque nas conversas, na risada, na alegria de estar com pessoas que ama. Quando o foco muda da comida para a experiência, você naturalmente come com mais atenção e satisfação.\nDepois da celebração, simplesmente volte à sua rotina nutritiva na próxima refeição. Sem compensação, sem punição, sem culpa. Uma refeição celebratória é parte de uma vida bem vivida — não é algo para \"consertar\".",
            "keyTakeaways": ["Nunca chegue a celebrações com fome — coma um lanche equilibrado antes", "Observe todas as opções primeiro, depois escolha o que realmente quer curtir", "Preencha metade do prato com vegetais quando disponíveis", "Foque na conexão e celebração, não apenas na comida", "Volte à rotina nutritiva imediatamente depois — uma refeição não define sua jornada"],
            "actionStep": "Pense na sua próxima celebração ou evento social. Anote três estratégias específicas que vai usar para curtir a ocasião honrando seus objetivos de bem-estar.",
            "journalPrimary": "Como feriados e ocasiões especiais afetaram sua jornada de bem-estar no passado? Que padrões percebe, e que estratégias poderiam te ajudar a navegar com mais confiança e alegria?"
        },
        105: {
            "introduction": "Hoje vamos mergulhar em uma das formas mais completas, gentis e prazerosas de movimento disponíveis — a natação. Seja deslizando em voltas ou simplesmente se movendo na água, nadar oferece benefícios extraordinários para o corpo enquanto é notavelmente gentil com as articulações.",
            "mainContent": "A natação é frequentemente chamada de forma perfeita de atividade física, e não é difícil ver por quê. Oferece treino de corpo inteiro que simultaneamente constrói condicionamento cardiovascular, fortalece músculos por todo o corpo, melhora flexibilidade e queima calorias significativas — tudo enquanto é uma das atividades mais gentis com as articulações. A flutuabilidade da água suporta o peso corporal, reduzindo estresse em ossos, articulações e tecidos conectivos em até 90 por cento.\nIsso torna a natação particularmente valiosa para quem carrega peso extra, tem preocupações articulares, está se recuperando de lesão, ou simplesmente prefere movimento gentil que não martela o corpo. Na água, todos os corpos são leves, e todos os movimentos são amortecidos.\nA queima calórica é impressionante: dependendo da intensidade e do estilo de nado, nadar pode queimar entre 400 e 700 calorias por hora. Até nadar de forma recreativa queima significativamente mais calorias que muitas atividades terrestres porque a água fornece resistência natural em todas as direções.\nA natação trabalha quase todos os grupos musculares principais simultaneamente. Braços, pernas, core, costas e ombros todos se engajam com cada braçada e chute. Isso constrói músculo magro por todo o corpo, melhorando tanto força quanto definição enquanto aumenta sua taxa metabólica em repouso.\nA qualidade meditativa da natação não deve ser subestimada. O som rítmico da água, o foco na respiração e a desconexão das distrações terrestres criam um estado quase meditativo que reduz estresse, acalma a mente e melhora o bem-estar emocional.\nSe não é nadadora confiante, não se preocupe — exercícios na água como hidroginástica fornecem muitos dos mesmos benefícios sem exigir habilidades de nado. Muitos centros comunitários oferecem aulas para todos os níveis.",
            "keyTakeaways": ["Natação é treino de corpo inteiro excepcionalmente gentil com articulações", "Queima 400-700 calorias por hora dependendo da intensidade e estilo", "A água fornece resistência natural, construindo músculo magro por todo o corpo", "É adequada para todos os níveis, idades e tipos de corpo", "A qualidade meditativa da natação reduz estresse e promove bem-estar mental"],
            "actionStep": "Se tem acesso a uma piscina ou corpo d'água, planeje uma sessão de natação esta semana. Se natação não está acessível, considere alternativas aquáticas como hidroginástica em um centro comunitário.",
            "journalPrimary": "Qual é sua relação com natação ou atividades aquáticas? Se gosta da água, como poderia incorporá-la na rotina de bem-estar? Se água não é sua praia, que outras opções de movimento de baixo impacto te atraem?"
        },
        106: {
            "introduction": "Hoje vamos mergulhar em uma condição que afeta milhões de pessoas e impacta significativamente o controle de peso — a resistência à insulina. Entender o que é, por que se desenvolve e como abordar pode ser uma das coisas mais empoderadoras que aprende na jornada de bem-estar.",
            "mainContent": "A insulina é um hormônio produzido pelo pâncreas que age como uma chave, destrancando suas células para que possam absorver açúcar (glicose) do sangue e usá-lo como energia. Em um sistema saudável, você come, o açúcar no sangue sobe, insulina é liberada, as células absorvem a glicose, e o açúcar no sangue volta ao normal. É uma dança lindamente coordenada.\nA resistência à insulina ocorre quando suas células começam a ignorar os sinais da insulina — as fechaduras enferrujam, e a chave não funciona tão bem. O pâncreas responde produzindo ainda mais insulina, tentando forçar as células a abrir. Por um tempo, essa insulina extra funciona, mas eventualmente o sistema fica sobrecarregado.\nAs consequências são significativas para o controle de peso. Quando os níveis de insulina estão cronicamente altos, seu corpo está em modo constante de armazenamento de gordura — particularmente ao redor do abdômen. Altos níveis de insulina também tornam muito difícil para o corpo acessar gordura armazenada para energia, o que é por que pessoas com resistência à insulina frequentemente acham que perder peso parece impossível mesmo quando estão \"fazendo tudo certo\".\nA boa notícia é que a resistência à insulina é altamente responsiva a mudanças de estilo de vida. Reduzir carboidratos refinados e açúcares adicionados é uma das intervenções mais eficazes. Quando come menos dos alimentos que causam picos rápidos de açúcar, o pâncreas produz menos insulina, e suas células gradualmente começam a responder a ela novamente.\nMovimento regular melhora significativamente a sensibilidade à insulina. Quando os músculos se contraem durante o exercício, absorvem glicose do sangue mesmo sem insulina — é como encontrar uma porta dos fundos para as células. Até uma caminhada de 15 minutos após refeições pode fazer diferença mensurável.\nSono e gerenciamento de estresse também desempenham papéis cruciais. Sono ruim e estresse crônico elevam cortisol, o que piora a resistência à insulina. Priorizar ambos cria um ciclo positivo de melhoria.",
            "keyTakeaways": ["Resistência à insulina significa que as células não respondem adequadamente aos sinais da insulina", "Promove armazenamento de gordura, especialmente ao redor do abdômen, e resiste à perda de peso", "Reduzir carboidratos refinados e açúcar é uma das intervenções mais eficazes", "Movimento regular melhora significativamente a sensibilidade à insulina", "Sono, gerenciamento de estresse e perda de peso criam um ciclo positivo de melhoria"],
            "actionStep": "Olhe suas refeições hoje pela lente da estabilidade do açúcar no sangue. Escolha carboidratos complexos em vez de refinados, inclua proteína e gordura saudável em cada refeição, e observe como sua energia e desejos respondem.",
            "journalPrimary": "Experimentou sinais que possam sugerir resistência à insulina — gordura abdominal teimosa, fadiga após refeições, desejos intensos por carboidratos? Como entender essa condição muda sua abordagem à nutrição?"
        },
        107: {
            "introduction": "Hoje vamos nutrir algo que pode parecer distante do bem-estar físico mas está profundamente conectado — a gratidão. Uma mentalidade grata não apenas faz bem; ativamente apoia sua saúde, seus hábitos e toda a jornada de bem-estar de formas poderosas e respaldadas pela ciência.",
            "mainContent": "Gratidão é mais que uma emoção agradável ou cortesia social — é uma prática com efeitos mensuráveis no cérebro, corpo e comportamento. Pesquisas de instituições líderes mostraram que prática regular de gratidão pode reduzir hormônios do estresse, melhorar qualidade do sono, diminuir inflamação, fortalecer função imunológica e até influenciar escolhas alimentares. Quando sente gratidão genuína, seu corpo responde com bioquímica que apoia o bem-estar.\nA conexão entre gratidão e sua jornada de bem-estar é profunda. Quando aborda seu corpo com gratidão — apreciando o que ele pode fazer em vez de criticando o que não pode — naturalmente faz escolhas mais cuidadosas e respeitosas. É difícil abusar de algo que genuinamente aprecia. As pessoas que veem seus corpos como presentes a serem cuidados em vez de problemas a serem consertados tendem a se nutrir melhor, se mover com mais alegria e tratar a si mesmas com mais compaixão.\nUm diário de gratidão é uma das práticas mais simples e eficazes. Cada noite, escreva três a cinco coisas pelas quais é grata — incluindo pelo menos uma relacionada ao corpo ou saúde. Com o tempo, essa prática literalmente reconfigura seu cérebro para perceber mais positivos na sua vida e jornada, criando um ciclo ascendente de apreciação e motivação.\nGratidão específica ao corpo é particularmente poderosa. Em vez de \"odeio minhas coxas\", tente \"sou grata por minhas pernas que me carregam por cada dia\". Em vez de focar no que a balança diz, aprecie que seu coração bate sem você precisar pensar nisso. Essa mudança de perspectiva transforma sua relação com o corpo de adversarial para cooperativa.\nApreciar pequenos progressos reforça hábitos positivos. Quando reconhece e agradece pelos passos que deu — uma boa refeição, uma caminhada, um copo extra de água — está reforçando os circuitos neurais que tornam esses comportamentos mais naturais e automáticos.",
            "keyTakeaways": ["Prática de gratidão reduz estresse, melhora sono e apoia função imunológica", "Abordar o corpo com gratidão promove escolhas cuidadosas e respeitosas", "Um diário diário de gratidão reconfigura o cérebro para positividade", "Gratidão específica ao corpo melhora sua relação com o corpo físico", "Apreciar pequenos progressos reforça hábitos positivos"],
            "actionStep": "Comece uma prática de gratidão esta noite. Antes de dormir, escreva cinco coisas pelas quais é grata — incluindo pelo menos duas relacionadas ao corpo ou jornada de bem-estar. Observe como essa prática afeta seu humor e sono.",
            "journalPrimary": "Por quais aspectos do seu corpo e saúde é genuinamente grata agora? Como uma prática diária de gratidão poderia mudar sua abordagem geral ao bem-estar?"
        },
        108: {
            "introduction": "Seu cérebro é o órgão mais extraordinário do corpo — e está faminto por gordura. Hoje vamos explorar a conexão vital entre gorduras saudáveis na dieta e função cerebral, e descobrir por que incluir gorduras de qualidade no plano de nutrição apoia não apenas o corpo, mas mente, humor e clareza cognitiva.",
            "mainContent": "Seu cérebro é aproximadamente 60 por cento gordura, tornando-o o órgão mais gordo do corpo. Faz sentido, então, que a qualidade da gordura que come influencie diretamente quão bem o cérebro funciona. Por décadas, dietas com pouca gordura foram promovidas como caminho para saúde, mas agora entendemos que o cérebro — e o corpo inteiro — precisa de gorduras saudáveis adequadas para prosperar. A chave é escolher os tipos certos.\nÁcidos graxos ômega-3 estão entre as gorduras mais importantes para saúde cerebral. Encontrados abundantemente em peixes gordurosos como salmão, sardinha e cavalinha, assim como em nozes, linhaça e sementes de chia, os ômega-3 desempenham papéis cruciais na estrutura das membranas das células cerebrais, comunicação entre neurônios e proteção contra declínio cognitivo. Pesquisas ligam consumo adequado de ômega-3 a melhora na memória, humor mais estável e risco reduzido de depressão e ansiedade.\nAbacate é outro amigo poderoso do cérebro. Rico em gorduras monoinsaturadas, apoia fluxo sanguíneo saudável ao cérebro — e melhor fluxo sanguíneo significa melhor entrega de oxigênio e nutrientes. Azeite extravirgem oferece benefícios similares e contém polifenóis que protegem as células cerebrais do dano oxidativo.\nDe uma perspectiva de bem-estar, gorduras saudáveis também aumentam a saciedade. Porque gordura é digerida lentamente, incluí-la nas refeições te mantém satisfeita por mais tempo, reduz fome entre refeições e estabiliza o açúcar no sangue. Essa satisfação duradoura ajuda a fazer melhores escolhas alimentares ao longo do dia.\nO equilíbrio é importante. Embora gorduras saudáveis sejam essenciais, são densas em calorias — 9 calorias por grama comparado a 4 para proteína e carboidratos. Porções conscientes — um quarto de abacate, uma colher de azeite, um punhado de nozes — fornecem todos os benefícios sem exceder as necessidades calóricas.",
            "keyTakeaways": ["Seu cérebro é 60% gordura e precisa de gordura na dieta para funcionar otimamente", "Ácidos graxos ômega-3 apoiam memória, humor e proteção cognitiva", "Abacate e azeite promovem fluxo sanguíneo saudável ao cérebro", "Gorduras saudáveis aumentam saciedade, reduzindo fome e desejos", "Inclua uma fonte de gordura de qualidade em cada refeição sendo consciente das porções"],
            "actionStep": "Inclua uma fonte de gordura saudável em cada refeição hoje — abacate no café, azeite na salada do almoço, e uma porção de peixe gordo ou castanhas no jantar. Observe quão satisfeita e mentalmente clara se sente.",
            "journalPrimary": "Quanta gordura saudável atualmente inclui nas refeições? Quais fontes de gordura saudável mais gosta, e como poderia incluir mais variedade?"
        },
        109: {
            "introduction": "Hoje vamos abordar uma pergunta que muitas pessoas carregam silenciosamente: \"Meu peso é determinado pelos meus genes?\" A resposta é nuançada, empoderadora e ultimamente esperançosa. Embora a genética influencie as tendências do corpo, ela não determina seu destino. Você tem muito mais poder do que imagina.",
            "mainContent": "A genética desempenha um papel real na relação do corpo com o peso. Pesquisas identificaram numerosos genes que influenciam fatores como metabolismo, apetite, padrões de armazenamento de gordura e até preferências alimentares. Algumas pessoas são geneticamente predispostas a metabolismo mais rápido, enquanto outras tendem a armazenar gordura mais facilmente. Algumas naturalmente têm sinais de fome mais fortes, enquanto outras se saciam mais facilmente. Essas diferenças genéticas são reais, e reconhecê-las pode reduzir a autoculpa e frustração que frequentemente acompanham a jornada de bem-estar.\nNo entanto — e isso é crucial — a genética influencia tendências, mas não determina resultados. Os cientistas frequentemente usam a analogia de um revólver carregado: seus genes carregam a arma, mas seu estilo de vida puxa o gatilho. Ter uma predisposição genética para ganho de peso não significa que ganhar peso é inevitável — significa que suas escolhas de estilo de vida são ainda mais importantes.\nA ciência da epigenética revelou algo notável: seus hábitos diários realmente influenciam como seus genes se expressam. Exercício regular, nutrição equilibrada, sono adequado e gerenciamento de estresse podem literalmente desligar genes que promovem armazenamento de gordura e ligar genes que apoiam metabolismo saudável. Você pode não ser capaz de mudar seus genes, mas pode mudar significativamente como eles operam.\nIsso significa que comparação com outros é fundamentalmente injusta — e não muito útil. Sua amiga que parece comer o que quiser sem ganhar peso tem uma composição genética diferente, um histórico metabólico diferente e provavelmente desafios que você não vê. Seu único referência significativo é você mesma — quem era ontem, na semana passada, no mês passado.\nFoque no que pode controlar: como nutre seu corpo, como se move, como dorme, como gerencia estresse e como fala consigo mesma. Essas escolhas têm impacto muito maior nos resultados do que sua genética — e são inteiramente suas para fazer.",
            "keyTakeaways": ["Genética influencia tendências de peso, metabolismo e apetite", "Genes não determinam seu destino — escolhas de estilo de vida moldam resultados", "Epigenética mostra que hábitos diários influenciam como genes se expressam", "Preste atenção em como seu corpo único responde a diferentes abordagens", "Foque no que pode controlar: hábitos, ambiente, mentalidade e escolhas diárias"],
            "actionStep": "Em vez de comparar seu progresso com o de outra pessoa hoje, foque no feedback do próprio corpo. Observe quais alimentos te dão energia, qual movimento parece bom e quais rotinas apoiam seu bem-estar. Honre seu projeto único.",
            "journalPrimary": "Já culpou a genética por dificuldades na jornada de bem-estar? Como entender que genes influenciam mas não determinam resultados muda sua perspectiva e motivação?"
        },
        110: {
            "introduction": "Ao fechar o Mês Quatro, vamos fortalecer algo que pode ser o músculo mais importante na jornada de bem-estar — sua resiliência mental. A capacidade de enfrentar contratempos, adaptar-se a desafios e continuar avançando com graça é o que separa quem transforma a vida de quem desiste. E como qualquer habilidade, resiliência pode ser construída.",
            "mainContent": "Resiliência mental não é sobre ser durona, nunca lutar ou empurrar através da dor com dentes cerrados. Resiliência verdadeira é a capacidade de se curvar sem quebrar — enfrentar dificuldades, experimentar a gama completa de emoções que trazem, e depois encontrar o caminho de volta para sua rota. É a capacidade de ver contratempos como temporários, como informação, e como oportunidades de crescimento em vez de evidência de fracasso.\nNa jornada de bem-estar, contratempos não são apenas possíveis — são inevitáveis. Você terá dias que comerá demais. Terá semanas que o movimento vai embora. Enfrentará platôs, estresse, doença, viagens, mudanças de vida e momentos em que a motivação simplesmente desaparece. Essas não são falhas — são a experiência humana normal. O que importa não é se você cai, mas como se levanta.\nConstruir uma rede de apoio é uma das formas mais poderosas de fortalecer resiliência. Ter pessoas que te encorajam, te ouvem sem julgamento e te lembram do quanto já caminhou pode fazer a diferença entre desistir e continuar. Isso pode ser uma amiga, familiar, treinadora, terapeuta ou comunidade online — qualquer pessoa que te apoie genuinamente.\nAutocompaixão é outro pilar da resiliência. Pesquisas mostram que pessoas que tratam a si mesmas com gentileza após contratempos se recuperam mais rápido e têm melhor desempenho do que aquelas que se criticam. Fale consigo mesma como falaria com uma amiga querida que estivesse lutando — com calor, encorajamento e compreensão.\nCada vez que se levanta após uma queda, sua resiliência fica mais forte. Cada contratempo superado se torna evidência de que pode lidar com desafios. Com o tempo, desenvolve uma confiança profunda na própria capacidade de navegar o que quer que a vida traga — e essa confiança é um dos maiores presentes da jornada de bem-estar.",
            "keyTakeaways": ["Resiliência é a capacidade de enfrentar contratempos e voltar ao caminho com graça", "Veja contratempos como oportunidades de aprendizado, não evidência de fracasso", "Construa uma rede de apoio de pessoas que encorajam seu crescimento", "Pratique autocompaixão — acelera a recuperação e melhora o desempenho", "Cada vez que se levanta após cair, sua resiliência fica mais forte"],
            "actionStep": "Pense em um contratempo recente na jornada de bem-estar. Em vez de se julgar, escreva três coisas que aprendeu com a experiência e uma coisa que fará diferente da próxima vez. Pratique responder com curiosidade em vez de crítica.",
            "journalPrimary": "Como tipicamente responde a contratempos — com autocrítica ou autocompaixão? O que mudaria se visse cada tropeço como degrau em vez de fracasso? Em quem poderia se apoiar para apoio em momentos desafiadores?"
        },
        111: {
            "introduction": "Bem-vinda ao Mês Cinco — Dominando Sua Abordagem. Começamos com uma família de vegetais que verdadeiramente merece o título de \"superalimento\": vegetais crucíferos. Brócolis, couve-flor, repolho, couve-de-bruxelas, couve e rúcula são potências nutricionais com benefícios notáveis para sua jornada de bem-estar.",
            "mainContent": "Vegetais crucíferos recebem seu nome da forma de cruz das suas flores, e são uma das famílias de vegetais mais estudadas e celebradas na ciência nutricional. Brócolis, couve-flor, repolho, couve-de-bruxelas, couve, rúcula, bok choy e rabanete são todos membros desta família impressionante.\nO que torna os crucíferos especiais é seu conteúdo único de compostos chamados glucosinolatos. Quando você mastiga, pica ou cozinha esses vegetais, os glucosinolatos se decompõem em compostos bioativos incluindo sulforafano, que pesquisas mostram ter poderosas propriedades anti-inflamatórias e até anticancerígenas. Esses compostos apoiam os sistemas naturais de desintoxicação do corpo e podem ajudar a proteger contra danos celulares.\nPara o controle de peso especificamente, crucíferos são aliados extraordinários. São extremamente baixos em calorias — uma xícara inteira de brócolis picado tem apenas 31 calorias — enquanto sendo ricos em fibra e água, o que significa que enchem seu estômago e satisfazem por muito poucas calorias. Esse volume é chave para se sentir satisfeita enquanto mantém déficit calórico.\nCrucíferos também apoiam saúde hormonal. Contêm um composto chamado indol-3-carbinol (I3C) que ajuda o corpo a metabolizar estrogênio de forma mais eficaz. O equilíbrio hormonal desempenha papel significativo no controle de peso, particularmente para mulheres, e apoiar metabolismo saudável de estrogênio através da alimentação é uma estratégia gentil mas poderosa.\nPara maximizar benefícios, coma crucíferos tanto crus quanto cozidos ao longo da semana. Mastigar legumes crus maximiza a formação de sulforafano, enquanto cozinhar levemente no vapor torna alguns nutrientes mais biodisponíveis. Evite cozinhar demais, que pode destruir os compostos benéficos e tornar os vegetais sem graça.\nBusque pelo menos uma porção de vegetais crucíferos diariamente. Adicione brócolis ao refogado, couve em smoothies, repolho em saladas, ou couve-de-bruxelas assadas como acompanhamento.",
            "keyTakeaways": ["Vegetais crucíferos contêm glucosinolatos únicos com propriedades anti-inflamatórias", "São extremamente baixos em calorias enquanto ricos em fibra — perfeitos para saciedade", "Apoiam desintoxicação natural e metabolismo hormonal saudável", "Coma tanto crus quanto levemente cozidos para máximo benefício", "Busque pelo menos uma porção diária de vegetais crucíferos"],
            "actionStep": "Adicione um vegetal crucífero a pelo menos duas refeições hoje. Brócolis cozido no vapor com o almoço, couve em um smoothie, ou couve-de-bruxelas assadas no jantar são opções deliciosas que apoiam seus objetivos de bem-estar.",
            "journalPrimary": "Quais vegetais crucíferos você gosta atualmente? Existem alguns que nunca experimentou? Como poderia incorporar mais desses superalimentos poderosos nas refeições diárias?"
        },
        112: {
            "introduction": "Hoje vamos aumentar o volume da música e descobrir uma das formas mais alegres, eficazes e revigorantes de movimento disponíveis — a dança. Quando o movimento parece celebração em vez de obrigação, tudo muda. Vamos descobrir por que dançar é uma ferramenta surpreendentemente poderosa na sua jornada de bem-estar.",
            "mainContent": "Dançar é uma das formas mais antigas de expressão humana, e acontece que também é uma das mais eficazes para apoiar bem-estar. O que torna a dança diferente de outras formas de exercício é sua capacidade de transcender o físico — ela conecta corpo, mente e espírito de formas que um treino de academia ou corrida simplesmente não conseguem.\nDo ponto de vista físico, dançar é um treino surpreendentemente completo. Dependendo do estilo e intensidade, pode queimar entre 200 e 600 calorias por hora. Mas além da queima calórica, dança melhora coordenação, equilíbrio, flexibilidade e resistência cardiovascular. Seus músculos são desafiados em múltiplos planos de movimento — não apenas frente e trás como em muitos exercícios convencionais.\nA liberação de endorfinas durante a dança é notavelmente poderosa. A combinação de movimento, música e expressão cria uma onda de químicos de bem-estar que pode melhorar o humor por horas após a sessão. Muitas pessoas relatam que dançar é o exercício mais eficaz que já encontraram para reduzir estresse e ansiedade.\nVocê não precisa ser \"boa\" em dança para colher os benefícios. Dançar sozinha na sua sala é tão eficaz para sua saúde quanto uma aula formal de dança. O corpo não sabe a diferença — ele apenas sabe que está se movendo, se expressando e curtindo. Ligue sua música favorita e deixe o corpo se mover como quiser.\nSe quer mais estrutura, explore as inúmeras opções disponíveis. Zumba, salsa, forró, dança de salão, hip hop, dança do ventre — cada estilo oferece seus próprios benefícios e culturas. Muitas aulas estão disponíveis online gratuitamente, então pode experimentar no conforto e privacidade do seu lar.\nDança é também uma atividade profundamente social. Aulas de dança, noites de dança e eventos sociais criam comunidade e conexão — elementos que já aprendeu serem cruciais para o sucesso na jornada de bem-estar.",
            "keyTakeaways": ["Dançar queima 200-600 calorias por hora dependendo do estilo e intensidade", "Melhora coordenação, equilíbrio, flexibilidade e saúde cardiovascular", "A combinação de música e movimento libera endorfinas poderosas", "Você não precisa ser \"boa\" — qualquer movimento com música conta", "Dançar pode ser social ou solo, em casa ou em aula"],
            "actionStep": "Coloque sua música favorita e dance livremente por pelo menos dez minutos hoje. Feche as cortinas se quiser privacidade e simplesmente deixe o corpo se mover. Observe como se sente durante e depois — a alegria pode te surpreender.",
            "journalPrimary": "Qual é sua relação com dançar? Quando foi a última vez que dançou livremente, sem se importar com como parecia? Como dançar poderia se tornar parte regular da sua prática de bem-estar?"
        },
        113: {
            "introduction": "Às vezes nosso corpo tenta nos dizer algo, e hoje vamos aprender a ouvir. A abordagem da dieta de eliminação é uma forma sistemática de identificar alimentos que podem estar causando inflamação, desconforto digestivo ou outros sintomas que dificultam seu progresso. É uma ferramenta poderosa de autoconhecimento.",
            "mainContent": "A dieta de eliminação não é mais uma dieta da moda ou programa de perda de peso — é uma ferramenta de diagnóstico usada por profissionais de saúde para identificar sensibilidades alimentares individuais. A premissa é simples: remova os alimentos que mais comumente causam reações, deixe seu corpo se acalmar, e depois reintroduza-os um de cada vez para observar como seu corpo responde.\nOs alimentos mais comumente eliminados incluem glúten, laticínios, ovos, soja, milho, amendoim, açúcar adicionado, álcool e alimentos altamente processados. Esses são removidos por um período de duas a quatro semanas — tempo suficiente para que a inflamação diminua e os sintomas se resolvam se um desses alimentos é o causador.\nA fase de reintrodução é onde a magia acontece. Você adiciona de volta um alimento de cada vez, esperando três a quatro dias entre cada reintrodução. Durante esse período, observa cuidadosamente quaisquer sintomas: inchaço, dor abdominal, fadiga, dores de cabeça, alterações de pele, mudanças de humor ou problemas digestivos. Se sintomas retornam com um alimento específico, você encontrou um gatilho.\nÉ importante abordar uma eliminação com orientação — idealmente com apoio de um nutricionista ou profissional de saúde que possa garantir que você mantenha nutrição adequada durante a fase de eliminação e interpretar seus resultados adequadamente.\nSensibilidades alimentares são diferentes de alergias alimentares. Alergias causam respostas imunológicas imediatas e podem ser perigosas. Sensibilidades são reações mais sutis que podem se manifestar horas ou até dias após consumo, tornando-as difíceis de identificar sem uma abordagem sistemática.\nDescobrir suas sensibilidades alimentares individuais pode ser revolucionário para a jornada de bem-estar. Muitas pessoas relatam melhora dramática em energia, digestão, clareza mental e até facilidade de perder peso após identificar e reduzir alimentos problemáticos.",
            "keyTakeaways": ["A dieta de eliminação é ferramenta de diagnóstico, não dieta da moda", "Remova alimentos comuns por 2-4 semanas, depois reintroduza um por vez", "Observe cuidadosamente os sintomas durante a fase de reintrodução", "Trabalhe com um profissional de saúde para orientação e segurança", "Identificar sensibilidades alimentares pode melhorar dramaticamente energia e digestão"],
            "actionStep": "Se experimenta sintomas digestivos, fadiga ou inflamação persistentes, considere conversar com um profissional de saúde sobre uma dieta de eliminação orientada. Enquanto isso, comece a perceber como se sente após comer certos alimentos comumente problemáticos.",
            "journalPrimary": "Existem alimentos que consistentemente fazem você se sentir inchada, cansada ou indisposta? O que notaria se rastreasse como se sente após cada refeição por uma semana?"
        },
        114: {
            "introduction": "Hoje vamos descobrir a arte das trocas saudáveis — substituições simples que reduzem calorias e melhoram a nutrição sem sacrificar a satisfação e o prazer das refeições. Não se trata de privação — se trata de escolhas mais inteligentes que fazem você se sentir tão bem quanto a comida tem gosto.",
            "mainContent": "Trocas saudáveis são uma das estratégias mais sustentáveis e livres de estresse na jornada de bem-estar. Em vez de eliminar completamente alimentos que ama ou seguir planos alimentares rígidos que parecem punitivos, você simplesmente substitui ingredientes ou preparações por opções que apoiam melhor seus objetivos — frequentemente sem diferença perceptível no sabor ou satisfação.\nAqui estão algumas das trocas mais eficazes:\n\n- **Arroz branco → Arroz integral ou couve-flor** (mais fibra, menos calorias)\n- **Creme de leite → Iogurte grego** (mais proteína, menos gordura)\n- **Macarrão regular → Macarrão integral ou abobrinha espiral** (mais fibra ou muito menos calorias)\n- **Refrigerante → Água com gás com limão ou frutas** (zero açúcar, mesmo frescor)\n- **Chips → Vegetais com homus** (mais nutrientes, mais saciedade)\n- **Sorvete → Banana congelada batida** (naturalmente doce, sem açúcar adicionado)\n- **Pão branco → Pão integral** (mais fibra e nutrientes)\n- **Fritura → Airfryer** (textura crocante, fração do óleo)\n- **Molho pronto de salada → Azeite + limão + ervas** (sem aditivos, mais saudável)\n- **Açúcar no café → Canela** (sem calorias, benefícios para açúcar no sangue)\n\nA chave é fazer uma troca de cada vez e dar a si mesma tempo para se acostumar. Na maioria dos casos, após duas a três semanas, a nova opção parecerá completamente normal — e a versão antiga pode até parecer pesada demais.\nTrocas funcionam porque removem a mentalidade de \"tudo ou nada\" que faz tantas dietas falharem. Você não está desistindo de nada — está atualizando. Ainda come macarrão, mas integral. Ainda come sorvete, mas feito de banana. A satisfação emocional permanece enquanto o perfil nutricional melhora.\nAlém de substituições de alimentos, considere trocas no preparo. Grelhar em vez de fritar, usar ervas frescas em vez de molhos pesados, e cozinhar no vapor em vez de saltear em óleo são todas formas de reduzir calorias enquanto mantém — e frequentemente melhora — o sabor.",
            "keyTakeaways": ["Trocas saudáveis reduzem calorias e melhoram nutrição sem sacrificar satisfação", "Faça uma troca de cada vez para mudança sustentável", "Na maioria dos casos, novas opções parecem normais em duas a três semanas", "Foque em atualizar, não eliminar — mantenha a satisfação emocional", "Trocas no preparo (grelhar em vez de fritar) são igualmente poderosas"],
            "actionStep": "Escolha uma troca saudável da lista de hoje e implemente na sua próxima refeição. Observe quão satisfeita se sente com a nova opção. Se funcionar bem, faça dela seu novo padrão.",
            "journalPrimary": "Quais trocas saudáveis mais te atraem? Existem alimentos que come por hábito que poderiam ser facilmente substituídos por opções mais nutritivas sem perder satisfação?"
        },
        115: {
            "introduction": "E se a chave para gerenciar o apetite não fosse força de vontade, mas os alimentos específicos que escolhe comer? Hoje vamos explorar alimentos que naturalmente ajudam a controlar a fome — não através de restrição, mas pela ciência da saciedade e satisfação.",
            "mainContent": "Certos alimentos têm a notável capacidade de ajudar você a se sentir satisfeita por mais tempo, reduzindo naturalmente a ingestão total sem que precise contar cada caloria ou lutar contra a fome. Esses alimentos \"supressores de apetite\" funcionam através de vários mecanismos: expandindo no estômago, retardando digestão, estabilizando açúcar no sangue, ou enviando sinais de saciedade ao cérebro.\nAlimentos ricos em fibra são os campeões da saciedade. Fibra absorve água e se expande no estômago, criando sensação de plenitude que dura horas. Feijões, lentilhas, aveia, frutas com casca, vegetais e sementes de chia são todas fontes excelentes. A chia é particularmente impressionante — pode absorver até 12 vezes seu peso em água, criando um gel no estômago que retarda a digestão significativamente.\nAlimentos ricos em proteína são outro pilar da saciedade. Proteína é o macronutriente mais saciante, desencadeando a liberação de hormônios de saciedade como peptídeo YY e GLP-1 que comunicam ao cérebro que você comeu o suficiente. Ovos, frango, peixe, iogurte grego e leguminosas são fontes poderosas.\nAlimentos com alto volume e baixa caloria — grandes em tamanho mas baixos em energia — enchem fisicamente o estômago sem entregar muitas calorias. Saladas volumosas, sopas à base de caldo, vegetais crus e frutas ricas em água como melancia e morango se encaixam nessa categoria. Começar refeições com uma sopa ou salada grande demonstrou reduzir a ingestão total significativamente.\nGorduras saudáveis, embora densas em calorias, promovem saciedade forte retardando o esvaziamento gástrico. Uma pequena quantidade de abacate, castanhas ou azeite adicionada a uma refeição pode fazer você se sentir satisfeita por muito mais tempo.\nÁgua desempenha papel surpreendente no controle do apetite. Beber um copo grande de água antes das refeições demonstrou reduzir a ingestão calórica em 75-90 calorias por refeição. Muitas vezes, o que sentimos como fome é na verdade sede.",
            "keyTakeaways": ["Alimentos ricos em fibra se expandem no estômago, criando saciedade duradoura", "Proteína é o macronutriente mais saciante, liberando hormônios de saciedade", "Alimentos de alto volume e baixa caloria enchem fisicamente sem muitas calorias", "Gorduras saudáveis retardam digestão, prolongando satisfação", "Beber água antes das refeições pode reduzir ingestão calórica significativamente"],
            "actionStep": "Em cada refeição hoje, inclua pelo menos um alimento supressor de apetite: comece com uma sopa ou salada grande, inclua uma fonte de proteína e fibra, e beba um copo de água antes de começar. Observe como sua fome muda ao longo do dia.",
            "journalPrimary": "Quais alimentos te deixam mais satisfeita por mais tempo? Existem refeições ou horários do dia em que luta mais com fome? Como poderia estrategicamente incluir mais alimentos saciantes nesses momentos?"
        },
        116: {
            "introduction": "Hoje vamos abordar um dos desafios mais difundidos da vida moderna — ficar sentada por tempo prolongado. Nossos corpos foram projetados para movimento, no entanto muitas de nós passamos a maioria das horas acordadas sentadas. Pequenas mudanças podem fazer uma diferença surpreendentemente grande.",
            "mainContent": "Pesquisas cada vez mais chamam o \"ficar sentado\" de \"o novo fumar\" — uma declaração dramática, mas respaldada por ciência preocupante. Ficar sentada por períodos prolongados está associada a maior risco de doenças cardíacas, diabetes tipo 2, certos tipos de câncer, e sim, ganho de peso — independentemente de se exercitar em outros momentos do dia. Isso significa que mesmo se faz um treino pela manhã, ficar sentada as próximas oito horas ainda afeta negativamente sua saúde.\nA boa notícia é que interromper o tempo sentada com pausas breves de movimento — mesmo apenas ficar de pé e se alongar por um minuto — pode contrabalançar significativamente esses efeitos. A chave não é apenas quanto exercício formal faz, mas quão frequentemente interrompe períodos de ficar sentada ao longo do dia.\nUma mesa de trabalho de pé é uma das mudanças mais impactantes que pode fazer se trabalha em um escritório ou em casa. Alternar entre ficar de pé e sentada ao longo do dia mantém os músculos engajados, melhora a postura e queima significativamente mais calorias que ficar sentada o dia todo. Se uma mesa de pé não é possível, simplesmente ficar de pé durante chamadas ou colocar o laptop em uma superfície mais alta durante parte do dia ajuda.\nProgramar um timer para se mover a cada 30-45 minutos é surpreendentemente eficaz. Quando o timer toca, fique de pé, alongue, faça uma caminhada curta, suba um lance de escadas, ou faça algumas flexões ou agachamentos. Esses micro-intervalos de movimento se acumulam significativamente ao longo do dia e mantêm seu metabolismo mais ativo.\nReunião caminhando, como mencionamos anteriormente, são outra ferramenta poderosa. Substituir pelo menos uma reunião sentada por dia por uma caminhada adiciona movimento valioso enquanto frequentemente melhora criatividade e produtividade.\nA meta não é nunca sentar — é sentar menos e se mover mais ao longo do dia. Cada minuto que passa de pé ou se movendo em vez de sentada é uma vitória para seu bem-estar.",
            "keyTakeaways": ["Ficar sentada por longos períodos prejudica a saúde independente de exercício formal", "Interromper o tempo sentada a cada 30-45 minutos contrabalançar efeitos negativos", "Mesas de pé ou superfícies elevadas mantêm músculos engajados e melhoram postura", "Micro-intervalos de movimento se acumulam significativamente ao longo do dia", "A meta é sentar menos e se mover mais — cada minuto ativo conta"],
            "actionStep": "Programe um timer para a cada 30 minutos durante seu trabalho ou tempo em casa hoje. Quando tocar, fique de pé e se mova por pelo menos um minuto — alongue, caminhe, faça agachamentos ou simplesmente fique de pé. Observe como se sente no final do dia comparado a dias normais.",
            "journalPrimary": "Quantas horas por dia estima que passa sentada? Quais oportunidades existem para ficar de pé ou se mover mais durante essas horas? Qual pequena mudança poderia fazer amanhã?"
        },
        117: {
            "introduction": "Hoje vamos cozinhar algo especial — caldo de ossos. Este alimento antigo e nutritivo tem sido um básico curativo em culturas ao longo dos séculos, e a ciência moderna está validando o que nossos ancestrais sabiam intuitivamente: caldo de ossos é alimento para sua alma e para seu corpo.",
            "mainContent": "Caldo de ossos é feito cozinhando ossos lentamente — geralmente de frango, boi ou peixe — por um período prolongado, tipicamente de 12 a 24 horas. Esse cozimento lento extrai minerais, colágeno, aminoácidos e outros compostos benéficos dos ossos e tecidos conectivos, criando um líquido rico e nutritivo que é muito mais que uma sopa simples.\nO colágeno é um dos benefícios mais celebrados do caldo de ossos. Colágeno é a proteína mais abundante no corpo, encontrada na pele, articulações, ossos e tecido conectivo. Quando ingerido, se decompõe em aminoácidos como glicina e prolina que apoiam saúde articular, elasticidade da pele e integridade do revestimento intestinal. Para sua jornada de bem-estar, um intestino saudável significa melhor absorção de nutrientes, menos inflamação e metabolismo melhorado.\nCaldo de ossos é naturalmente rico em minerais como cálcio, magnésio, fósforo e potássio em formas que o corpo pode absorver facilmente. É também surpreendentemente saciante — a proteína do colágeno e gelatina promove sensação de saciedade, tornando-o um excelente alimento para apoiar controle de peso.\nDo ponto de vista prático, caldo de ossos é versátil e econômico. Pode ser bebido como chá quente, usado como base para sopas e ensopados, para cozinhar grãos, ou como líquido de cozimento para vegetais e proteínas. Pode ser feito em casa usando ossos que de outra forma seriam descartados — é nutrição de praticamente zero desperdício.\nSe preferir conveniência, caldos de ossos de qualidade estão cada vez mais disponíveis em mercados e online. Procure variedades com ingredientes mínimos, sem saborizantes artificiais e com pelo menos 8-10 gramas de proteína por porção, indicando que é genuíno caldo de ossos e não apenas caldo regular.",
            "keyTakeaways": ["Caldo de ossos é rico em colágeno que apoia articulações, intestino e pele", "Contém minerais biodisponíveis como cálcio, magnésio e potássio", "A proteína do colágeno promove saciedade, apoiando controle de peso", "Pode ser bebido, usado em sopas, ou para cozinhar grãos e vegetais", "Pode ser feito em casa economicamente ou comprado com qualidade"],
            "actionStep": "Experimente incorporar caldo de ossos ao seu dia — beba uma xícara como lanche quente, use como base para uma sopa, ou cozinhe arroz ou quinoa nele para nutrição extra. Se nunca fez, pesquise uma receita simples de caldo de ossos.",
            "journalPrimary": "Já experimentou caldo de ossos? Se sim, como gosta de usá-lo? Se não, o que te atrai — ou preocupa — sobre experimentar? Como alimentos tradicionais e nutritivos poderiam apoiar sua jornada?"
        },
        118: {
            "introduction": "Hoje vamos desenvolver uma das habilidades mais importantes na jornada de bem-estar — a capacidade de distinguir entre fome física verdadeira e apetite, que é o desejo psicológico de comer. Aprender essa diferença é libertador e transformador.",
            "mainContent": "Fome e apetite são frequentemente usados como sinônimos, mas são experiências fundamentalmente diferentes. Fome é uma necessidade biológica — seu corpo requer combustível e te informa através de sinais físicos como estômago roncando, queda de energia, dificuldade de concentração, e às vezes irritabilidade. O apetite, por outro lado, é um desejo psicológico por comida que pode existir completamente independente da necessidade física.\nA fome física se constrói gradualmente. Começa sutil e se intensifica com o tempo. Pode ser satisfeita por uma variedade de alimentos — quando está realmente com fome, praticamente qualquer coisa parece apelativa. Ela é acompanhada por sinais corporais reais: estômago vazio, energia diminuindo, talvez leve tontura. E uma vez que come o suficiente, a fome desaparece. Há uma sensação clara de \"tive o bastante\".\nO apetite, em contraste, tende a aparecer de repente. Frequentemente deseja alimentos específicos — ninguém nunca disse \"Estou tão estressada, preciso de brócolis\". É tipicamente disparado por emoções (estresse, tédio, solidão, celebração), estímulos ambientais (ver ou cheirar comida, propagandas), horário do dia, ou simplesmente hábito. E a satisfação do apetite é muitas vezes temporária — você pode comer sem realmente se sentir \"cheia\" porque nunca esteve fisicamente vazia para começar.\nDesenvolver a capacidade de pausar e perguntar \"Estou fisicamente com fome ou isso é apetite?\" é uma das habilidades mais transformadoras que pode construir. Não significa que nunca deve comer por apetite — comer socialmente, comida como prazer e celebração são todos partes de uma vida saudável. Significa fazer essa distinção conscientemente e escolher sua resposta em vez de reagir automaticamente.\nUma prática útil é a escala de fome. Imagine uma escala de 1 a 10, onde 1 é faminta e 10 é desconfortavelmente estufada. Idealmente, você come quando está em torno de 3-4 e para quando alcança 6-7. Essa consciência simples pode transformar padrões de alimentação ao longo do tempo.",
            "keyTakeaways": ["Fome física se constrói gradualmente e pode ser satisfeita por muitos alimentos", "Apetite aparece de repente, deseja alimentos específicos e é disparado por emoções ou ambiente", "Pausar para perguntar \"Isso é fome ou apetite?\" é uma habilidade transformadora", "Comer por apetite às vezes está bem — a chave é consciência e escolha", "A escala de fome (1-10) ajuda a reconhecer quando comer e quando parar"],
            "actionStep": "Antes de cada vez que comer hoje, pause por 30 segundos e pergunte: \"Estou fisicamente com fome, ou é apetite?\" Observe os sinais do corpo. Se é apetite, identifique o que está realmente disparando o desejo.",
            "journalPrimary": "Como você diferencia fome de apetite na prática? Existem momentos específicos do dia ou situações em que come mais por apetite do que fome? O que desencadeia esses momentos?"
        },
        119: {
            "introduction": "Comer por estresse é um dos desafios mais comuns na jornada de bem-estar — e hoje vamos abordá-lo com compaixão em vez de crítica. Buscar comida quando estressada não é uma falha de caráter — é uma resposta humana compreensível que pode ser gentilmente redirecionada com as ferramentas certas.",
            "mainContent": "Quando o estresse atinge, seu corpo libera cortisol — e cortisol literalmente te faz desejar alimentos ricos em açúcar e gordura. Não é falta de força de vontade; é bioquímica. Seu corpo está buscando uma fonte rápida de conforto e energia porque acredita que precisa se preparar para perigo. Entender isso remove a vergonha e te empodera a encontrar melhores soluções.\nA comida funciona como regulador de estresse porque genuinamente altera a química do cérebro. Alimentos açucarados e gordurosos disparam dopamina — o neurotransmissor do prazer — proporcionando alívio temporário real do desconforto emocional. O problema não é que a comida não funciona para estresse; é que funciona muito bem no curto prazo enquanto cria problemas no longo prazo.\nO primeiro passo para gerenciar comer por estresse é identificar seus gatilhos específicos. Trabalho? Relacionamentos? Finanças? Solidão? Fadiga? Cada pessoa tem gatilhos diferentes, e conhecer os seus permite intervir mais cedo no processo.\nDesenvolva um \"kit de ferramentas de estresse\" que não envolva comida:\n- **Respiração**: 4 tempos de inspiração, segurar por 4, expirar por 6\n- **Movimento**: Uma caminhada de 10 minutos pode reduzir cortisol significativamente\n- **Conexão**: Ligar para uma amiga ou familiar\n- **Escrita**: Diário de emoções por 5 minutos\n- **Sensorial**: Banho quente, música calmante, aromaterapia\n- **Mindfulness**: 5 minutos de meditação guiada\n\nA técnica da \"pausa de 10 minutos\" é particularmente eficaz. Quando sentir o impulso de comer por estresse, comprometa-se a esperar apenas 10 minutos e fazer uma atividade do kit de ferramentas. Muitas vezes o impulso passa, e se ainda quiser comer depois, pode fazer uma escolha mais consciente.\nSeja gentil consigo mesma quando comer por estresse acontecer — porque vai acontecer. O progresso não é eliminação perfeita; é consciência crescente e resposta cada vez mais frequente com ferramentas alternativas.",
            "keyTakeaways": ["Comer por estresse é uma resposta bioquímica ao cortisol, não falta de força de vontade", "Identifique seus gatilhos específicos de estresse para intervir mais cedo", "Desenvolva um \"kit de ferramentas de estresse\" com alternativas sem comida", "A pausa de 10 minutos permite que o impulso passe naturalmente", "Progresso é consciência crescente, não eliminação perfeita"],
            "actionStep": "Crie seu kit pessoal de ferramentas de estresse. Escreva cinco atividades sem comida que genuinamente te acalmam e as tenha visíveis — no celular, na geladeira, ou no espelho. Na próxima vez que sentir o impulso de comer por estresse, experimente uma antes de ir à comida.",
            "journalPrimary": "Quais são seus maiores gatilhos de estresse que levam a comer? Quando percebe o impulso de comer por estresse, que emoção está realmente sentindo? Que atividades sem comida genuinamente te trazem conforto?"
        },
        120: {
            "introduction": "Ao fechar os primeiros quatro meses da jornada, hoje vamos olhar adiante — não apenas para a próxima semana ou mês, mas para o resto da vida. Criar um plano de manutenção garante que as mudanças lindas que construiu se tornem permanentes, sustentáveis e genuinamente suas.",
            "mainContent": "Os primeiros 120 dias da sua jornada de bem-estar foram sobre aprender, experimentar e construir hábitos. Daqui para frente, o foco muda para manutenção, refinamento e sustentabilidade de longo prazo. Essa transição é crucial — é onde muitas pessoas tropeçam porque tratam a jornada como algo temporário em vez de um estilo de vida permanente.\nCriar um plano de manutenção começa com identificar os hábitos não negociáveis — as práticas que fazem a maior diferença para você e que se comprometeu a manter não importa o quê. Para algumas pessoas é beber água suficiente, para outras é preparar refeições, para outras é caminhar diariamente. Identifique seus 3-5 não negociáveis e proteja-os ferozmente.\nReconheça que manutenção não é estática — é dinâmica. Sua vida vai mudar: estações, trabalhos, relacionamentos, saúde e circunstâncias vão evoluir. Seu plano de bem-estar precisa ter flexibilidade embutida para se adaptar a essas mudanças sem quebrar. A diferença entre uma abordagem rígida que falha e uma flexível que perdura é a capacidade de se adaptar sem abandonar.\nSistemas são mais poderosos que metas nesta fase. Em vez de \"Quero perder mais 5 quilos\", pense \"Sou uma pessoa que se move 30 minutos por dia e come vegetais em cada refeição\". Metas têm linhas de chegada; sistemas são para sempre.\nPlaneje para os inevitáveis contratempos. Não é \"se\" vai ter um dia ruim ou uma semana difícil — é \"quando\". Ter um plano de recuperação — \"Quando escorregar, minha próxima refeição será equilibrada e nutritiva\" — remove a espiral de culpa que transforma um contratempo em uma desistência.\nFinalmente, continue aprendendo e se adaptando. A ciência da nutrição evolui, seu corpo muda com a idade, e novas descobertas podem oferecer ferramentas melhores. Mantenha-se curiosa, aberta e disposta a ajustar sua abordagem conforme cresce.\nVocê não está terminando um programa. Está vivendo uma vida que projetou — uma vida de energia, saúde e amor-próprio. E essa vida continua para sempre.",
            "keyTakeaways": ["Identifique seus 3-5 hábitos não negociáveis e proteja-os", "Manutenção é dinâmica — flexibilidade é essencial para sustentabilidade", "Sistemas ('eu sou alguém que...') são mais poderosos que metas com prazo", "Planeje para contratempos com um plano de recuperação, não com perfeição", "Continue aprendendo e adaptando — bem-estar é uma jornada vitalícia"],
            "actionStep": "Escreva seus 3-5 hábitos de bem-estar não negociáveis — as práticas que se compromete a manter independente do que a vida traga. Para cada um, escreva uma declaração de identidade: \"Eu sou alguém que...\" Poste onde vai vê-los diariamente.",
            "journalPrimary": "Quais hábitos dos últimos 120 dias fizeram mais diferença no como se sente? O que precisa ser parte permanente da sua vida? Como vai se adaptar quando a vida inevitavelmente interromper sua rotina?"
        },
    }

def apply_translations(data, translations):
    count = 0
    for lesson in data['lessons']:
        day = lesson['dayNumber']
        if day in translations:
            t = translations[day]
            lesson['content']['introduction'] = t['introduction']
            lesson['content']['mainContent'] = t['mainContent']
            lesson['content']['keyTakeaways'] = t['keyTakeaways']
            lesson['content']['actionStep'] = t['actionStep']
            lesson['journalPrompt']['primary'] = t['journalPrimary']
            count += 1
    return count

if __name__ == '__main__':
    filepath = 'src/i18n/locales/pt/lessons.json'
    with open(filepath, 'r') as f:
        data = json.load(f)
    translations = get_translations()
    count = apply_translations(data, translations)
    with open(filepath, 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Applied {count} translations (Days 101-120)")
