#!/usr/bin/env python3
"""Apply Brazilian Portuguese translations for days 21-40."""
import json

def get_translations():
    return {
        21: {
            "introduction": "Caminhar é a forma de movimento mais subestimada. Hoje, vamos descobrir seus benefícios profundos.",
            "mainContent": "**Caminhar: O Exercício Perfeito**\n\nCaminhar é:\n- Acessível para quase todo mundo\n- Gratuito e não exige equipamento\n- De baixo impacto e gentil com as articulações\n- Sustentável para a vida toda\n- Social ou solitário, como você preferir\n\n**Os Benefícios**\n\n**Físicos:**\n- Queima aproximadamente 290 calorias por hora (ritmo moderado)\n- Fortalece o coração\n- Apoia a densidade óssea\n- Auxilia a digestão\n- Melhora o equilíbrio e a coordenação\n\n**Mentais:**\n- Reduz estresse e ansiedade\n- Melhora o humor pela liberação de endorfinas\n- Melhora a função cognitiva\n- Estimula a criatividade\n- Melhor qualidade de sono\n\n**Começando**\n\nSe você não caminha regularmente:\n- Comece com apenas 5 minutos por dia\n- Adicione 5 minutos a cada semana\n- Busque eventualmente 30+ minutos na maioria dos dias\n- Qualquer caminhada conta — você não precisa de um horário especial\n\n**Tornando Prazeroso**\n\n- Caminhe na natureza quando possível\n- Ouça música, podcasts ou audiolivros\n- Caminhe com amigos ou família\n- Explore rotas novas\n- Pratique meditação caminhando",
            "keyTakeaways": [
                "Caminhar é acessível, gratuito e sustentável para a vida toda",
                "Queima cerca de 290 calorias por hora com inúmeros outros benefícios",
                "Comece com 5 minutos e aumente gradualmente"
            ],
            "actionStep": "Faça uma caminhada de 20 minutos hoje. Observe como se sente antes, durante e depois.",
            "journalPrimary": "Qual é sua relação com a caminhada? Como você poderia incorporar mais caminhadas na sua vida diária?"
        },
        22: {
            "introduction": "A simples prática de se movimentar após as refeições pode transformar sua digestão e seus níveis de energia.",
            "mainContent": "**Por Que o Movimento Pós-Refeição Importa**\n\nMovimento suave após comer:\n- Auxilia a digestão e reduz o inchaço\n- Ajuda a regular os níveis de açúcar no sangue\n- Previne a queda de energia pós-refeição\n- Queima calorias que poderiam ser armazenadas\n- Apoia a motilidade intestinal saudável\n\n**A Ciência**\n\nEstudos mostram que uma caminhada de 15 minutos após a refeição pode reduzir significativamente os picos de açúcar no sangue em comparação com permanecer sedentária. Isso é especialmente importante após refeições ricas em carboidratos.\n\n**Que Tipo de Movimento?**\n\nO movimento pós-refeição deve ser suave:\n- Uma caminhada casual (não caminhada rápida)\n- Tarefas domésticas leves\n- Alongamento suave\n- Ficar de pé e se mover em vez de sentar\n\n**Evite exercícios intensos imediatamente após comer, pois podem atrapalhar a digestão.**\n\n**Aplicação Prática**\n\n- Caminhe ao redor do quarteirão após o jantar\n- Suba as escadas de volta à sua mesa após o almoço\n- Faça alongamentos suaves após o café da manhã\n- Arrume a cozinha tranquilamente após as refeições\n\n**Tornando um Hábito**\n\nVincule o movimento pós-refeição ao seu ritual alimentar. Assim como você automaticamente retira o prato, adicione uma breve sessão de movimento.",
            "keyTakeaways": [
                "Movimento suave após as refeições auxilia a digestão e o açúcar no sangue",
                "Uma caminhada de 15 minutos após as refeições pode reduzir significativamente os picos de açúcar",
                "O movimento pós-refeição deve ser suave, não intenso"
            ],
            "actionStep": "Após cada refeição hoje, faça uma caminhada suave de 10-15 minutos ou faça movimentos leves.",
            "journalPrimary": "Como você costuma se sentir após as refeições? Como o movimento pós-refeição poderia mudar essa experiência?"
        },
        23: {
            "introduction": "Movimento sustentável não é sobre intensidade — é sobre consistência. Hoje, vamos construir uma prática que dure.",
            "mainContent": "**A Abordagem 5-5-5**\n\nComece pequeno, construa gradualmente:\n- Comece com apenas 5 minutos de movimento\n- Adicione 5 minutos a cada semana\n- Continue até alcançar seu objetivo (30-45 minutos é ideal para a maioria das pessoas)\n\n**Por Que Isso Funciona**\n\n- 5 minutos é tão fácil que você não tem desculpa para pular\n- A construção gradual previne esgotamento e lesões\n- Sucesso gera sucesso — cada dia prova que você consegue\n- O hábito se consolida antes de se tornar desafiador\n\n**Agendando o Movimento**\n\nO melhor horário para se exercitar é quando você realmente vai fazer. Considere:\n- **Manhã**: Já fica pronto antes que as desculpas apareçam\n- **Almoço**: Quebra o dia de trabalho\n- **Noite**: Descomprime após o trabalho\n\n**Superando o 'Não Tenho Tempo'**\n\n- 5 minutos é 0,3% do seu dia\n- O movimento melhora a energia e a produtividade\n- Agende como uma reunião importante\n- Lembre-se: algum movimento é melhor que nenhum\n\n**Dias de Descanso Importam**\n\nInclua 1-2 dias de descanso por semana. Seu corpo precisa de recuperação. Dias de descanso ainda podem incluir movimentos muito suaves como caminhadas.",
            "keyTakeaways": [
                "Comece com 5 minutos, adicione 5 minutos a cada semana",
                "Consistência importa mais que intensidade",
                "Inclua dias de descanso para recuperação"
            ],
            "actionStep": "Agende seu movimento para a semana que vem. Comece com blocos de tempo realistas que você sabe que pode cumprir.",
            "journalPrimary": "Qual horário do dia funciona melhor para sua prática de movimento? O que pode atrapalhar, e como você vai lidar com isso?"
        },
        24: {
            "introduction": "O melhor movimento é aquele que você gosta. Hoje, vamos explorar a variedade maravilhosa de formas de movimentar seu corpo.",
            "mainContent": "**Por Que a Variedade Importa**\n\n- Previne o tédio\n- Trabalha diferentes grupos musculares\n- Reduz lesões por movimentos repetitivos\n- Mantém as coisas interessantes\n- Ajuda a descobrir o que você ama\n\n**Opções de Movimento**\n\n**Suave:**\n- Caminhada\n- Natação\n- Yoga\n- Tai Chi\n- Alongamento\n\n**Moderado:**\n- Dança\n- Trilhas\n- Ciclismo\n- Jardinagem\n- Brincar com crianças/animais de estimação\n\n**Incorporando Movimento:**\n- Suba as escadas em vez do elevador\n- Estacione mais longe das entradas\n- Caminhe durante ligações telefônicas\n- Programe um alarme para se mover a cada hora\n- Faça elevações de panturrilha enquanto espera\n\n**Encontrando Sua Alegria**\n\nPergunte-se:\n- O que você adorava fazer quando criança?\n- O que parece divertido, não punitivo?\n- O que você se imagina fazendo a longo prazo?\n- O que poderia experimentar de completamente novo?\n\n**O Elemento Social**\n\nMovimento com outros:\n- Faz o tempo passar rápido\n- Adiciona responsabilidade\n- Cria comunidade\n- Torna mais divertido",
            "keyTakeaways": [
                "O melhor movimento é aquele que você gosta",
                "Variedade previne o tédio e trabalha diferentes músculos",
                "Procure formas de adicionar movimento ao longo do dia"
            ],
            "actionStep": "Experimente uma nova forma de movimento hoje — algo que você tinha curiosidade mas ainda não tentou.",
            "journalPrimary": "Que tipos de movimento trazem alegria para você? Que atividades novas gostaria de explorar?"
        },
        25: {
            "introduction": "Construir força não é sobre pesos pesados — é sobre ensinar seu corpo a te apoiar pela vida.",
            "mainContent": "**Por Que a Força Importa**\n\n'Treino de força' parece intimidador. Vamos chamar de 'fluxo corporal' — ensinar seu corpo a se mover com força e graça.\n\nBenefícios:\n- Mantém a massa muscular (perdemos 3-8% por década após os 30!)\n- Aumenta o metabolismo (músculo queima mais calorias que gordura)\n- Melhora a densidade óssea\n- Melhora movimentos funcionais do dia a dia\n- Aumenta a autoconfiança\n\n**Sem Equipamento Necessário**\n\nSeu corpo fornece toda a resistência que você precisa:\n\n- **Agachamentos**: Sente para trás como se fosse numa cadeira invisível\n- **Flexões na parede**: Flexões contra a parede\n- **Avanços**: Dê um passo à frente e abaixe\n- **Prancha**: Segure a posição com braços estendidos\n- **Equilíbrio em uma perna**: Trabalho de equilíbrio\n\n**Começando**\n\nComece com 10 repetições de cada movimento, 2-3 vezes por semana:\n1. 10 agachamentos\n2. 10 flexões na parede\n3. 10 avanços (cada perna)\n4. Prancha de 20 segundos\n5. 20 segundos equilibrando em cada perna\n\n**A Abordagem Gentil**\n\nIsso não é sobre 'sem dor, sem ganho'. Mova-se com atenção, pare se algo doer, e progrida gradualmente.",
            "keyTakeaways": [
                "Treino de força (fluxo corporal) mantém músculos e aumenta o metabolismo",
                "Exercícios com peso corporal não exigem equipamento",
                "Comece com 10 repetições, 2-3 vezes por semana"
            ],
            "actionStep": "Experimente a rotina simples de fluxo corporal hoje: 10 agachamentos, 10 flexões na parede, 10 avanços cada perna, prancha de 20 segundos.",
            "journalPrimary": "Qual é sua relação com o treino de força? Como reformular para 'fluxo corporal' muda sua perspectiva?"
        },
        26: {
            "introduction": "As palavras que você usa moldam sua realidade. Hoje, vamos transformar linguagem limitante em fala empoderadora.",
            "mainContent": "**Palavras Têm Poder**\n\nA linguagem que usamos — tanto em voz alta quanto na nossa cabeça — afeta profundamente nossas ações e resultados.\n\n**Linguagem Limitante vs. Empoderadora**\n\n- 'Eu tenho que' → 'Eu escolho'\n- 'Eu não consigo' → 'Estou aprendendo a'\n- 'Eu deveria' → 'Eu quero'\n- 'Vou tentar' → 'Eu vou'\n- 'Estou falhando' → 'Estou crescendo'\n- 'Isso é difícil' → 'Isso está me desafiando'\n- 'Estou me privando' → 'Estou me nutrindo'\n\n**Exemplos em Ação**\n\n❌ 'Eu tenho que fazer exercício'\n✅ 'Eu tenho a oportunidade de movimentar meu corpo'\n\n❌ 'Não posso comer isso'\n✅ 'Estou escolhendo não comer isso agora'\n\n❌ 'Fui tão ruim comendo aquilo'\n✅ 'Foi uma escolha; minha próxima escolha pode ser diferente'\n\n**O Poder do 'Eu Sou'**\n\nCuidado com declarações de 'Eu sou'. O que vem depois molda sua identidade:\n\n❌ 'Eu sou ruim em exercícios'\n✅ 'Estou construindo minha forma física'\n\n❌ 'Sou viciada em açúcar'\n✅ 'Estou aprendendo a apreciar outros sabores'",
            "keyTakeaways": [
                "A linguagem molda pensamentos, ações e resultados",
                "'Eu escolho' é mais empoderador que 'eu tenho que'",
                "Declarações de 'Eu sou' moldam sua identidade — use-as com sabedoria"
            ],
            "actionStep": "Flagre-se usando linguagem limitante hoje. Anote três situações e reformule-as usando alternativas empoderadoras.",
            "journalPrimary": "Que frases limitantes você costuma usar sobre si mesma e sua jornada de bem-estar? Como pode reformulá-las?"
        },
        27: {
            "introduction": "Disciplina não é punição — é o ato máximo de amor-próprio. Hoje, vamos ressignificar como enxergamos o compromisso.",
            "mainContent": "**Disciplina vs. Punição**\n\nDisciplina não é:\n- Aguentar firme através da dor\n- Se forçar a sofrer\n- Se punir por erros passados\n\nDisciplina é:\n- Cumprir promessas feitas a si mesma\n- Escolher alegria a longo prazo em vez de prazer momentâneo\n- Um ato de profundo autorrespeito\n\n**Disciplina vs. Consistência**\n\n**Disciplina**: Fazer o que precisa ser feito, mesmo quando não está a fim.\n\n**Consistência**: Aparecer regularmente, permitindo a imperfeição humana.\n\nAmbas importam. A disciplina te sustenta nos momentos difíceis; a consistência constrói mudanças duradouras.\n\n**Por Que Temos Dificuldade**\n\n- Fazemos mudanças demais de uma vez\n- Definimos padrões irrealistas\n- Faltam razões convincentes ('porquê')\n- Dependemos de motivação em vez de hábitos\n- Nos punimos por deslizes\n\n**Construindo Autodisciplina**\n\n1. Comece menor do que acha necessário\n2. Conecte ações ao seu 'porquê' mais profundo\n3. Crie um ambiente que apoie seus objetivos\n4. Use intenções de implementação: 'Quando X acontecer, eu vou fazer Y'\n5. Pratique autocompaixão quando vacilar",
            "keyTakeaways": [
                "Disciplina é amor-próprio em ação",
                "Comece menor do que acha necessário",
                "Consistência permite a imperfeição humana"
            ],
            "actionStep": "Identifique uma área onde você tem dificuldade com disciplina. Torne-a menor e mais fácil. Conecte-a ao seu 'porquê'.",
            "journalPrimary": "Onde você tem sido dura demais consigo mesma? Como enxergar a disciplina como um ato de amor-próprio poderia mudar isso?"
        },
        28: {
            "introduction": "Desculpas nos protegem do fracasso, mas também impedem nosso sucesso. Hoje, vamos aprender a liberá-las.",
            "mainContent": "**Desculpas Comuns**\n\n- 'Não tenho tempo'\n- 'Estou muito cansada'\n- 'É muito difícil'\n- 'Começo na segunda'\n- 'Já tentei antes e falhei'\n- 'Tenho genética ruim'\n- 'Comida saudável é muito cara'\n- 'Não sei como'\n\n**A Verdade Sobre Desculpas**\n\nDesculpas são a forma da nossa mente nos proteger de:\n- Medo do fracasso\n- Medo do sucesso\n- Desconforto da mudança\n- Desafio à nossa identidade\n\n**Desculpa vs. Explicação**\n\nUma desculpa impede a ação. Uma explicação precede a resolução do problema.\n\n❌ Desculpa: 'Não consigo fazer exercício porque não tenho tempo.'\n✅ Explicação + Solução: 'Minha agenda é cheia, então vou encontrar duas janelas de 10 minutos para me movimentar.'\n\n**Liberando Desculpas**\n\n1. **Reconheça a desculpa** sem julgamento\n2. **Examine honestamente**: É realmente verdade?\n3. **Encontre o medo por trás**: Do que você tem medo?\n4. **Reformule como um problema a resolver**: Como posso contornar isso?\n5. **Tome uma pequena ação**: Prove que a desculpa está errada\n\n**Lembre-se**: Cada desculpa que você libera é um passo em direção à liberdade.",
            "keyTakeaways": [
                "Desculpas nos protegem, mas também impedem o crescimento",
                "Transforme desculpas em problemas a resolver",
                "Cada desculpa liberada é um passo em direção à liberdade"
            ],
            "actionStep": "Anote suas três desculpas mais comuns. Para cada uma, escreva uma solução ou alternativa.",
            "journalPrimary": "Que desculpas você costuma dar para si mesma? Que medos podem estar escondidos por trás delas?"
        },
        29: {
            "introduction": "Aquela voz severa na sua cabeça não é sua inimiga — é uma protetora que precisa de atualização. Hoje, vamos aprender a trabalhar com ela.",
            "mainContent": "**Entendendo o Crítico Interior**\n\nSeu crítico interior se desenvolveu para te proteger de:\n- Rejeição social\n- Decepção\n- Fracasso\n- Ridicularização\n\nEle tem boas intenções, mas frequentemente usa estratégias ultrapassadas e prejudiciais.\n\n**Mensagens Comuns do Crítico Interior**\n\n- 'Você nunca vai mudar'\n- 'Você sempre falha nisso'\n- 'Quem você pensa que é?'\n- 'Você não merece se sentir bem'\n- 'Outras pessoas conseguem, mas você não'\n\n**Ressignificando o Fracasso**\n\nFracasso não é o oposto do sucesso — faz parte do sucesso.\n\nCada 'fracasso' é:\n- Informação sobre o que não funciona\n- Prova de que você está tentando\n- Uma oportunidade de ajustar e crescer\n- Um degrau, não um obstáculo\n\n**Trabalhando com Seu Crítico Interior**\n\n1. **Reconheça**: 'Estou te ouvindo'\n2. **Agradeça**: 'Obrigada por tentar me proteger'\n3. **Atualize**: 'Mas eu cresci, e agora consigo lidar com isso'\n4. **Redirecione**: 'E se isso pudesse dar certo? Como seria?'\n\n**A Alternativa da Autocompaixão**\n\nFale consigo mesma como falaria com uma amiga querida que estivesse passando por dificuldades. Você a criticaria duramente ou ofereceria encorajamento gentil?",
            "keyTakeaways": [
                "Seu crítico interior tem boas intenções, mas usa estratégias ultrapassadas",
                "Fracasso é informação e um degrau, não um obstáculo",
                "Trate-se com a compaixão que ofereceria a uma amiga"
            ],
            "actionStep": "Na próxima vez que seu crítico interior falar duramente, pause e responda com compaixão. Anote tanto a crítica quanto sua resposta compassiva.",
            "journalPrimary": "O que seu crítico interior mais frequentemente diz a você? Se você fosse sua conselheira compassiva, o que diria de volta?"
        },
        30: {
            "introduction": "Parabéns — você completou 30 dias da sua base de bem-estar. Hoje, vamos celebrar e declarar seu compromisso daqui para frente.",
            "mainContent": "**Refletindo Sobre Sua Jornada**\n\nNos últimos 30 dias, você explorou:\n- Definir intenções poderosas\n- Hidratação e consciência corporal\n- Design do ambiente e redes de apoio\n- Fundamentos de nutrição\n- Práticas de alimentação consciente\n- Arquitetura de refeições\n- Movimento com alegria\n- Transformação de mentalidade\n\nIsso não é o fim — é a base.\n\n**Seu Protocolo Pessoal**\n\nDe tudo que aprendeu, crie seu protocolo pessoal de bem-estar. Quais práticas você vai levar adiante?\n\nConsidere:\n- Rituais matinais\n- Práticas alimentares\n- Hábitos de movimento\n- Ferramentas de mentalidade\n- Redes de apoio\n\n**A Declaração de Bem-Estar**\n\nEscreva sua declaração pessoal de bem-estar — uma afirmação de quem você está se tornando e como escolhe viver.\n\nExemplo: 'Sou uma pessoa que nutre seu corpo com alimentos integrais, se move com alegria e fala consigo mesma com compaixão. Escolho o bem-estar não como destino, mas como prática diária de amor-próprio.'\n\n**O Que Vem a Seguir**\n\nFase 2: Momentum te espera. Mas tire um tempo para celebrar a Fase 1. Você construiu algo notável.",
            "keyTakeaways": [
                "30 dias de base te preparam para mudanças duradouras",
                "Crie seu protocolo pessoal de bem-estar com o que mais ressoou",
                "Sua jornada de bem-estar continua — isso é apenas o começo"
            ],
            "actionStep": "Escreva sua declaração pessoal de bem-estar. Leia em voz alta. Coloque onde você vai vê-la todos os dias.",
            "journalPrimary": "Quais são as três lições mais impactantes desses 30 dias? Como você vai levá-las adiante?"
        },
        31: {
            "introduction": "Bem-vinda a uma virada de jogo na sua jornada de bem-estar, alma linda! O preparo de refeições é uma das coisas mais amorosas que você pode fazer por si mesma — é como enviar um pacote de carinho para o seu eu do futuro. Quando você dedica um tempinho para planejar e preparar sua alimentação com antecedência, está se preparando para o sucesso em cada dia da semana.",
            "mainContent": "Imagine isso: é uma terça-feira à noite cheia, você está cansada de um dia longo, e a última coisa que quer fazer é descobrir o que comer. Sem um plano, é muito fácil pegar o que for mais rápido e conveniente — e isso muitas vezes significa escolhas que não servem de verdade ao seu corpo. Mas quando você já preparou refeições saudáveis no fim de semana, tudo que precisa fazer é abrir a geladeira e esquentar algo delicioso e nutritivo. Essa é a magia do preparo de refeições.\nOs benefícios vão muito além da conveniência. Quando você prepara refeições com antecedência, reduz naturalmente a alimentação impulsiva porque a decisão já foi tomada. Você não fica parada em frente à despensa às 19h tentando decidir o jantar — você já tem uma refeição linda e equilibrada te esperando. Isso também significa que você economiza dinheiro, já que compras planejadas significam menos compras por impulso e menos desperdício de comida.\nO controle de porções se torna fácil quando você prepara com antecedência. Em vez de estimar quantidades quando está com fome (e sejamos honestas, olhos famintos sempre servem mais), você porciona tudo com cuidado quando está calma e com a cabeça tranquila. Suas marmitas se tornam pequenos atos de autocuidado, cada uma perfeitamente equilibrada.\nComeçar é mais simples do que você imagina. Escolha um dia por semana — muita gente adora o domingo — e dedique algumas horas para preparar três ou quatro refeições. Invista em potes de vidro ou livres de BPA que empilhem direitinho na geladeira. Comece pequeno: talvez prepare apenas seus almoços da semana. Conforme for se sentindo confortável, expanda para cafés da manhã ou jantares também.\nPense no preparo de refeições como um ritual semanal de amor-próprio. Coloque sua música ou podcast favorito, prepare uma xícara de chá, e curta o processo. Você não está apenas cozinhando — está construindo uma base para uma relação mais saudável e tranquila com a comida.",
            "keyTakeaways": [
                "O preparo de refeições reduz a alimentação impulsiva e apoia escolhas conscientes",
                "Planejar com antecedência economiza tempo e dinheiro ao longo da semana",
                "Comece com 3-4 refeições e um dia de preparo por semana",
                "Refeições pré-porcionadas eliminam a adivinhação da alimentação equilibrada",
                "O processo em si pode se tornar um ritual prazeroso de autocuidado"
            ],
            "actionStep": "Escolha seu dia de preparo para esta semana e anote na agenda. Depois escolha duas receitas simples que gostaria de preparar — mantenha fácil e prazeroso. Compre os ingredientes e reserve duas horas para sua primeira sessão de preparo de refeições.",
            "journalPrimary": "Quais refeições ou horários do dia você acha mais desafiador comer bem? Como ter uma refeição pronta poderia mudar essa experiência?"
        },
        32: {
            "introduction": "Hoje vamos explorar um tema que pode realmente transformar sua relação com a comida — controle de porções. E o mais bonito é: não se trata de restrição ou privação. É sobre aprender a dar ao seu corpo exatamente o que ele precisa para se sentir satisfeito, energizado e nutrido. Pense nisso como uma conversa amorosa entre você e seu prato.",
            "mainContent": "Muitas de nós crescemos sem uma noção clara de como uma porção adequada realmente se parece. Ao longo das décadas, as porções dos restaurantes cresceram dramaticamente, e nossa percepção de \"normal\" mudou junto. A boa notícia é que recalibrar sua noção de porções é surpreendentemente simples — e você carrega a ferramenta de medida perfeita com você para todo lugar: sua mão.\nAqui vai um guia gentil que torna a consciência de porções fácil e intuitiva. Sua palma representa a quantidade certa de proteína para uma refeição — um pedaço de frango, peixe ou tofu do tamanho e espessura da sua palma. Feche o punho, e esse é aproximadamente o tanto de vegetais que deveria estar no seu prato (e sinceramente, você sempre pode comer mais vegetais!). Faça uma concha com a mão, e essa é mais ou menos a quantidade certa de carboidratos complexos como arroz, massa ou batata-doce. Por fim, seu polegar representa uma porção de gorduras saudáveis — pense em azeite, pasta de amendoim ou abacate.\nUma das estratégias mais eficazes e gentis é simplesmente usar pratos menores. Pesquisas mostraram que quando usamos um prato de 25 cm em vez de 30 cm, naturalmente nos servimos menos — mas nos sentimos igualmente satisfeitas. É um exemplo lindo de como pequenas mudanças no ambiente podem gerar grandes resultados sem nenhuma força de vontade.\nOutra prática útil é servir as refeições na cozinha em vez de colocar travessas na mesa de jantar. Quando a comida está bem na nossa frente, é natural repetir mesmo quando já estamos confortavelmente satisfeitas. Ao manter as travessas no balcão, você cria uma pausa gentil — um momento para checar com seu corpo e perguntar: \"Ainda estou com fome de verdade, ou estou comendo simplesmente porque está aqui?\"\nLembre-se, controle de porções não é sobre medir cada pedacinho ou se sentir privada. É sobre sintonizar com a sabedoria do seu corpo e honrar o que ele realmente precisa. Com o tempo, porções adequadas vão parecer completamente naturais, e você vai descobrir que comer a quantidade certa na verdade é mais satisfatório do que comer demais.",
            "keyTakeaways": [
                "Sua mão é um guia de porções que você sempre tem com você",
                "Pratos menores naturalmente levam a porções adequadas sem esforço",
                "Servir refeições na cozinha cria uma pausa consciente antes de repetir",
                "Controle de porções é sobre honrar seu corpo, não restringi-lo",
                "Com prática, porções equilibradas se tornam seu novo normal"
            ],
            "actionStep": "Na sua próxima refeição, use o método da mão para montar seu prato: uma palma de proteína, um punho de vegetais, uma mão em concha de carboidratos e um polegar de gordura saudável. Observe como essa porção faz você se sentir.",
            "journalPrimary": "Quando você pensa em controle de porções, que emoções surgem? Existem refeições em que você tende a comer mais do que seu corpo precisa, e o que pode estar motivando isso?"
        },
        33: {
            "introduction": "Bons sonhos não servem apenas para descansar — são uma das ferramentas mais poderosas na sua jornada de bem-estar! Hoje vamos mergulhar em algo que pode te surpreender: a conexão profunda entre o sono e como seu corpo administra o peso. Dormir bem não é luxo; é parte vital do autocuidado.",
            "mainContent": "Aqui vai algo fascinante que muita gente não percebe: quando você não dorme o suficiente, seu corpo muda os hormônios que controlam fome e saciedade. Especificamente, o sono ruim aumenta um hormônio chamado grelina — seu \"hormônio da fome\" — que faz você sentir mais fome ao longo do dia. Ao mesmo tempo, diminui a leptina, seu \"hormônio da saciedade\", tornando mais difícil se sentir satisfeita após comer. É como se seu corpo estivesse trabalhando contra você, e nada disso é sua culpa — é simplesmente a biologia respondendo ao descanso insuficiente.\nEssa mudança hormonal explica por que, após uma noite mal dormida, você pode se pegar desejando alimentos açucarados e ricos em carboidratos. Seu corpo está literalmente buscando energia rápida para compensar a fadiga. Pesquisas mostraram que pessoas com privação de sono consomem em média 300-400 calorias extras por dia comparado a quando estão bem descansadas. Com o tempo, isso se acumula significativamente.\nO ponto ideal para a maioria dos adultos é 7-9 horas de sono de qualidade por noite. Note essa palavra — qualidade. Não é só sobre as horas; é sobre quão restaurador o sono realmente é. O sono profundo e ininterrupto é quando seu corpo faz seu trabalho de reparo mais importante, incluindo regular o metabolismo e processar hormônios do estresse.\nCriar uma rotina antes de dormir é uma das coisas mais amorosas que você pode fazer pelo seu corpo. Comece a desacelerar cerca de uma hora antes de deitar. Diminua as luzes, guarde as telas (a luz azul realmente interfere nos seus hormônios do sono), e faça algo calmante — leia um livro, tome um banho quente, pratique alongamento suave ou beba um chá de camomila. Seu corpo vai começar a associar esses rituais com o sono, facilitando o adormecer naturalmente.\nPense no sono como a base que sustenta todo o resto na sua jornada de bem-estar. Quando você está bem descansada, faz melhores escolhas alimentares, tem mais energia para movimento suave e lida com o estresse com mais graça. Priorizar o sono não é preguiça — é uma das coisas mais inteligentes que você pode fazer pela sua saúde.",
            "keyTakeaways": [
                "O sono ruim aumenta hormônios da fome e diminui sinais de saciedade",
                "Pessoas com privação de sono tendem a consumir 300-400 calorias extras por dia",
                "Busque 7-9 horas de sono de qualidade e ininterrupto por noite",
                "Uma rotina consistente antes de dormir sinaliza ao corpo que é hora de descansar",
                "Sono de qualidade apoia melhores escolhas alimentares, energia e gestão do estresse"
            ],
            "actionStep": "Esta noite, programe um \"alarme de desacelerar\" uma hora antes do horário que deseja dormir. Quando tocar, guarde todas as telas, diminua as luzes e faça uma atividade calmante antes de deitar. Observe como se sente pela manhã.",
            "journalPrimary": "Quantas horas de sono você costuma dormir, e como se sente no dia seguinte? Qual é uma coisa que está entre você e um sono melhor que poderia resolver esta semana?"
        },
        34: {
            "introduction": "Vamos ter uma conversa honesta e carinhosa sobre algo que afeta tantas de nós: o estresse. Você pode não perceber, mas o estresse que carrega na mente e no coração pode se manifestar no corpo de formas muito reais. Entender essa conexão é incrivelmente empoderador porque significa que gerenciar o estresse não é bom apenas para sua paz mental — é uma ferramenta genuína para apoiar seus objetivos de bem-estar.",
            "mainContent": "Quando você está sob estresse crônico, seu corpo libera um hormônio chamado cortisol. Em doses curtas, o cortisol é na verdade útil — faz parte da sua resposta de \"luta ou fuga\" que mantinha nossos ancestrais seguros. Mas quando o estresse se torna um companheiro constante, o cortisol permanece elevado, e é aí que os problemas começam. Um dos efeitos do cortisol é promover o armazenamento de gordura, particularmente na região abdominal. Isso não é sobre força de vontade ou disciplina — é uma resposta hormonal que acontece automaticamente quando seu corpo se sente ameaçado.\nO cortisol elevado também aumenta os desejos por comidas reconfortantes — aquelas opções ricas em açúcar e gordura que proporcionam uma sensação temporária de alívio. Seu corpo está literalmente buscando uma fonte rápida de energia e conforto porque acredita estar em perigo. Entender isso remove a vergonha e a autoculpa que tantas pessoas carregam em relação aos seus padrões alimentares.\nExercícios de respiração profunda são uma das ferramentas mais simples e poderosas que você tem. Quando você faz respirações lentas e profundas — especialmente quando prolonga a expiração mais que a inspiração — ativa o sistema nervoso parassimpático, que é o modo \"descansar e digerir\" do seu corpo. Apenas três a cinco minutos de respiração intencional podem reduzir os níveis de cortisol e trazer uma sensação de calma. Tente inspirar por quatro tempos, segurar por quatro e expirar por seis.\nMeditação e mindfulness não precisam ser complicados ou demorados. Mesmo cinco minutos sentada em silêncio focando na respiração pode fazer uma diferença significativa. Existem aplicativos gratuitos maravilhosos e meditações guiadas disponíveis se sentar em silêncio parecer desafiador no início. A chave é a consistência — alguns minutos todos os dias são muito mais eficazes que uma hora por semana.\nAlém dessas práticas, pense no que genuinamente traz alegria e relaxamento para você. Talvez seja uma caminhada na natureza, pintar, brincar com um animal de estimação, ouvir música ou conversar com uma amiga querida. Essas atividades de alívio do estresse não são luxos — são partes essenciais do seu kit de ferramentas de bem-estar. Quando você gerencia o estresse, não está apenas se sentindo melhor emocionalmente; está criando o ambiente interno que seu corpo precisa para liberar o excesso de peso naturalmente.",
            "keyTakeaways": [
                "O estresse crônico eleva o cortisol, que promove armazenamento de gordura na região abdominal",
                "O cortisol elevado gera desejos por comidas reconfortantes ricas em açúcar e gordura",
                "A respiração profunda ativa o sistema calmante de \"descansar e digerir\" do corpo",
                "Mesmo cinco minutos de meditação diária podem reduzir significativamente o estresse",
                "Atividades prazerosas de alívio do estresse são ferramentas essenciais, não luxos"
            ],
            "actionStep": "Pratique um exercício simples de respiração agora: inspire por 4 tempos, segure por 4 tempos, expire por 6 tempos. Repita cinco vezes. Observe como seu corpo se sente antes e depois. Comprometa-se a fazer isso uma vez hoje quando sentir tensão aumentando.",
            "journalPrimary": "Quais são suas três principais fontes de estresse agora? Para cada uma, você consegue identificar uma pequena ação que poderia reduzir seu impacto na sua vida diária?"
        },
        35: {
            "introduction": "Conhecimento é poder, querida, e hoje vamos colocar esse poder direto nas suas mãos — literalmente! Aprender a ler rótulos nutricionais é como ter um tradutor para a linguagem dos alimentos. Uma vez que você entenda o que aqueles números e ingredientes realmente significam, vai se sentir confiante e empoderada toda vez que for às compras. Sem mais adivinhação, sem mais cair em marketing inteligente.",
            "mainContent": "A primeira coisa a verificar em qualquer rótulo nutricional é o tamanho da porção. É aqui que muita gente se confunde. Aquele pacote de chips pode dizer 150 calorias — mas se o tamanho da porção é apenas 10 chips e o pacote contém cinco porções, você na verdade está olhando para 750 calorias no pacote todo. Sempre comece por aqui, porque todos os outros números no rótulo são baseados nessa porção única.\nEm seguida, torne-se uma detetive quando se trata de açúcares escondidos. Os fabricantes de alimentos são espertos — sabem que consumidores conscientes da saúde procuram \"açúcar\" nas listas de ingredientes, então usam dezenas de nomes alternativos. Fique atenta a qualquer coisa terminando em \"-ose\" (como frutose, sacarose, maltose ou dextrose), além de xaropes, néctares e concentrados. Se vários deles aparecem em um produto, é sinal de que o açúcar é um componente principal, mesmo que nenhum tipo único apareça primeiro na lista.\nO sódio é outro número importante para observar, especialmente porque o excesso de sódio pode causar retenção de líquidos e inchaço, o que pode ser desanimador quando você está acompanhando seu progresso. O limite diário recomendado é 2.300 mg, mas muitos alimentos processados contêm uma quantidade surpreendente. Uma única lata de sopa, por exemplo, pode conter mais de 800 mg — mais de um terço da sua cota diária em uma única refeição.\nAqui vai uma regra de ouro: ignore as alegações de marketing na frente da embalagem. Palavras como \"natural\", \"light\", \"integral\" e até \"orgânico\" não necessariamente significam que um alimento é saudável ou baixo em calorias. São termos de marketing projetados para fazer você se sentir bem com a compra. A história real está sempre no painel de informações nutricionais e na lista de ingredientes no verso.\nA lista de ingredientes em si conta muito. Os ingredientes são listados em ordem de quantidade — o que aparece primeiro compõe a maior parte do alimento. Se açúcar, óleo ou uma palavra que você não consegue pronunciar está nos três primeiros ingredientes, essa é uma informação valiosa. Como guia geral, quanto mais curta e reconhecível a lista de ingredientes, mais próximo o alimento está da sua forma natural.",
            "keyTakeaways": [
                "Sempre verifique o tamanho da porção primeiro — todo o resto depende disso",
                "Procure açúcares escondidos sob nomes terminando em \"-ose\", xaropes e concentrados",
                "Monitore o teor de sódio, especialmente em alimentos processados e embalados",
                "Ignore alegações de marketing na frente da embalagem; confie no painel nutricional",
                "Listas de ingredientes mais curtas e reconhecíveis geralmente significam escolhas mais saudáveis"
            ],
            "actionStep": "Pegue três alimentos embalados da sua cozinha agora. Leia cada rótulo com atenção: verifique o tamanho da porção, identifique açúcares escondidos e observe o teor de sódio. Você pode se surpreender com o que encontrar!",
            "journalPrimary": "Você já ficou surpresa com algo que encontrou em um rótulo nutricional? Como ter esse conhecimento muda como você se sente ao escolher alimentos?"
        },
        36: {
            "introduction": "Hoje vamos falar sobre algo que pode fazer uma diferença profunda em como você se sente todos os dias — reduzir os açúcares refinados na sua vida. Isso não é sobre punição ou perfeição, querida. É sobre entender como os açúcares refinados afetam seu corpo e gentilmente direcionar para escolhas que te deixem estável, energizada e verdadeiramente satisfeita.",
            "mainContent": "Os açúcares refinados têm um efeito poderoso no seu corpo. Quando você os consome, seu açúcar no sangue dispara rapidamente, te dando uma explosão de energia que parece maravilhosa — mas é seguida por uma queda inevitável. Essa queda desencadeia mais desejos, criando um ciclo que pode parecer impossível de escapar. Enquanto isso, a insulina elevada pelos picos repetidos de açúcar sinaliza ao seu corpo para armazenar gordura em vez de queimá-la. Entender esse ciclo é o primeiro passo para se libertar dele.\nO açúcar se esconde em mais lugares do que você imagina. Além dos culpados óbvios como refrigerantes, doces e confeitaria, açúcares refinados aparecem em cafés aromatizados, lanches embalados, condimentos, pão e até molhos salgados. Nas listas de ingredientes, o açúcar tem muitos nomes — sacarose, xarope de milho, maltose, dextrose e qualquer coisa terminando em \"-ose\". Tornar-se consciente desses disfarces te coloca de volta no controle das suas escolhas.\nUma das trocas mais bonitas que você pode fazer é escolher alimentos integrais e naturalmente doces como frutas quando os desejos aparecem. Diferente do açúcar refinado, a fruta vem embalada com fibra, que retarda a absorção dos seus açúcares naturais e previne aqueles picos dramáticos de açúcar no sangue. Um punhado de frutas vermelhas ou uma maçã crocante pode satisfazer seu desejo por doce enquanto realmente nutre seu corpo. É a sobremesa original da natureza!\nMontar refeições equilibradas é outra estratégia poderosa. Quando você inclui proteína, gorduras saudáveis e fibra em cada refeição, seu açúcar no sangue fica estável ao longo do dia, o que naturalmente reduz os desejos por açúcar. Pense nisso como construir um fogo firme com boas toras em vez de jogar papel que arde rápido e apaga.\nTalvez o mais importante: reduza o açúcar gradualmente em vez de cortar tudo de uma vez. A eliminação drástica frequentemente leva a desejos de rebote e alimentação emocional excessiva. Em vez disso, diminua gentilmente a quantidade de açúcar no café semana a semana, troque um lanche açucarado por uma fruta, ou escolha iogurte natural e adicione suas próprias frutas vermelhas. Suas papilas gustativas vão realmente se adaptar — alimentos que antes pareciam não doces o suficiente começarão a ter um sabor perfeitamente delicioso.\nFinalmente, preste atenção em quando os desejos por açúcar batem mais forte. Você está estressada? Cansada? Entediada? Frequentemente, o desejo não é realmente sobre açúcar — é sobre buscar conforto ou energia. Quando você consegue identificar a necessidade subjacente e atendê-la diretamente — com descanso, conexão, movimento ou uma respiração profunda — o desejo muitas vezes se dissolve por conta própria.",
            "keyTakeaways": [
                "O açúcar refinado cria um ciclo de pico e queda que gera mais desejos e armazenamento de gordura",
                "O açúcar se esconde em muitos alimentos sob nomes como xarope de milho, maltose e dextrose",
                "Frutas inteiras satisfazem desejos de doces enquanto fornecem fibra e nutrientes",
                "Refeições equilibradas com proteína, gordura e fibra mantêm o açúcar no sangue estável",
                "A redução gradual funciona melhor que a eliminação repentina"
            ],
            "actionStep": "Identifique uma fonte de açúcar refinado que você consome regularmente — talvez uma bebida adoçada, um doce diário ou um condimento. Escolha uma alternativa mais gentil para experimentar esta semana: fruta em vez de doce, água com gás em vez de refrigerante, ou iogurte natural com frutas vermelhas em vez de iogurte com sabor.",
            "journalPrimary": "Quando você sente desejo por açúcar mais intensamente? Que emoção ou situação tende a desencadeá-lo? Como você poderia atender essa necessidade subjacente sem buscar algo doce?"
        },
        37: {
            "introduction": "Hoje é sobre uma das habilidades mais transformadoras que você pode desenvolver nessa jornada — comer com atenção plena. No nosso mundo acelerado, tantas de nós comemos no piloto automático, mal sentindo o sabor da comida. A alimentação consciente te convida a desacelerar, realmente saborear seu alimento e reconectar com a sabedoria natural do seu corpo sobre fome e saciedade.",
            "mainContent": "Alimentação consciente é, em essência, simplesmente prestar atenção. É sobre estar totalmente presente com sua comida — perceber as cores, aromas, texturas e sabores de cada mordida. Quando você come assim, algo notável acontece: você aproveita mais sua comida enquanto naturalmente come menos. Seu corpo tem sinais sofisticados que dizem quando você comeu o suficiente, mas esses sinais levam cerca de 20 minutos para se registrar completamente. Quando come rápido e distraída, você frequentemente ultrapassa esses sinais.\nO primeiro e talvez mais importante passo é comer sem distrações. Isso significa desligar a TV, colocar o celular virado para baixo e se afastar do computador. Pode parecer desconfortável no início — muitas de nós usamos telas como companhia na hora das refeições — mas essa simples mudança permite que você realmente experimente sua comida. Você pode descobrir sabores e texturas que estava perdendo completamente.\nTente colocar o garfo na mesa entre as mordidas. Essa prática gentil naturalmente desacelera seu ritmo de alimentação, dando tempo ao cérebro para receber sinais de saciedade do estômago. Também permite que você mastigue e saboreie totalmente cada mordida antes de passar para a próxima. Muitas pessoas descobrem que, quando comem assim, sentem-se satisfeitas com menos comida — não porque estão restringindo, mas porque estão absorvendo o prazer de comer.\nSaborear cada mordida é um ato de gratidão pelo alimento que está dando ao seu corpo. Perceba a crocância de um vegetal fresco, a cremosidade do abacate, o calor de uma sopa bem temperada. Quando você envolve todos os seus sentidos na experiência alimentar, as refeições se tornam mais ricas e satisfatórias, mesmo quando as porções são modestas.\nA alimentação consciente também ajuda a distinguir entre fome física e fome emocional. A fome física aumenta gradualmente, pode ser satisfeita por muitos alimentos diferentes e para quando você está confortavelmente satisfeita. A fome emocional tende a aparecer de repente, deseja comidas reconfortantes específicas e não vai embora mesmo depois de comer bastante. Aprender a diferenciar é uma das habilidades mais empoderadoras do seu kit de bem-estar.",
            "keyTakeaways": [
                "Comer sem distrações permite perceber sinais de fome e saciedade",
                "Colocar o garfo na mesa entre mordidas desacelera naturalmente o ritmo",
                "Sinais de saciedade levam cerca de 20 minutos para se registrar completamente",
                "Envolver todos os sentidos torna as refeições mais satisfatórias com menos comida",
                "A alimentação consciente ajuda a distinguir fome física de fome emocional"
            ],
            "actionStep": "Na sua próxima refeição, comprometa-se a comer com zero distrações — sem celular, sem TV, sem leitura. Coloque o garfo na mesa a cada três mordidas. Observe o sabor da comida e como seu corpo se sente enquanto come. Use um timer se necessário para garantir pelo menos 20 minutos para a refeição.",
            "journalPrimary": "Com que frequência você come distraída? O que acha que poderia descobrir sobre sua comida — ou sobre si mesma — se começasse a comer com mais atenção?"
        },
        38: {
            "introduction": "Seu corpo é um sistema incrivelmente inteligente, e hoje vamos explorar a orquestra hormonal que influencia seu peso. Entender esses hormônios não é sobre adicionar complexidade à sua jornada — é sobre te empoderar para trabalhar *com* os ritmos naturais do seu corpo em vez de inconscientemente trabalhar contra eles. Conhecimento é verdadeiramente poder aqui.",
            "mainContent": "Pense nos seus hormônios como mensageiros que carregam instruções importantes pelo seu corpo. Quando se trata de peso, três hormônios têm papéis protagonistas: insulina, leptina e grelina. Entender o que cada um faz ajuda você a fazer escolhas que apoiam seu funcionamento saudável.\nA insulina é produzida pelo pâncreas sempre que você come, particularmente quando come carboidratos. Seu trabalho é ajudar a transportar a glicose (açúcar no sangue) do sangue para as células, para ser usada como energia. Quando a insulina está funcionando bem, seu açúcar no sangue fica estável e seu corpo usa os alimentos eficientemente como combustível. Porém, quando a insulina permanece cronicamente elevada — frequentemente por comer com muita frequência, alto consumo de açúcar ou beliscar constantemente — seu corpo muda para o modo de armazenamento de gordura. Apoiar o funcionamento saudável da insulina através de refeições equilibradas, espaçamento adequado entre as refeições e escolher carboidratos complexos em vez de refinados é uma estratégia fundamental para sua jornada de bem-estar.\nA leptina é seu hormônio do \"estou satisfeita\", produzida pelas células de gordura para dizer ao cérebro que você comeu o suficiente. Quando a leptina está funcionando corretamente, você naturalmente para de comer quando está confortavelmente satisfeita. Porém, em alguns casos — particularmente com alimentação excessiva crônica ou inflamação — o cérebro pode se tornar resistente aos sinais da leptina, tornando mais difícil sentir satisfação. A boa notícia é que a sensibilidade à leptina pode ser melhorada com sono de qualidade, movimento regular e uma alimentação anti-inflamatória.\nA grelina é a contraparte da leptina — é seu hormônio do \"estou com fome\", produzida principalmente no estômago. A grelina aumenta antes das refeições e cai depois de comer. Curiosamente, a privação de sono aumenta os níveis de grelina, o que explica por que você pode sentir uma fome voraz após uma noite mal dormida. Horários regulares de refeição, proteína adequada e sono consistente ajudam a manter a grelina em equilíbrio saudável.\nA coisa linda é que os mesmos hábitos fundamentais apoiam os três hormônios: refeições equilibradas com proteína e fibra adequadas, sono de qualidade, gestão do estresse e movimento suave regular. Você não precisa microgerenciar seus hormônios — simplesmente precisa criar as condições onde eles possam funcionar otimamente. Seu corpo sabe o que fazer quando recebe o apoio certo.",
            "keyTakeaways": [
                "A insulina regula o açúcar no sangue e o armazenamento de gordura — mantenha-a equilibrada com alimentos integrais e espaçamento entre refeições",
                "A leptina sinaliza saciedade; sua função melhora com sono e alimentos anti-inflamatórios",
                "A grelina impulsiona a fome e aumenta com a privação de sono",
                "Os mesmos hábitos saudáveis — sono, refeições equilibradas, movimento — apoiam os três hormônios",
                "Trabalhar com seus hormônios significa trabalhar com seu corpo, não contra ele"
            ],
            "actionStep": "Foque em um hábito que apoia seus hormônios hoje: ou ir dormir 30 minutos mais cedo (apoiando leptina e grelina), ou garantir que cada refeição hoje inclua proteína, fibra e gordura saudável (apoiando o equilíbrio da insulina).",
            "journalPrimary": "Você já percebeu sentir mais fome após uma noite mal dormida, ou desejar doces quando estressada? Como entender as razões hormonais por trás desses padrões muda como você se sente sobre eles?"
        },
        39: {
            "introduction": "Aqui vai algo maravilhoso para saber: *como* você prepara sua comida importa tanto quanto *o que* você come. Hoje vamos explorar métodos de cozimento que preservam nutrientes, realçam sabores e apoiam seus objetivos de bem-estar — tudo isso tornando suas refeições absolutamente deliciosas. Cozinhar saudável não significa cozinhar sem graça, e estou animada para te mostrar por quê!",
            "mainContent": "A forma como você cozinha pode mudar dramaticamente o perfil nutricional do alimento. Fritar por imersão, por exemplo, pode mais que dobrar o teor calórico ao saturar o alimento com óleo. A empanação adiciona carboidratos refinados e ainda mais absorção de gordura. Molhos pesados com creme podem transformar um prato simples e nutritivo em algo que trabalha contra seus objetivos. A notícia maravilhosa é que existem tantos métodos deliciosos de cozimento que preservam e até realçam a bondade dos seus alimentos.\nCozinhar no vapor é um dos métodos mais gentis disponíveis. Preserva mais vitaminas e minerais que quase qualquer outra técnica porque o alimento nunca entra em contato direto com a água, onde os nutrientes podem se perder. Vegetais no vapor mantêm suas cores vibrantes, textura crocante satisfatória e valor nutricional completo. Uma simples panela de bambu ou um cesto de inox é tudo que você precisa.\nGrelhar e assar trazem à tona a doçura natural dos alimentos através da caramelização, criando sabores profundos e complexos sem calorias adicionais. Vegetais assados — pense em couve-de-bruxelas, batata-doce, couve-flor ou pimentões — desenvolvem um sabor rico, quase amanteigado, que é irresistível. Um fio de azeite, sal e suas ervas favoritas são tudo que você precisa.\nAssar no forno é incrivelmente versátil e prático, permitindo preparar proteínas e vegetais com mínima gordura adicionada. A airfryer se tornou uma opção popular que cria aquela crocância satisfatória que amamos com uma fração do óleo usado na fritura tradicional. Ambos os métodos são fantásticos para cozinhar em quantidade.\nUma das mudanças mais empolgantes que você pode fazer é descobrir o mundo das ervas e temperos. Em vez de depender de sal, açúcar e molhos pesados para dar sabor, explore a incrível gama de sabores que ervas e temperos oferecem — tudo com praticamente zero calorias. Manjericão fresco, alecrim, coentro, cominho, páprica defumada, alho e gengibre podem transformar ingredientes simples em refeições de nível restaurante. Isso não é sobre sacrifício; é sobre elevar sua culinária a um novo patamar.",
            "keyTakeaways": [
                "Cozinhar no vapor preserva mais nutrientes e mantém os vegetais vibrantes",
                "Grelhar e assar realçam a doçura natural através da caramelização",
                "A airfryer cria crocância com mínimo óleo",
                "Ervas e temperos adicionam sabor incrível sem adicionar calorias",
                "Métodos saudáveis de cozimento podem tornar a comida mais gostosa, não menos"
            ],
            "actionStep": "Escolha uma refeição hoje e prepare-a usando um destes métodos: vapor, grelha, assado, forno ou airfryer. Experimente pelo menos duas ervas ou temperos que normalmente não usa. Perceba como comida saudável pode ser saborosa!",
            "journalPrimary": "Em quais métodos de cozimento você mais confia? Existem técnicas mais saudáveis que gostaria de explorar? Que ervas ou temperos você tem curiosidade de experimentar?"
        },
        40: {
            "introduction": "Em um mundo cheio de opções \"sem açúcar\", é natural se perguntar: os adoçantes artificiais são realmente uma boa troca? Hoje vamos ter uma conversa honesta e equilibrada sobre esses substitutos comuns do açúcar. Como sempre, o conhecimento te empodera a fazer as escolhas que são melhores para o *seu* corpo e a *sua* jornada.",
            "mainContent": "Adoçantes artificiais como aspartame, sucralose e sacarina foram criados para oferecer doçura sem as calorias do açúcar. Na superfície, isso parece uma solução perfeita — todo o sabor sem nenhum impacto energético. No entanto, pesquisas da última década revelaram um quadro mais complexo que vale a pena entender.\nUma das descobertas mais fascinantes é que adoçantes artificiais podem na verdade aumentar os desejos por açúcar em vez de reduzi-los. Funciona assim: quando sua língua sente algo doce, seu cérebro espera que calorias venham em seguida. Quando essas calorias nunca chegam, seu cérebro pode intensificar os sinais de fome, essencialmente dizendo: \"Cadê a energia que você prometeu?\" Isso pode levar a comer demais mais tarde no dia, potencialmente anulando a economia de calorias da escolha pelo adoçante artificial.\nTambém há evidências crescentes de que alguns adoçantes artificiais podem perturbar seu microbioma intestinal — a comunidade de bactérias benéficas no seu sistema digestivo que desempenha um papel crucial no metabolismo, função imunológica e até no humor. Um intestino saudável apoia o controle de peso, então qualquer coisa que o perturbe merece consideração cuidadosa.\nSe você está procurando alternativas tanto ao açúcar refinado quanto aos adoçantes artificiais, existem algumas opções mais gentis que valem a pena explorar. A estévia, derivada de uma folha de planta, e o adoçante de fruta-dos-monges são opções naturais que não parecem elevar o açúcar no sangue da mesma forma. Usados com moderação, podem satisfazer seu desejo por doce sendo mais gentis com seu corpo. Mas a frase-chave é \"com moderação\" — mesmo adoçantes naturais podem manter a preferência por sabores intensamente doces se usados em excesso.\nEm última análise, a abordagem mais poderosa é gradualmente retreinar seu paladar para apreciar menos doçura no geral. Conforme você reduz adoçantes de todos os tipos, vai se impressionar com como suas papilas gustativas se adaptam. Alimentos que antes pareciam sem graça começarão a revelar seus sabores naturais, e você encontrará satisfação genuína na doçura sutil de alimentos reais e integrais.",
            "keyTakeaways": [
                "Adoçantes artificiais podem aumentar desejos ao enganar o cérebro que espera calorias",
                "Alguns adoçantes artificiais podem perturbar bactérias intestinais benéficas",
                "Alternativas naturais como estévia e fruta-dos-monges são opções mais gentis quando usadas com moderação",
                "Reduzir gradualmente todos os adoçantes ajuda a retreinar seu paladar",
                "O objetivo é apreciar os sabores naturais de alimentos reais e integrais"
            ],
            "actionStep": "Faça um inventário dos adoçantes artificiais na sua rotina diária — bebidas diet, produtos sem açúcar, sachês de adoçante. Escolha um para reduzir ou substituir esta semana por uma opção mais natural, ou simplesmente tente ficar sem.",
            "journalPrimary": "Quanta doçura você sente que \"precisa\" no seu dia? Como sua experiência com a comida poderia mudar se seu paladar se adaptasse a menos doçura ao longo do tempo?"
        },
    }

def apply_translations(data, translations):
    count = 0
    for lesson in data['lessons']:
        day = lesson['dayNumber']
        if day in translations:
            t = translations[day]
            lesson['content']['introduction'] = t['introduction']
            lesson['content']['mainContent'] = t['mainContent']
            lesson['content']['keyTakeaways'] = t['keyTakeaways']
            lesson['content']['actionStep'] = t['actionStep']
            lesson['journalPrompt']['primary'] = t['journalPrimary']
            count += 1
    return count

if __name__ == '__main__':
    filepath = 'src/i18n/locales/pt/lessons.json'
    import json
    with open(filepath, 'r') as f:
        data = json.load(f)
    translations = get_translations()
    count = apply_translations(data, translations)
    with open(filepath, 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Applied {count} translations (Days 21-40)")
